bootstrap/README.md
bootstrap/app.php
packages/realtime-compiler/src/Concerns/InteractsWithLaravel.php

Provides backwards compatibility by giving a grace period to migrate old projects to handle the breaking move of bootstrap/app.php to app/bootstrap.php in https://github.com/caendesilva/hyde-monorepo/commit/f08c97964a10d1e66b6e50ba91b82d30cb05ac28.
The PR adds back the legacy file, but with a deprecation notice. It also updates the HydeRC to fix https://github.com/caendesilva/hyde-monorepo/issues/13.

Handle moving of the bootstrap file to provide backwards compatibility for the migration period

---

.github/workflows/split-monorepo.yml
build/tools/checksums.txt
build/tools/update-composer.php

Creates an improved update-composer.php script that removes the packages entry as well as replaces dev-master version requirements with configured constants. Also updates the actual script, together with the checksums as an added security.

Improve transformation of the hyde/hyde composer.json in the monorepo split job

---

packages/framework/src/Services/ValidationService.php
tests/Feature/Commands/HydeValidateCommandTest.php
tests/Feature/Services/ValidationServiceTest.php

If there are no documentation pages there is no need for an index page, and the test can safely be skipped.

Skip documentation index validation test if the _docs directory is empty

---

CHANGELOG.md
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Contracts/PageContract.php
packages/framework/tests/Unit/PageModelGetAllFilesHelperTest.php

Adds a helper to get an array of all the source file slugs for the model.
Essentially an alias of CollectionService::getAbstractPageList().
Example:
```php
MarkdownPost::all() = ['hello-world']
```

Fix #44 Add ModelClass::files() helper

---

CHANGELOG.md
docs/documentation-pages.md
packages/framework/src/Actions/GeneratesNavigationMenu.php

Changed the default position of the automatic navigation menu link to the right, also making it configurable.
You can customize the priority using the following config value in the `config/docs.php` file:
```php
'navigation_link_priority' => 500 // Default value before this change
```

Change priority of the automatic docs link in the navbar so it is after standard pages 

---

packages/framework/tests/Feature/Actions/PublishesHomepageViewTest.php
packages/framework/tests/Feature/Concerns/HasPageMetadataTest.php
packages/framework/tests/Feature/ConfigurableFeaturesTest.php
packages/framework/tests/Feature/DocumentationPageParserTest.php
packages/framework/tests/Feature/FindsContentLengthForImageObjectTest.php
packages/framework/tests/Feature/HydeHelperFacadeTest.php
packages/framework/tests/Feature/ImageModelTest.php
packages/framework/tests/Feature/MetadataHelperTest.php
packages/framework/tests/Feature/Services/BladeDownProcessorTest.php
packages/framework/tests/Feature/Services/FileCacheServiceTest.php
packages/framework/tests/Feature/Services/HasConfigurableMarkdownFeaturesTest.php
packages/framework/tests/Feature/Services/HydeSmartDocsTest.php
packages/framework/tests/Feature/Services/Markdown/CodeblockFilepathProcessorTest.php
packages/framework/tests/Feature/Services/Markdown/ShortcodeProcessorTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php
packages/framework/tests/Unit/AuthorGetNameTest.php
packages/framework/tests/Unit/BlogPostFrontMatterIsOptionalTest.php
packages/framework/tests/Unit/DateStringTest.php
packages/framework/tests/Unit/DocumentationPageTest.php
packages/framework/tests/Unit/FileHelperRelativeLinkTest.php
packages/framework/tests/Unit/HasAuthorTest.php
packages/framework/tests/Unit/HasDynamicTitleTest.php
packages/framework/tests/Unit/HasFeaturedImageTest.php
packages/framework/tests/Unit/HasPageMetadataRssFeedLinkTest.php

Removes Copilot comments and renames test method names to snake_case to match the convention

Clean up tests

---

CHANGELOG.md
packages/framework/src/Contracts/MarkdownDocumentContract.php
packages/framework/src/Models/DocumentationPage.php
packages/framework/src/Models/MarkdownDocument.php
packages/framework/src/Models/MarkdownPost.php
packages/framework/tests/Unit/MarkdownPageModelConstructorArgumentsAreOptionalTest.php

Adds the MarkdownDocumentContract interface to markdown based pages to keep a consistent and predictable state and makes the constructor arguments for Markdown page models optional to fix https://github.com/hydephp/develop/issues/65

Make page model constructor parameters optional

---

CHANGELOG.md
packages/framework/src/Actions/ChecksIfConfigIsUpToDate.php

Will be replaced by checking the version instead.

Deprecate ChecksIfConfigIsUpToDate.php

---

.env.example
CHANGELOG.md
config/hyde.php
docs/advanced-customization.md
packages/framework/src/Actions/PostBuildTasks/GenerateSitemap.php
packages/framework/src/Commands/HydeBuildStaticSiteCommand.php
packages/framework/src/Contracts/AbstractBuildTask.php
packages/framework/src/Contracts/BuildTaskContract.php
packages/framework/src/Services/BuildHookService.php
packages/framework/tests/Feature/Services/BuildHookServiceTest.php

>info This feature should not be in danger of breaking things. However, it was added very recently and the implementation may change at any moment. See <a href=" https://github.com/hydephp/develop/issues/79">this GitHub issue</a> for up to date information.
Since v0.40.0 you can create custom post-build hooks. These hooks are code that is executed automatically after the site has been built using the `php hyde build` command.
Here is a minimal example to get you started. For all these examples we assume you put the file in the `App/Actions` directory, but you can put them anywhere.
```php
class SimpleHook extends AbstractBuildTask
{
public function run(): void
{
$this->info('Hello World!');
}
}
```
This will then output the following, where you can see that some extra output, including …

Add easy to use post-build hooks #79

---

app/Monorepo/Commands/MonorepoMakeReleaseCommand.php
app/Providers/AppServiceProvider.php

Somehow, somewhere, the AppServiceProvider that was supposed to be restored got lost during the way. While I look into how this happened, I'm yanking the affected Hyde/Hyde release and pushing a beta patch release.

Fix missing AppServiceProvider

---

packages/framework/src/Concerns/Internal/FileHelpers.php
packages/framework/tests/Feature/HydeDocsIndexPathTest.php

Uses the model class property, and adds a test to make sure it works.

Fix bug #94: Hyde::docsIndexPath() checks the hard-coded source directory 

---

CHANGELOG.md
docs/architecture-concepts.md
packages/framework/src/Services/CollectionService.php
packages/framework/tests/Feature/Services/CollectionServiceTest.php

Added configuration option `hyde.media_extensions` to allow you to specify additional comma separated media file types. Fixes https://github.com/hydephp/develop/issues/39;
```php
config('hyde.media_extensions', 'png,svg,jpg,jpeg,gif,ico,css,js'))
```

Add configuration option to allow more file types in the  media directory

---

CHANGELOG.md
config/hyde.php
docs/advanced-customization.md
packages/framework/config/hyde.php
packages/framework/src/HydeServiceProvider.php

The `hyde.site_output_path` option was recently deprecated. This update adds an alternative which resolves the relative path within the service provider. This makes it safer to set the output directory to something within the project. If one wants to use an absolute path outside the project that must be done in a service provider, which has now been documented.
> **Warning**
> Hyde deletes all files in the output directory before compiling the site. Don't set this path to a directory that contains important files!
If you want to store your compiled website in a different directory than the default `_pages`, you can change the path using the following configuration option in config/hyde.php. The path is expected to be relative to your project root.
```php
// filepath config/hyde.php
return …
```

Add a safer output directory config option to replace deprecated setting

---

CHANGELOG.md
packages/realtime-compiler/bin/server.php
packages/realtime-compiler/src/Http/ExceptionHandler.php

Fixes a bug in the auxiliary exception handler leading to unintentional recursion causing out of memory errors in both the browser and the PHP server.

HydeRC: Fix bug causing out of memory failures in exception handler

---

packages/framework/src/HydeServiceProvider.php
packages/framework/src/Modules/DataCollections/DataCollection.php
packages/framework/src/Modules/DataCollections/DataCollectionServiceProvider.php
packages/framework/src/Modules/DataCollections/Facades/Collection.php
packages/framework/src/Modules/DataCollections/Facades/MarkdownCollection.php
packages/framework/src/Modules/README.md
tests/Hyde/Feature/Hyde/Framework/Testing/Modules/DataCollections/DataCollectionTest/DataCollectionTest.php

Not sure if this is the best name for it, but this update adds a DataCollection module (which may me merged into the core as it became much simpler than I expected), which reads flatfile content and parses them into usable Laravel collections.
Currently only a Markdown collection type is added. This is easel accessible with the MarkdownCollection facade that is made available to Blade views through the DataCollectionServiceProvider.
Supply the name for a subdirectory of the new `_data` directory to the facade to get a collection with the parsed files.
For example, imagine we have a directory called `_data/testimonials` where we collect testimonials in the form of Markdown files, with front matter to specify the author and link.
```md
// filepath: _data/testimonials/one.md
---
author: John …
```

Create static file collections

---

CHANGELOG.md
docs/collections.md
package-lock.json
package.json
packages/hyde/composer.json

- Added configuration option `hyde.media_extensions` to allow you to specify additional comma separated media file types. [#39](https://github.com/hydephp/develop/issues/39)
- Adds a safer config option `hyde.output_directory` for customizing the output directory
- Adds a file-based way to create and interact with collections, https://hydephp.com/docs/master/collections
- Removed the `--pretty` build command option which was deprecated in v0.25.x
- Removed deprecated internal AssetManager trait which was replaced with the Asset facade
- HydeRC: Fixes a bug in the auxiliary exception handler leading to unintentional recursion causing out of memory errors in both the browser and the PHP server.

v0.43.0-beta - 2022-06-25 - File-based Collections

---

.github/workflows/split-monorepo.yml

Want to test pushing the monorepo packages directly to the master branches. Since we are in v0.x I think it's okay if they are not entirely stable. This will reduce developer complexity a lot, and make it faster to deploy releases, allowing for more frequent and more scoped releases with less headache as merge pull requests don't need to be synced.
Once Hyde enters 1.x and becomes stable develop branches would make more sense.

Push split monorepo directly to master branches

---

CHANGELOG.md
packages/framework/resources/views/layouts/app.blade.php

I think this was a layover when using the app layout as the base for the documentation site. Now that the docs are in a separate layout we aren't using it. Resolves https://github.com/hydephp/develop/issues/118

Remove unused `$withoutNavigation` variable from the app layout

---

CHANGELOG.md
packages/framework/resources/views/components/docs/labeled-sidebar-navigation-menu.blade.php
packages/framework/src/Actions/GeneratesNavigationMenu.php
packages/framework/src/Concerns/HasDynamicTitle.php
packages/framework/src/Helpers/HydeHelperFacade.php
packages/framework/src/Hyde.php
packages/framework/src/Models/DocumentationSidebarItem.php
packages/framework/tests/Unit/HydeHelperFacadeMakeTitleTest.php

The Hyde::titleFromSlug() helper is internally moved and is referenced through the new Hyde::makeTitle() helper which is an improved version, with a more general name. This is done by replacing the underlying implementation to use the Str::headline() helper instead of Str::title(), combined with a lookup table of auxiliary words that should be lowercase, while ensuring the first word is always capitalized.
The helper does not support fully uppercase input, which is okay since it is mainly intended to convert slugs to titles, as a fallback. I think it may be out of scope to parse uppercase input Hyde source filenames are recommended to be lowercase, but am open to change if requested.

Improve Hyde title generation helper

---

docs/advanced-customization.md
packages/framework/src/Actions/CreatesNewPageSourceFile.php
packages/framework/src/Concerns/Internal/FileHelpers.php
packages/framework/src/Concerns/RegistersDefaultDirectories.php
packages/framework/src/Concerns/ValidatesExistence.php
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Contracts/PageContract.php
packages/framework/src/HydeServiceProvider.php
packages/framework/src/Models/BladePage.php
packages/framework/src/Models/DocumentationPage.php
packages/framework/src/Models/MarkdownPage.php
packages/framework/src/Models/MarkdownPost.php
packages/framework/src/Services/CollectionService.php
packages/framework/src/Services/DiscoveryService.php
packages/framework/src/Services/SitemapService.php
packages/framework/src/StaticPageBuilder.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Feature/Concerns/HasPageMetadataTest.php
packages/framework/tests/Feature/StaticPageBuilderTest.php
packages/framework/tests/Unit/DocumentationPageTest.php

This update refactors the internal page models to ensure a more predictable and consistent state. This is in large part done by further defining the page model contract, and abstracting the implementations to the base class, leading to less boilerplate for the actual implementations, while gaining a more defined source of truth. It also adds the scaffolding to customize more output directories, and unifies this with the legacy documentation output paths. Besides that, this PR does not add much in the terms of features, it does make several changes that may be considered breaking to the package developers.

Improve internal page model structure

---

CHANGELOG.md
packages/framework/src/Services/CollectionService.php
packages/framework/tests/Feature/Commands/HydeMakePageCommandTest.php
packages/framework/tests/Feature/DocumentationPageParserTest.php
packages/framework/tests/Feature/Services/BuildHookServiceTest.php
packages/framework/tests/Feature/Services/CollectionServiceTest.php

Also improves the tests, and renames some of the helpers

Refactor the CollectionService to reduce boilerplate

---

CHANGELOG.md
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Contracts/MarkdownDocumentContract.php
packages/framework/src/Contracts/MarkdownPageContract.php
packages/framework/src/Models/MarkdownDocument.php
packages/framework/tests/Unit/MarkdownDocumentTest.php

Creates a MarkdownPage contract, adds a __toString magic method, and a method to render documents into HTML, which fixes https://github.com/hydephp/develop/issues/109.

Refine markdown document classes

---

CHANGELOG.md
config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/HydeServiceProvider.php

Removes support for the config option which was deprecated in the last release. It has since been replaced with the output_directory setting.

Removed deprecated 'hyde.site_output_path' config option

---

CHANGELOG.md
packages/framework/src/Commands/HydeBuildStaticSiteCommand.php
packages/framework/tests/Feature/Commands/BuildStaticSiteCommandTest.php

First checks if the configured directory is on the whitelist of safe directories (can be configured using `hyde.safe_output_directories`, please submit PRs/comments with more ideas for default safe directories!), and asks if the user really wants the directory to be emptied. Defaults to false. Then when it's okay to proceed, the output is emptied using a less nuclear approach to prevent accidental file deletions. Yes, I accidentally deleted my .git directory. And I did so twice. (And the somehow the vendor directory in the CI).

Improves how the site output directory is emptied, helping prevent accidental deletion of files

---

packages/framework/src/Services/CollectionService.php
packages/framework/tests/Feature/GeneratesNavigationMenuTest.php
packages/framework/tests/Feature/Services/CollectionServiceTest.php

This is the underlying problem for this the navigation menu bug, which this will fix https://github.com/hydephp/develop/issues/139. See that thread for the error and the fix details.

Fix bug causing files starting with underscores to add empty values to the file collection array

---

CHANGELOG.md
packages/framework/src/Actions/GeneratesDocumentationSearchIndexFile.php
packages/framework/src/Actions/GeneratesNavigationMenu.php
packages/framework/src/Commands/HydeBuildSearchCommand.php
packages/framework/src/Commands/HydeBuildStaticSiteCommand.php
packages/framework/src/Helpers/HydeHelperFacade.php
packages/framework/src/Hyde.php
packages/framework/src/Services/CollectionService.php
packages/framework/src/Services/DocumentationSidebarService.php
packages/framework/src/Services/ValidationService.php
packages/framework/tests/Feature/DocumentationPageParserTest.php
packages/framework/tests/Feature/MarkdownPageTest.php
packages/framework/tests/Feature/Services/CollectionServiceTest.php

Remove deprecated code

---

CHANGELOG.md
docs/advanced-customization.md
packages/framework/src/Concerns/RegistersFileLocations.php
packages/framework/src/HydeServiceProvider.php

The original name was deprecated in v0.44.0 where the rename was advised.

Rename internal trait RegistersDefaultDirectories to RegistersFileLocations

---

CHANGELOG.md
packages/framework/src/Concerns/RegistersFileLocations.php
packages/framework/src/HydeServiceProvider.php
packages/framework/tests/Unit/HydeServiceProviderTest.php

Moves methods related to directory mappings from the HydeServiceProvider to the RegistersFileLocations trait, making it easier to override them.

Refactor the HydeServiceProvider structure

---

CHANGELOG.md
packages/framework/src/HydeServiceProvider.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/tests/Unit/DocumentationPageTest.php

This method has been replaced with `DocumentationPage::getOutputPath()`

Remove deprecated `DocumentationPage::getDocumentationOutputPath()`

---

packages/framework/src/helpers.php
packages/framework/tests/Feature/HelpersTest.php

Adds a helper which is a wrapper for the array_map function. However, the returned array is filtered for duplicates and its keys are reset. The callback function also comes after the original array as I think that presents a more logical developer flow.

Add `array_map_unique()` helper

---

composer.json

This will speed up a lot of stuff. And one can always pass the optimize-autoloader flag when running Composer commands, however there does not seem to be an inverse. When we move to stable v1 it'd be good to enable it again.

Disable autoloader optimization in default composer config

---

packages/framework/src/Hyde.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Feature/Actions/GeneratesDocumentationSearchIndexFileTest.php
packages/framework/tests/Feature/Commands/HydeBuildSearchCommandTest.php
packages/framework/tests/Feature/Commands/HydeRebuildStaticSiteCommandTest.php
packages/framework/tests/Feature/DataCollectionTest.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Feature/GeneratesNavigationMenuTest.php
packages/framework/tests/Feature/RebuildServiceTest.php
packages/framework/tests/Feature/RouteTest.php
packages/framework/tests/Feature/RouterTest.php
packages/framework/tests/Feature/Services/CollectionServiceTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarServiceTest.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php
packages/framework/tests/Feature/Services/ValidationServiceTest.php
packages/framework/tests/Feature/SourceDirectoriesCanBeChangedTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php
packages/framework/tests/Unit/PageModelGetAllFilesHelperTest.php
packages/framework/tests/Unit/PageModelGetHelperTest.php
packages/framework/tests/Unit/PageModelParseHelperTest.php
packages/framework/tests/Unit/SourceFilesInCustomDirectoriesCanBeCompiledTest.php
packages/framework/tests/Unit/Views/ScriptsComponentViewTest.php
packages/framework/tests/Unit/Views/StylesComponentViewTest.php
tests/TestCase.php

Implements the Laravel macroable trait and adds `Hyde::touch($path)` instead of `touch(Hyde::path($path))`,  which will speed up the writing of tests.

Add macroable trait to the Hyde facade

---

RELEASE_NOTES.md
packages/framework/src/Services/DiscoveryService.php

> The Discovery Service (previously called BuildService) provides helper methods for source file autodiscovery used in the building process to determine where files are located and how to parse them.
Autodiscovery is now powered by the Router. The helpers here can be moved to FluentPathHelpers.php

Deprecate `DiscoveryService.php`

---

packages/realtime-compiler/src/Actions/Compiler.php
packages/realtime-compiler/src/Routing/LegacyPageRouter.php
packages/realtime-compiler/src/Routing/PageRouter.php
packages/realtime-compiler/src/Routing/Router.php

Separates the old compiling logic so it can stick around for a bit adding backwards compatibility. The old classes have been marked as deprecated.
The main services (automatically used when the foundation is available) now fetches routes from the Hyde route index, providing much greater compatibility as we don't have to attempt to reverse engineer paths at runtime.
Instead, the RC now works by formatting the URI string to a normalized route key, then using that to fetch the route from the route index. The route model is then passed directly to the static page builder for compiling.

Update the Realtime Compiler plugin to use the new Router service

---

.idea/develop.iml
packages/framework/src/Services/SitemapService.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php

Refactors how the sitemap is generated, by utilizing the router. The actual XML result does not change.

Update sitemap generator to use the router

---

packages/framework/src/Models/NavItem.php
packages/framework/tests/Unit/NavItemTest.php

Fixes https://github.com/hydephp/develop/issues/215

Add a NavItem::toRoute() helper 

---

docs/architecture-concepts.md
packages/framework/resources/views/components/link.blade.php
packages/framework/src/HydeServiceProvider.php
packages/framework/src/Views/Components/LinkComponent.php
packages/framework/tests/Unit/Views/Components/LinkComponentTest.php

Adds an `<x-link />` component that hooks into the View factory to resolve relative links automatically. No more having to pass the `$currentPage` property to a bunch of `relativeLink` helpers!

Add a link component to resolve routes automatically

---

packages/framework/src/Contracts/RouteFacadeContract.php
packages/framework/src/Models/Route.php
packages/framework/tests/Feature/RouteTest.php

Adds a helper to get the home route, usually the index page route.

Add `Route::home()` helper

---

packages/framework/src/Contracts/RoutingServiceContract.php
packages/framework/src/Services/RoutingService.php
packages/framework/tests/Feature/RoutingServiceTest.php

This hook can then be used by package developers to add custom routes.
For example:
```php
class MyServiceProvider extends ServiceProvider {
public function boot() {
RoutingService::getInstance()->addRoute(
(new CustomPage('source-file'))->getRoute()
);
}
}
```

Add public add route method to route service

---

RELEASE_NOTES.md
config/hyde.php
docs/customization.md
packages/framework/config/hyde.php
packages/framework/resources/views/layouts/app.blade.php
packages/framework/resources/views/layouts/footer.blade.php
packages/framework/src/Actions/ConvertsFooterMarkdown.php

Most websites have a footer with copyright details and contact information. You probably want to change the Markdown to include your information, though you are of course welcome to keep the default attribution link!
The footer component is made up of a few levels of components, depending on how much you want to customize.
There are two ways to customize the footer text. First, you can set it in the configuration file:
```php
// filepath: config/hyde.php
'footer' => 'Site proudly built with [HydePHP](https://github.com/hydephp/hyde) 🎩',
```
If you don't want to write Markdown in the configuration file, you can create a Markdown file in your includes directory. When this file is found, it will be used instead of the configuration setting.
```markdown
// filepath: …
```

Refactor footer component to use includes facade

---

.github/workflows/test-cypress.yml
tests/Cypress/.gitignore
tests/Cypress/cypress.config.js
tests/Cypress/cypress/e2e/fixture-0.cy.js
tests/Cypress/cypress/support/e2e.js
tests/Cypress/package-lock.json
tests/Cypress/package.json

Sets up the project and CI to run automated [Cypress](https://cypress.io/) tests, and adds two basic test specs.

Set up infrastructure for automated Cypress frontend testing

---

.github/workflows/test-pull-requests.yml
.idea/php.xml
.idea/runConfigurations/Browser__Dusk_.xml
README.md
composer.json
composer.lock
packages/framework/resources/views/homepages/post-feed.blade.php
packages/framework/src/HydeServiceProvider.php
phpunit.dusk.xml
tests/Browser/DefaultHomepageTest.php
tests/Browser/DuskServiceProvider.php
tests/Browser/ExampleTest.php
tests/Browser/HighLevelViewTest.php
tests/Browser/Pages/HomePage.php
tests/Browser/Pages/Page.php
tests/Browser/console/.gitignore
tests/Browser/screenshots/.gitignore
tests/Browser/source/.gitignore
tests/DuskBaseTestCase.php
tests/DuskTestCase.php

Cypress is nice and gives instant visual feedback, however it breaks productivity having to swap to a completely different framework and language. This PR will explore using Laravel Dusk, using a ported test case so it can run with Laravel Zero.

Add Laravel Dusk for browser testing

---

composer.json
composer.lock
packages/framework/composer.json
packages/hyde/composer.json

This makes the framework module more modular and lightweight, though the end user experience should not be different.

Move laravel-zero/framework dependency to hyde/hyde

---

app/bootstrap.php

These comments were left to ease the transition and can in my opinion now be removed.

Remove comments for deprecated base path setup in bootstrap script

---

RELEASE_NOTES.md
packages/framework/resources/views/layouts/scripts.blade.php

[Alpine](https://alpinejs.dev/) is a rugged, minimal tool for composing behavior directly in the markup.
Adding it to HydePHP will allow us to port HydeFront scripts directly to the Blade views, allowing for extensive customization, and improved compatibility between versions, as well as reduced complexity.

Add Alpine.js

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/search.blade.php
packages/framework/resources/views/layouts/docs.blade.php

Since the dialog element is not fully supported (looking at you Safari) this PR switches to a custom AlpineJS implementation until the dialog element becomes more stable.
Fixes https://github.com/hydephp/develop/issues/41

Replace search dialog element with custom implementation

---

packages/framework/resources/views/layouts/navigation.blade.php

Adds the `x-uncloak-md` class to the navigation menu, preventing it from being cloaked by Alpine.

Fix visual bug where navigation menu flashes on desktop until Alpine is loaded

---

.github/workflows/split-monorepo.yml
RELEASE_NOTES.md
packages/hyde/composer.json
packages/testing/stubs/hyde-testing-workflow.stub

Building a website with HydePHP is often a bit different than developing a full stack application with Laravel, as with Hyde you mainly focus on content for the frontend. For the majority of use cases, users of the Hyde/Hyde package will not need to run tests (and if they do, they'll likely be with a front end tool like Cypress, instead of PHPUnit/Pest).
Removing these test files from the split package will reduce complexity (and resolve https://github.com/hydephp/hyde/issues/206). Users that need to run tests can with ease set up a suite by installing the framework of their choice. I also added a [sample workflow file](https://github.com/hydephp/develop/blob/6e41acf2518d1d89e196d3040e7faebf89af54f4/packages/testing/stubs/hyde-testing-workflow.stub) (the one currently in hyde/hyde what …

Remove test files from Hyde package

---

RELEASE_NOTES.md
docs/console-commands.md
packages/framework/src/Commands/HydeMakePageCommand.php
packages/framework/tests/Feature/Commands/HydeMakePageCommandTest.php

Adds new shorthands to the `hyde make:page` command: `--blade` or `--docs` instead of `--type=blade` or `--type=docs`.

Improve the make:page command

---

RELEASE_NOTES.md
packages/framework/resources/views/components/article-excerpt.blade.php
packages/framework/resources/views/components/post/article.blade.php
packages/framework/src/Commands/HydeBuildSitemapCommand.php
packages/framework/src/Concerns/GeneratesPageMetadata.php
packages/framework/src/Concerns/HasPageMetadata.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/src/Models/Route.php
packages/framework/src/Services/RssFeedService.php
packages/framework/src/Services/SitemapService.php
packages/framework/src/Services/ValidationService.php
packages/framework/tests/Unit/HydeUriPathHelperTest.php
packages/framework/tests/Unit/HydeUrlPathHelpersTest.php

Having a function that can return both a string and a psuedo-boolean (false) can lead to unpredictable states. This PR deprecates the `Hyde::uriPath()` helper and adds two new ones instead, `Hyde::qualifiedUrl()` and `Hyde::hasSiteUrl()`, effectively splitting the former into the latter.

Add new URL path helpers

---

RELEASE_NOTES.md
packages/framework/resources/views/layouts/head.blade.php
packages/framework/src/Concerns/HasPageMetadata.php
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Contracts/PageContract.php
packages/framework/tests/Feature/AbstractPageTest.php

This provides a canonical place to assemble the displayed page title, while also making it easier to customize from the backend in the future.

Construct the HTML page title inside the AbstractPage class

---

RELEASE_NOTES.md
packages/framework/src/Actions/SourceFileParser.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/tests/Unit/DocumentationPageTest.php

This property was added to allow automatic categorization based on subdirectory structures, but while keeping the file output in the root output directory (by keeping the slug as a basename). I think it's better to keep a consistent format between models, and thus include the subdirectory in the slug, and instead extract the basename when getting the currentpage property and output path.

Remove DocumentationPage localPath property

---

RELEASE_NOTES.md
packages/framework/src/Actions/SourceFileParser.php
packages/framework/src/Models/MarkdownDocument.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/src/Modules/Markdown/MarkdownFileParser.php
packages/framework/tests/Feature/MarkdownFileParserTest.php
packages/framework/tests/Feature/SourceFileParserTest.php
packages/framework/tests/Unit/DocumentationPageTest.php

Aims to refactor how pages are parsed, reducing boilerplate, and taking the opportunity to refactor related services.
In addition, this will reduce a lot of complexity. The first step I'm making is merging all page parsers in a single class https://github.com/hydephp/develop/pull/322, then this PR will refactor to simplify them further and reduce boilerplate.

Simplify page parsers

---

RELEASE_NOTES.md
packages/framework/resources/views/components/article-excerpt.blade.php
packages/framework/resources/views/components/post/article.blade.php
packages/framework/src/Actions/GeneratesDocumentationSearchIndexFile.php
packages/framework/src/Actions/SourceFileParser.php
packages/framework/src/Concerns/CanBeInNavigation.php
packages/framework/src/Concerns/HasPageMetadata.php
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Models/DocumentationSidebar.php
packages/framework/src/Models/Pages/BladePage.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/src/Services/SitemapService.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Feature/Concerns/CanBeInNavigationTest.php
packages/framework/tests/Feature/Concerns/HasArticleMetadataTest.php
packages/framework/tests/Feature/Concerns/HasPageMetadataTest.php
packages/framework/tests/Feature/MarkdownPageTest.php
packages/framework/tests/Feature/RouteTest.php
packages/framework/tests/Feature/SourceFileParserTest.php
packages/framework/tests/Unit/DocumentationPageTest.php
packages/framework/tests/Unit/GetLatestMarkdownPostsTest.php
packages/framework/tests/Unit/HasPageMetadataRssFeedLinkTest.php
packages/framework/tests/Unit/MarkdownPostParserTest.php

This update contains **breaking changes** to the internal API regarding page models. This should only affect you directly if you've written any code that interacts with the internal page models, such as constructing them using non-built-in Hyde helpers.
Previously internally called `slug(s)`, are now called `identifier(s)`. In all honestly, this has 90% to do with the fact that I hate the word "slug".
I considered using `basename` as an alternative, but that does not fit with nested pages. Here instead is the definition of an `identifier` in the context of HydePHP:
> An identifier is a string that is in essence everything in the filepath between the source directory and the file extension.
So, for example, a page source file stored as `_pages/foo/bar.md` would have the identifier …

Breaking: Begin internal rename of slugs to identifiers

---

RELEASE_NOTES.md
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Feature/StaticPageBuilderTest.php
packages/framework/tests/Unit/HasPageMetadataRssFeedLinkTest.php

```php
public function __construct(array $matter = [], string $body = '', ?string $title = null, string $identifier = '', ?MarkdownDocument $markdownDocument = null)
```
```php
public function __construct(string $identifier = '', array $matter = [], string $body = '', ?string $title = null, ?MarkdownDocument $markdownDocument = null)
```

Breaking: Reorder AbstractMarkdownPage constructor argument positions, putting the identifier first

---

RELEASE_NOTES.md
packages/framework/src/Actions/SourceFileParser.php

Makes some helpers in SourceFileParser public static allowing them to be used outside the class
The following are changed
- findTitleForPage
- findTitleFromMarkdownHeadings
- getDocumentationPageCategory
The actual usage of them is not affected.

Make file parser helpers public

---

RELEASE_NOTES.md
packages/framework/src/Facades/Markdown.php
packages/framework/tests/Unit/MarkdownFacadeTest.php

Deprecates Facades\Markdown::parse(), and adds a new Markdown::render() method instead.
The reason for this is that parsing in Hyde commonly is used to take a source file and parse it into an object. Since this method does the reverse (taking a Markdown string and compiling it to HTML), having it named render would make more sense, and also match the view render method.

Replace Markdown::parse() with Markdown::render()

---

RELEASE_NOTES.md
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Contracts/MarkdownDocumentContract.php
packages/framework/src/Models/MarkdownDocument.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Unit/MarkdownDocumentTest.php

Removes the body() method from Markdown pages, you can use markdown()->body() or cast the markdown property to string.

Remove body() method from Markdown pages

---

RELEASE_NOTES.md
packages/framework/src/Actions/GeneratesDocumentationSearchIndexFile.php
packages/framework/src/Concerns/HasTableOfContents.php
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Contracts/MarkdownPageContract.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/src/Modules/Markdown/MarkdownFileParser.php
packages/framework/tests/Feature/MarkdownPageTest.php
packages/framework/tests/Feature/Services/HydeSmartDocsTest.php
packages/framework/tests/Feature/SourceFileParserTest.php
packages/framework/tests/Unit/HasTableOfContentsTest.php
packages/framework/tests/Unit/MarkdownPostParserTest.php

Since the Markdown body is now strongly typed as a Markdown object, we have duplicate properties for the Markdown body (which is also stored in the Markdown object). This PR removes that.
```
^ Hyde\Framework\Models\Pages\MarkdownPage^ {#3014
+markdown: Hyde\Framework\Models\Markdown^ {#3009
+body: "foo bar"
}
+body: "foo bar"
}
```
```
^ Hyde\Framework\Models\Pages\MarkdownPage^ {#3006
+markdown: Hyde\Framework\Models\Markdown^ {#3014
+body: "foo bar"
}
}
```

Remove `body` property from Markdown 

---

packages/framework/src/Models/FrontMatter.php
packages/framework/src/Models/Markdown.php
packages/framework/src/Models/MarkdownDocument.php
packages/framework/src/Models/NavItem.php
packages/framework/src/Models/Route.php

As per the manual:
> As of PHP 8.0.0, any class that contains a [__toString()](https://www.php.net/manual/en/language.oop5.magic.php#object.tostring) method will also implicitly implement the [Stringable](https://www.php.net/manual/en/class.stringable.php) interface, and will thus pass type checks for that interface. Explicitly implementing the interface anyway is recommended. https://www.php.net/manual/en/language.oop5.magic.php

Implement Stringable interface in classes using toString magic method

---

docs/architecture-concepts.md
packages/framework/src/Actions/BladeMatterParser.php
packages/framework/src/Actions/PageModelConstructor.php
packages/framework/src/Actions/SourceFileParser.php
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Contracts/MarkdownPageContract.php
packages/framework/src/Contracts/PageContract.php
packages/framework/src/Models/Pages/BladePage.php
packages/framework/tests/Feature/BladeMatterParserTest.php
packages/framework/tests/Feature/SourceFileParserTest.php

Part one of this will be adding all the common methods currently in the Markdown pages. Then, write a parser to statically parse Blade files for properties. 
I have the following syntax suggestion, as it's actually already used in templates (and I don't want to add actual YAML blocks to Blade files)
```blade
@php($title = 'Latest Posts')
```
Which is equivalent to the following Markdown front matter
```markdown
---
title: Latest Posts
---
```
I think this could easily be parsed similar to how we do shortcodes, by scanning lines for patterns.
The algorithm could be roughly as follows (using `@php($foo = 'bar')` as the example)
1. Get blade file contents as text
2. Split each line into array
3. If line string starts with substring `@php($`
4. Call helper method with that line as a parameter …

Add front matter support to Blade pages

---

docs/architecture-concepts.md
packages/framework/src/Actions/BladeMatterParser.php
packages/framework/tests/Feature/BladeMatterParserTest.php

Parses string literals to arrays, for the BladeMatter parser. See https://github.com/hydephp/develop/pull/346#issuecomment-1206286625

Create static array parser

---

packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Models/Pages/MarkdownPost.php

This was cause to a weird issue where some data was not present in some places. This is of course because the data had not been constructed yet. As long as each child that has a schema adds it to the new construct method (and calls the parent) this issue should be fixed.

Create method to construct schemas to control the call order

---

packages/framework/tests/Feature/RelativeLinksAcrossPagesRetainsIntegrityTest.php

See https://github.com/hydephp/develop/issues/371
> We must make sure this does not break relative links. We may need to force a recompute of relative links each time the current page property is set.
> 
> Originally posted by @caendesilva in https://github.com/hydephp/develop/pull/367#issuecomment-1207925899

Add test to ensure pre-computed relative links are retained when rendering new pages

---

RELEASE_NOTES.md
packages/framework/src/Actions/FindsContentLengthForImageObject.php
packages/framework/src/Models/Image.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/tests/Feature/Commands/StaticSiteBuilderPostModuleTest.php
packages/framework/tests/Feature/FindsContentLengthForImageObjectTest.php
packages/framework/tests/Feature/ImageModelTest.php
packages/framework/tests/Unit/ArticleMetadataTest.php

The docs explain that images using the Image object should be in the _media directory when they are referenced by a local path, but we are not consistently doing this. This PR fixes that.
Will fix the following:

Consistently use image paths relative to _media directory as described in the documentation

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/grouped-sidebar.blade.php
packages/framework/src/Concerns/FrontMatter/Schemas/DocumentationPageSchema.php
packages/framework/src/Models/DocumentationSidebar.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

This is more predictable than assigning "other" at runtime. The logic determining if the categorized layout should be used has been updated, so this PR should have no effect on the actual rendered pages and their behaviour.

Add a default category property value for documentation pages

---

RELEASE_NOTES.md
packages/framework/src/Actions/Constructors/FindsNavigationDataForPage.php
packages/framework/tests/Unit/Views/NavigationMenuViewTest.php

This is caused in FindsNavigationDataForPage.php where the front matter is only read for Markdown pages.
> ```php
> if ($this->page instanceof AbstractMarkdownPage) {
>     if ($this->page->matter('navigation.title') !== null) {
>         return $this->page->matter('navigation.title');
>     }
> 
>     if ($this->page->matter('title') !== null) {
>         return $this->page->matter('title');
>     }
> }
> ```

Fix #383: Navigation menu titles can't be set in BladeMatter

---

packages/framework/src/Concerns/FrontMatter/Schemas/DocumentationPageSchema.php
packages/framework/src/Models/DocumentationSidebar.php

Previously, when a documentation page did not have a label front matter, it defaulted to a title generated from the slug/identifier. This was intentional, as the page titles may be too long to comfortably fit in the sidebar. This PR reverts this behaviour which was inadvertently changed in v0.58.0-beta. It also fixes a bug where the sidebar label was actually not used in the resulting view.

Change documentation page label fallback to previous behaviour

---

tests/fixtures/_posts/typography-front-matter.md

Constantly getting false positives in visual regression testing due to the images often not loading. This changes the fixtures to load from the HydePHP website. If that goes down, we have bigger problems than a broken image.

Change browser test image fixture to more reliable host

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Hyperlinks.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/Image.php
packages/framework/tests/Feature/Foundation/HyperlinksTest.php

If true is passed as the second argument, and a base URL is set, the image will be returned with a qualified Absolute URI.

Add option to Hyde::image() helper to prefer full URI paths

---

RELEASE_NOTES.md
packages/framework/src/Concerns/JsonSerializesArrayable.php
packages/framework/src/Helpers/Features.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/FrontMatter.php
packages/framework/src/Models/Route.php
packages/framework/tests/Feature/RouteCollectionTest.php

Implements interfaces to convert models into arrays and JSON.
Be mindful that this can cause issues (as seen in the failing tests) when serializing a parent object. For example, calling toArray() on a Laravel collection containing one of the affected models will bubble and use the array representation of the model, which may not be what you always want.

Improve model serializations

---

RELEASE_NOTES.md
app/bootstrap.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/HydeServiceProvider.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/testing/src/CreatesApplication.php

This PR restructures how the HydeKernel singleton (and by proxy, facade) internally are stored.
This makes the framework more modular and allows it to be operated more independently from the service container.
It partially reverts to the original behaviour, while retaining compatibility with the current service container behaviour. The PR does as follows:
- The HydeKernel singleton is now stored as a static property of the kernel class
- The service container now points to the aforementioned singleton instance when calling the contract
- The Hyde facade now calls members on the new singleton instead of the service container making it work outside the container
- The kernel instance can be set using the new setInstance method
- The boot and bootKernel methods have been merged
In most …

Bring out the HydeKernel singleton from the service container

---

RELEASE_NOTES.md
packages/framework/src/Actions/FindsContentLengthForImageObject.php
packages/framework/src/Models/Image.php
packages/framework/tests/Feature/FindsContentLengthForImageObjectTest.php
packages/framework/tests/Feature/ImageModelTest.php

If you try to get the source path of an image, it's probably because you want the source path of the image. Having it return null can lead to unexpected issues and broken image links. Instead, an exception should be thrown to let the user know about the problem so it can be fixed before deploying the site.

Throw exception instead of returning null when attempting to get source for Image without source

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/src/Actions/Constructors/FindsNavigationDataForPage.php
packages/framework/tests/Feature/AbstractPageTest.php

Prior to this release, the navigation menu priorities were based on the page slug. This has been changed to the route key. A route key in Hyde is in short the compiled page's path, relative to the site's root. For example, `_site/foo/bar.html` has the route key `foo/bar`.
This change is breaking as it requires the configuration to be updated. However, this is really easy. Just change `docs` to `docs/index` in the `config/hyde.php` file.
```diff
'navigation' => [
'order' => [
'index' => 0,
'posts' => 10,
-		'docs' => 100,
+		'docs/index' => 100,
],
],
```

Reduce complexity by using route keys to get navigation menu priorities from config

---

RELEASE_NOTES.md
packages/framework/src/Actions/GeneratesDocumentationSearchIndexFile.php
packages/framework/tests/Feature/Actions/GeneratesDocumentationSearchIndexFileTest.php

Fixes https://github.com/hydephp/develop/issues/410

Fix #410: Search index generator breaks when storing documentation page source files in subdirectories

---

RELEASE_NOTES.md
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Contracts/PageContract.php
packages/framework/src/Contracts/RouteFacadeContract.php
packages/framework/src/Foundation/PageCollection.php
packages/framework/src/Foundation/RouteCollection.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/src/Models/Route.php
packages/framework/src/RouteCollection.php
packages/framework/src/Services/BuildService.php
packages/framework/tests/Feature/PageCollectionTest.php
packages/framework/tests/Feature/RouteCollectionTest.php

To upgrade the moved collection namespaces, simply replace the following namespace imports:
```diff
-use Hyde\Framework\PageCollection;
+use Hyde\Framework\Foundation\PageCollection;
-use Hyde\Framework\RouteCollection;
+use Hyde\Framework\Foundation\RouteCollection;
```

Move core collections into foundation namespace

---

RELEASE_NOTES.md
packages/framework/src/Foundation/BaseSystemCollection.php
packages/framework/src/Foundation/FileCollection.php
packages/framework/src/Foundation/PageCollection.php
packages/framework/src/Foundation/RouteCollection.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/File.php
packages/framework/src/Services/DiscoveryService.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Feature/FileCollectionTest.php
packages/framework/tests/Feature/FileTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/PageCollectionTest.php
packages/framework/tests/Feature/RouteCollectionTest.php
packages/testing/src/ResetsApplication.php

Creates a new foundation class, the FileCollection. Which like the other foundation collections, discovers all the files. Running this part of the autodiscovery will further enrich the Hyde Kernel, and allow greater insight into the application. The end user experience should not be affected by this.
It also adds a new model, `File`, as an object-oriented way of representing a project file on the disk.
Note that having the filesystem pre-discovered means that changing the discovery rules at runtime after the framework has booted, means that you need to reboot the framework. I think this would ever really happen during testing when changing a directory mid-test. If it happens in actual code you are probably doing something wrong (registering in boot method instead of register method for …

Discover filesystem upon booting the framework

---

RELEASE_NOTES.md
app/bootstrap.php
packages/framework/src/Contracts/AssetServiceContract.php
packages/framework/src/Contracts/HydeKernelContract.php
packages/framework/src/Facades/Asset.php
packages/framework/src/Foundation/BaseSystemCollection.php
packages/framework/src/Foundation/Filesystem.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/HydeServiceProvider.php
packages/framework/src/helpers.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Unit/AssetFacadeTest.php
packages/framework/tests/Unit/HydeServiceProviderTest.php

These were originally added because I wrongly assumed the Laravel service container only accepted interfaces when type hinting. These classes aren't intended to be extended in the same ways other contracts are. Thus, having interfaces for these adds undue complexity.
The following interfaces are affected:
- HydeKernelContract, type hint the HydeKernel::class instead
- AssetServiceContract, type hint the AssetService::class instead

Deprecate unnecessary contracts

---

packages/framework/src/Foundation/Concerns/ForwardsFilesystem.php
packages/framework/src/Foundation/Concerns/ForwardsHyperlinks.php
packages/framework/src/Foundation/Concerns/ImplementsStringHelpers.php
packages/framework/src/HydeKernel.php

While I'm generally a bit weary of single-use traits (I love them, but feel that they can be a sign that the code needs to be split up into more classes), the HydeKernel is a vital part of the framework and cannot really be split up the same way as other classes can.
This PR moves logic to scoped internal traits in the Foundation\Concerns namespace. This will make it easier to get an overview of what's going on in each domain. This does not affect any of the logic itself or end usage of the framework, just how it is internally structured.

Refactor HydeKernel code to organized single-used traits

---

RELEASE_NOTES.md
packages/framework/src/Commands/HydeBuildStaticSiteCommand.php
packages/framework/src/Helpers/Features.php
packages/framework/tests/Feature/Commands/HydeBuildRssFeedCommandTest.php
packages/framework/tests/Feature/MetadataTest.php
packages/framework/tests/Feature/MetadataViewTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php
packages/framework/tests/Unit/Views/NavigationMenuViewTest.php

Fixes https://github.com/hydephp/develop/issues/443
- The RSS feed related generators are now only enabled when there are blog posts
- The documentation search related generators are now only enabled when there are documentation pages
This may seem like a big change, but in actuality, these files were not generated when running the standard build command unless the pages existed, so it makes no sense to have links to them in the site.
Comment related to the issue:
> Okay, so this was discovered when running `php hyde build` on a new project without any posts. An RSS feed is not generated then as the build command has an extra check to see if there are any posts. Same with documentation. This is of course inconsistent with how we handle it in other places. So something needs to be changed. …

Only enable support files when there are related pages

---

RELEASE_NOTES.md
config/site.php
docs/digging-deeper/customization.md
packages/framework/config/site.php
packages/framework/src/HydeServiceProvider.php
packages/framework/src/Services/YamlConfigurationService.php
packages/framework/tests/Feature/YamlConfigurationServiceTest.php
packages/framework/tests/Unit/HydeServiceProviderTest.php

This file will work as a superset of the site config file, and allow some basic site configuration to be managed with YAML. The YAML options are then be merged taking priority over other settings at runtime using a service provider. This allows for easier static analysis of the configuration file, as well as better interoperability.

Add a YAML configuration file

---

RELEASE_NOTES.md
packages/framework/src/Actions/PostBuildTasks/GenerateRssFeed.php
packages/framework/src/Actions/PostBuildTasks/GenerateSearch.php
packages/framework/src/Actions/PostBuildTasks/GenerateSitemap.php
packages/framework/src/Commands/HydeBuildRssFeedCommand.php
packages/framework/src/Commands/HydeBuildSearchCommand.php
packages/framework/src/Commands/HydeBuildSitemapCommand.php
packages/framework/src/Commands/HydeBuildStaticSiteCommand.php
packages/framework/src/Concerns/ActionCommand.php
packages/framework/src/Contracts/AbstractBuildTask.php
packages/framework/src/Contracts/BuildTaskContract.php
packages/framework/tests/Feature/Commands/HydeBuildRssFeedCommandTest.php
packages/framework/tests/Feature/Commands/HydeBuildSearchCommandTest.php
packages/framework/tests/Feature/Commands/HydeBuildSitemapCommandTest.php
packages/framework/tests/Feature/Services/BuildHookServiceTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php

This update refactors the build services for the generation of sitemaps, RSS feeds, and documentation search index. These are now handled by post-build tasks, and are simplified.
Much of the return information has been removed as well as preflight checks. We may want to add some exceptions in the related services as the following messages (among others) have been removed
- Cannot generate sitemap.xml, please check your configuration.
- You don't have a site URL configured. Check config/hyde.php
- You have disabled sitemap generation in config/hyde.php
- You can enable sitemap generation by setting `site.generate_sitemap` to `true`
- Cannot generate sitemap.xml, please check your configuration.
- You don't have the `simplexml` extension installed. Check your PHP installation.
I also had to …

Refactor auxiliary build services and tasks

---

packages/framework/resources/views/components/navigation/dropdown.blade.php
packages/framework/resources/views/layouts/navigation.blade.php
packages/framework/src/Contracts/AbstractPage.php

Adds a simple component for navigation menu dropdowns. While it's not automatically generated in the code as of yet, it gives a quick way to add a dropdown to published views. 
> I actually can't think of a good way to implement automatic dropdowns in a way that works well without a bunch of complexity. The best I can see now is to add a Blade component that can be used in published views, and we'll take it from there. https://github.com/hydephp/develop/issues/76#issuecomment-1234222716
Here is an example usage:
```blade
@php
$navigation = \Hyde\Framework\Models\NavigationMenu::create();
@endphp
<x-hyde::navigation.dropdown label="About us">
@foreach ($navigation->items as $item)
<li>
@include('hyde::components.navigation.navigation-link')
</li>
@endforeach
</x-hyde::navigation.dropdown> …
```

Add navigation menu dropdown component

---

packages/framework/src/Actions/PostBuildTasks/GenerateBuildManifest.php
packages/framework/src/Commands/HydeBuildStaticSiteCommand.php
packages/framework/src/Services/BuildTaskService.php

Adds a silent (as it takes less than 1ms) post-build task to generate a simple JSON manifest of the MD5 hashes of the source file and the compiled HTML file. This can then be used to see if a page needs to be recompiled. MD5 was chosen for its speed and size and I think it's fine for this use since it's not used for anything cryptographic. 
This can be used to determine if a compiled page is up to date with the source file by comparing if the input and output hashes match.
The feature can be disabled in the configuration, as can output path. The defaults are seen below. They are not in the default config file, instead these are simply the fallback values internally.
```php
// config/hyde.php
'generate_build_manifest' => true,
'build_manifest_path' => …
```

Generate a build manifest after the build

---

RELEASE_NOTES.md
packages/framework/src/Commands/HydeRebuildStaticSiteCommand.php

The validation check was testing posts twice but not Markdown pages

Fix validation bug in rebuild command

---

.idea/misc.xml
RELEASE_NOTES.md
packages/framework/src/Actions/PostBuildTasks/GenerateBuildManifest.php
packages/framework/src/Actions/PostBuildTasks/GenerateRssFeed.php
packages/framework/src/Actions/PostBuildTasks/GenerateSitemap.php
packages/framework/src/Actions/StaticPageBuilder.php
packages/framework/src/Commands/HydeBuildSiteCommand.php
packages/framework/src/Foundation/Concerns/ForwardsFilesystem.php
packages/framework/src/Foundation/Filesystem.php
packages/framework/src/Hyde.php
packages/framework/src/Services/BuildService.php
packages/framework/src/Services/DocumentationSearchService.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php
packages/framework/tests/Feature/HydeKernelTest.php

Makes the method less verbose, and in my option makes it cleared that it's an absolute path like Hyde::path and Hyde::vendorPath

Rename Hyde method getSiteOutputPath to sitePath

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/grouped-sidebar-navigation.blade.php
tests/Browser/HighLevelViewTest.php

These classes are internally only used for Dusk testing, but adds a semantic CSS hook that should be renamed according to https://github.com/hydephp/develop/pull/498
- Changed Blade component identifier class 'sidebar-category' to 'sidebar-group'
- Changed Blade component identifier class 'sidebar-category-heading' to 'sidebar-group-heading'
- Changed Blade component identifier class 'sidebar-category-list' to 'sidebar-group-list'

Change CSS identifier class 'sidebar-category' to 'sidebar-group'

---

.idea/misc.xml
RELEASE_NOTES.md
packages/framework/resources/views/components/article-excerpt.blade.php
packages/framework/src/Concerns/HydePage.php
packages/framework/src/Foundation/Concerns/ForwardsHyperlinks.php
packages/framework/src/Foundation/Hyperlinks.php
packages/framework/src/Hyde.php
packages/framework/src/Models/Route.php
packages/framework/src/Services/BuildService.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Unit/Foundation/HyperlinkFormatHtmlPathTest.php
projects/shelf/single-file-dashboard/dashboard.php
projects/templates/dashboard.blade.php

Before v1 I want to make sure we are using consistent naming. To aid in this, I'm drafting a schema spec/glossary relating to paths here.
- Renaming methods and variables using the term `URI` with `URL`
--- 
An absolute path is a path that starts from the root of the filesystem. For example, `/home/user/my-hyde-project/_pages/example.md` is an absolute path. These should only be used as the last step of a filesystem operation, for example just before writing, reading, or creating a file.
Hyde prefers relative paths. These are paths that are relative to the project root (or a subdirectory therein). For example, `_pages/example.md` is a relative path. These should be used as much as possible, as they are more portable and easier to work with.
Now that the path types are defined, let's set …

Breaking unification of URL-related methods and variables

---

packages/framework/src/Models/Image.php

Since the check never returns a falsely value, but instead throws an exception, this condition can never be reached.

Remove unreachable conditional result

---

packages/framework/resources/views/pages/documentation-search.blade.php
packages/framework/src/Actions/StaticPageBuilder.php
packages/framework/src/Foundation/Concerns/ManagesViewData.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php

Moves responsibility for sharing the current page data to the view from the static page builder to the Hyde kernel

Refactor shared view data handling

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Hyperlinks.php
packages/framework/src/Hyde.php
packages/framework/tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php

This parameter is only used in a single test, and never in actual code

Remove unused $default parameter to Hyde::url method

---

RELEASE_NOTES.md
packages/realtime-compiler/src/Concerns/InteractsWithLaravel.php
packages/realtime-compiler/src/Routing/Router.php

Removed support for the legacy bootstrapping file removed in Hyde v0.40

Remove RealtimeCompiler support for the legacy bootstrap file

---

RELEASE_NOTES.md
docs/getting-started/console-commands.md
packages/framework/src/Commands/HydeRouteListCommand.php
packages/framework/src/HydeServiceProvider.php
packages/framework/tests/Feature/Commands/HydeRouteListCommandTest.php

Adds a `route:list` command
```
$ php hyde route:list
+-----------+------------------------+------------------+-----------+
| Page Type | Source File            | Output File      | Route Key |
+-----------+------------------------+------------------+-----------+
| BladePage | _pages/404.blade.php   | _site/404.html   | 404       |
| BladePage | _pages/index.blade.php | _site/index.html | index     |
+-----------+------------------------+------------------+-----------+
```

Add a route:list command

---

RELEASE_NOTES.md
packages/framework/src/Models/Pages/BladePage.php

Makes the BladePage $view argument optional to match the base HydePage class. This was originally made required as Blade pages need a concrete view to compile, so pages still won't be able to be compiled without a view, so this PR will just defer that error if a developer tries that.

Make BladePage $view argument optional

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Foundation/FileCollection.php
packages/framework/src/Foundation/PageCollection.php
packages/framework/src/Helpers/Features.php
packages/framework/tests/Unit/HydeHelperFacadeTest.php

This means you must update your hyde.php config, otherwise blog posts might not be generated.

Breaking: Rename Features::blogPosts to Features::markdownPost to match the page type name 

---

RELEASE_NOTES.md
packages/framework/resources/views/layouts/scripts.blade.php
packages/framework/resources/views/layouts/styles.blade.php
packages/framework/src/Helpers/Asset.php
packages/framework/src/Services/AssetService.php
packages/framework/tests/Feature/AssetServiceTest.php
packages/framework/tests/Feature/MetadataViewTest.php
packages/framework/tests/Unit/RelativeLinksAcrossPagesRetainsIntegrityTest.php
packages/framework/tests/Unit/Views/ScriptsComponentViewTest.php
packages/framework/tests/Unit/Views/StylesComponentViewTest.php

Adds a new `Asset::mediaLink()`helper method which (besides adding visual consistency in Blade views) automatically appends `?v= + md5()` of the file, allowing for easy cache busting. This can be disabled by setting `hyde.cache_busting` to false.

Add cache busting

---

packages/framework/src/Actions/PostBuildTasks/GenerateBuildManifest.php
packages/framework/tests/Unit/GenerateBuildManifestTest.php

Adds the date the manifest was compiled, and removes the page property, replacing it with the source and output paths. Previously, the page property contained the source path. To differentiate the date from the pages, the pages are now in under the `pages` array key.
```json
[
{
"page": "_pages/404.blade.php",
"source_hash": "9a4e236420cd01cbb726240199d0de82",
"output_hash": "c4ef14f1fa794d3d105b6d039b28ba06"
},
{
"page": "_pages/index.blade.php",
"source_hash": "72469ce3453f5b396402e5207493921b",
"output_hash": "72469ce3453f5b396402e5207493921b"
}
]
```
```json
{
"generated": "2022-10-01T13:40:09.602307Z",
"pages": [
{
"source_path": "_pages/404.blade.php",
"output_path": "404.html",
"source_hash": "27a3012eacef5d0672e59ddcd9866985",
"output_hash": "e8f804948dc9890a5659b53910f783ca"
},
{ …
```

Rewrite the build manifest schema

---

packages/framework/tests/Feature/NavigationDataTest.php

This PR moves `NavigationDataTest` from `Model` directory to `Feature` and updates its namespace respectively. Closes #557

Fix: move NavigationDataTest from 'Model' to 'Feature'

---

packages/framework/src/Models/Support/File.php
packages/framework/tests/Feature/FileTest.php

This PR adds `getExtension(): string` method to the [File.php](https://github.com/hydephp/develop/blob/master/packages/framework/src/Models/Support/File.php) class that by using `pathinfo()` method under the hood returns extension of a file as a result.
To confirm that everything works as expected I've attached a simple test in `FileTest.php` file that check few potential use cases.
This should close issue #556

Add 'getExtension' method to the File class

---

packages/hyde/composer.json
packages/realtime-compiler/README.md
packages/realtime-compiler/composer.json

Fixes #515:
> Needs a minor version bump as well as updating the minimum framework version as the package uses the HydePage class from the upcoming framework release.

Update the RealtimeCompiler package

---

.github/workflows/continuous-integration.yml
.github/workflows/test-pull-requests.yml
RELEASE_NOTES.md
SECURITY.md
composer.json
composer.lock
packages/framework/composer.json
packages/hyde/composer.json

<div type='discussions-op-text'>
<sup>Originally posted by **caendesilva** October 24, 2022</sup>
As PHP 8.1 is starting to become more widespread, and Hyde's dependencies are increasingly adopt it, it's only a matter of time before we need to drop support for PHP 8.0. The very latest we can do this is in February next year when Laravel 10 (or as I like to call it, Laravel X) is released, which drops support for PHP 8.0. As will we have to.
Since changing the minimum PHP version will be a breaking change, and Hyde 1.0 is due to be released relatively soon, we may have to think about dropping support for 8.0.
I'd love to get some community feedback on this. What PHP versions are you using, and do you think it makes sense for HydePHP to keep on supporting 8.0? </div>

Breaking: Set minimum PHP version to 8.1

---

packages/framework/src/HydeKernel.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/MetadataViewTest.php

If you want to get the "real" installed version, you can still use the following (which was the old behaviour)
```php
Composer\InstalledVersions::getPrettyVersion('hyde/framework')
```

Change version method to return the new version constant instead of using Composer

---

packages/framework/src/Console/HydeConsoleServiceProvider.php
packages/framework/src/Framework/HydeServiceProvider.php

The HydeServiceProvider class is really long, hoping to start to refactor it to extract its responsibilities to the new domains added by the experimental refactor branch.

Handle console commands in new HydeConsoleServiceProvider

---

packages/framework/src/Framework/Features/Session/Session.php
packages/framework/src/Framework/Features/Session/SessionServiceProvider.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/src/Support/Models/File.php
packages/framework/tests/Framework/Feature/SessionTest.php

Adds a simple session handler, arguably most useful to defer messages, for example, to asynchronously add warnings to be used at a later point in the request lifecycle.
It's bound into the service container as a singleton and is not persisted.

Add a simple session handler

---

packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/tests/Feature/FeaturedImageModelTest.php
packages/framework/tests/Feature/MarkdownPostTest.php

Leads to a more explicit, consistant, and predictable behaviour. It also makes usage more forgiving as front matter can use both _media/ or just the filename as it will be normalized.

Normalize internal image path storage

---

packages/framework/resources/views/components/post/image.blade.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/LocalFeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/RemoteFeaturedImage.php
packages/framework/tests/Feature/FeaturedImageModelTest.php
packages/framework/tests/Feature/FeaturedImageTest.php

The featured image class is one of rather high complexity, most of which is due to the fact that it supports two wildly different storage adapters. This PR keeps the shared logic in a base class, and the differential logic in child classes.
It also very strictly enforces the internal data structure, and has explicit constructors with data validation, paired with a scoped public API. This makes the whole system more maintainable and predictable.
As the constructors now require all parameters to be set, the classes will require a factory, however since the data logic is now easily decouplable this is not a problem; in fact it may even prove more useful as it will be easier to support multiple front matter keys, allowing for much better interoperability.

Simplify featured images by splitting into new classes

---

packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/RemoteFeaturedImage.php
packages/framework/tests/Feature/FeaturedImageFactoryTest.php
packages/framework/tests/Feature/FeaturedImageTest.php

See https://github.com/hydephp/develop/pull/619

Add featured image factory

---

.idea/inspectionProfiles/Project_Default.xml
packages/framework/resources/views/components/article-excerpt.blade.php
packages/framework/resources/views/components/docs/documentation-article.blade.php
packages/framework/resources/views/components/post/article.blade.php
packages/framework/resources/views/components/post/author.blade.php
packages/framework/resources/views/components/post/image.blade.php
packages/framework/tests/Feature/StaticSiteBuilderPostModuleTest.php
packages/framework/tests/Unit/Views/ArticleExcerptViewTest.php
packages/framework/tests/Unit/Views/FeaturedImageViewTest.php

Changes itemtypes to use the https version of schema identifiers. See https://schema.org/docs/faq.html#19
> Q: Should we write 'https://schema.org' or 'http://schema.org' in our markup?
> 
> There is a general trend towards using 'https' more widely, and you can already write 'https://schema.org' in your structured data. We have migrated the schema.org site itself towards using https: as the default version of the site and our preferred form in examples. However 'http://schema.org' -based URLs in structured data markup will remain widely understood for the foreseeable future and there should be no urgency about migrating existing data. This is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine.

Change schema.org identifiers to use https

---

packages/realtime-compiler/src/Routing/PageRouter.php

Uses the getOrFail method to throw a 404 when the route is not found in the realtime compiler.

HydeRC: Use getOrFail instead of get

---

packages/framework/src/Console/Commands/MakePostCommand.php
packages/framework/src/Framework/Actions/CreatesNewMarkdownPostFile.php
packages/framework/tests/Feature/Commands/MakePostCommandTest.php

Refactors the internals of the `MakePostCommand` and `CreatesNewMarkdownPostFile` and changes the default generated author name from "Mr. Hyde" to "default".

Refactor the make:post command action

---

packages/framework/src/Console/Commands/MakePageCommand.php
packages/framework/src/Framework/Actions/CreatesNewPageSourceFile.php
packages/framework/tests/Feature/Actions/CreatesNewPageSourceFileTest.php
packages/framework/tests/Feature/Commands/MakePageCommandTest.php
packages/testing/src/TestCase.php

Refactors the internals of the MakePageCommand and CreatesNewPageSourceFile to use better OOP.

Refactor the make:page command action

---

packages/framework/src/Console/Commands/MakePostCommand.php

Extracts some helper methods to make the code easier to read.

Clean up the MakePostCommand class

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php

Makes so that the following yield the same result, where previously the latter would do nothing.
```markdown
---
navigation:
group: Example
---
```
```markdown
---
navigation:
category: Example
---
```
This saves you having to try to remember which front matter key works, as now both does!

Allow navigation group to be set with category key

---

packages/framework/src/Facades/Features.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateRssFeed.php
packages/framework/src/Framework/Features/Metadata/GlobalMetadataBag.php
packages/framework/src/Framework/Services/RssFeedService.php
packages/framework/src/Framework/Services/SitemapService.php
packages/framework/src/Support/Helpers/XML.php
packages/framework/tests/Feature/BuildOutputDirectoryCanBeChangedTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php

Refactors [RssFeedService.php](https://github.com/hydephp/develop/blob/master/packages/framework/src/Framework/Services/RssFeedService.php) and [SitemapService.php](https://github.com/hydephp/develop/blob/master/packages/framework/src/Framework/Services/SitemapService.php)
Contains one breaking API change:
- Renames RssFeedService method getDefaultOutputFilename to outputFilename, as the word default implies it can be changed, but we have no such logic.

Refactor XML services

---

packages/framework/src/Foundation/Concerns/ManagesViewData.php
packages/framework/src/Framework/Features/Metadata/GlobalMetadataBag.php
packages/framework/src/Framework/Features/Metadata/MetadataBag.php
packages/framework/src/Framework/Features/XmlGenerators/BaseXmlGenerator.php
packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php
packages/framework/src/Framework/Features/XmlGenerators/SitemapGenerator.php
packages/framework/tests/Unit/BuildOutputDirectoryCanBeChangedTest.php

These refactors should not have any affect on behaviour.

Code refactors

---

packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Unit/DocumentationPageTest.php

Major changes:
- Renames method formatSlugForModel to pathToIdentifier and improves it
- Adds support for customizing media file extensions with an array
- Adds more test cases

Refactor DiscoveryService.php

---

packages/framework/src/Framework/Services/BuildService.php

This refactor only affects the internal code API.

Clean up the build service class

---

packages/framework/src/Foundation/Concerns/ImplementsStringHelpers.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/HydeKernelTest.php

Adds a helper to the Hyde facade to quickly convert Markdown to HTML.

Add a Hyde::markdown() helper

---

packages/framework/src/Pages/Concerns/HydePage.php

Ensures no leading or trailing slashes are present within the output of the `HydePage::getSourcePath()` and `HydePage::getOutputPath()` methods.

Unslash page source and output paths

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Features/Publications/PublicationHelper.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php

I think I broke this command when refactoring. This fixes that and also adds tests for it.

Fix and refactor make:publicationType command and add tests for it

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationFieldTest.php
packages/framework/tests/Feature/PublicationTypeTest.php
tests/fixtures/test-publication-schema.json

Adds a `PublicationType` for a stronger type system.

Add publication fields class

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Console/Concerns/ValidatingCommand.php
packages/framework/src/Framework/Features/Publications/PublicationService.php
packages/framework/tests/Feature/ValidatingCommandTest.php

Moves method `PublicationService::askWithValidation()` to `ValidatingCommand::askWithValidation()`
This PR is not breaking as it targets a branch that has not yet been merged into the master branch so none of this code is in the public API yet.

Extract service helper to base command class

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Concerns/ValidatingCommand.php
packages/framework/src/Framework/Actions/Concerns/CreateAction.php
packages/framework/src/Framework/Actions/Contracts/CreateActionContract.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldType.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/CreateActionTest.php
packages/framework/tests/Feature/PublicationFieldTypeTest.php
packages/framework/tests/Feature/ValidatingCommandTest.php

Refactors for better usage of built-in helpers and reduces redundant code. Also improves test coverage.

Refactor publication commands and create actions

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/src/Framework/Features/Publications/PublicationService.php
packages/framework/tests/Feature/PublicationTypeTest.php
packages/framework/tests/Feature/Services/PublicationServiceTest.php

Refactors and simplifies the publication service class.

Refactor publication service and add tests for it

---

packages/framework/src/Foundation/Concerns/ForwardsFilesystem.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/HydeKernelTest.php

Fixes https://github.com/hydephp/develop/issues/698

Add Hyde facade helper to get the Filesystem instance

---

packages/framework/src/Facades/Features.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Framework/Factories/Concerns/CoreDataObject.php
packages/framework/src/Framework/Features/Navigation/NavigationData.php
packages/framework/src/Markdown/Models/FrontMatter.php
packages/framework/src/Support/Concerns/Serializable.php
packages/framework/src/Support/Contracts/SerializableContract.php
packages/framework/src/Support/Models/File.php
packages/framework/src/Support/Models/Route.php
packages/framework/tests/Unit/JsonSerializesArrayableTest.php
packages/framework/tests/Unit/SerializableContractTest.php
packages/framework/tests/Unit/SerializableTest.php

Now we have a lot of classes that implements JsonSerializable and Arrayable. For further compatability we could also add Jsonable. To make the code shorter and instantly clear this PR merges these interfaces into a `SerializableContract` and updates the former usages to use the new one. It also updates the trait used for automatically serializing arrayables.

Add a serializable contract

---

packages/framework/src/Markdown/Models/FrontMatter.php
packages/framework/tests/Unit/DocumentationPageTest.php
packages/framework/tests/Unit/FrontMatterModelTest.php

Fixes https://github.com/hydephp/develop/issues/708

Method FrontMatter::get() now returns the instance instead of data array when no key is specified

---

packages/framework/resources/views/components/article-excerpt.blade.php
packages/framework/src/Framework/Concerns/InteractsWithFrontMatter.php
packages/framework/src/Framework/Features/Metadata/PageMetadataBag.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Feature/SourceFileParserTest.php
packages/framework/tests/Unit/MarkdownPostParserTest.php

Part one of fixing https://github.com/hydephp/develop/issues/709
This is a breaking change as this trait is used by the HydePage class, and therefore affects all page models.

Breaking: Rename method 'get' to 'data' in InteractsWithFrontMatter

---

packages/framework/src/Framework/Actions/SourceFileParser.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php

Fixes https://github.com/hydephp/develop/issues/709 in conjunction with https://github.com/hydephp/develop/pull/712

Add static HydePage::get() method to get pages from the page collection

---

composer.lock
packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/MakePublicationTagCommand.php
packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Console/Concerns/ValidatingCommand.php
packages/framework/src/Console/HydeConsoleServiceProvider.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldType.php
packages/framework/src/Framework/Features/Publications/PublicationService.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationFieldTypeTest.php

Mainly it includes the new tag feature, but also some other minor improvements such as: 
1) Use trim() on input where appropriate
2) Changed min/max types to string, this makes sense because it could be a datetime or A-Z or something like that
3) Simplified the logic for MAX_RETRIES on the validation  checker for input, I think this version reads nicer than the original one (sidenote: this method doesn't really need to be recursive, it could also be done in a do...while loop)
4) Some other minor things
Please look for the string FIXME in the code, I used this to mark some things which I think you should review just to make sure. It should not be anything to fix, but just to review.
The new command is called makePublicationTag ... I called it "tag" because this is the most obvious use …

Committing code to 'tag' field type.

---

packages/framework/tests/Feature/StaticSiteServiceTest.php
packages/testing/src/TestCase.php
packages/testing/src/helpers.php

Adds a new testing helper to create temporary directories.
Here's an example of a test refactored to use this:
Before:
```php
{
$path = Hyde::path('_media/foo/img.png');
@mkdir(dirname($path), recursive: true);
file_put_contents($path, 'foo');
$this->artisan('build')->assertSuccessful();
$this->assertFileEquals(Hyde::path('_media/foo/img.png'), Hyde::path('_site/media/foo/img.png'));
unlink(Hyde::path('_media/foo/img.png'));
rmdir(Hyde::path('_media/foo'));
unlink(Hyde::path('_site/media/foo/img.png'));
rmdir(Hyde::path('_site/media/foo'));
}
```
After:
```php
{
$this->directory('_media/foo');
$this->cleanUpWhenDone('_site/media/foo');
file_put_contents(Hyde::path('_media/foo/img.png'), 'foo');
$this->artisan('build')->assertSuccessful(); …
```

Internal: Update testing helpers

---

packages/framework/src/Facades/Render.php
packages/framework/src/Foundation/Concerns/ManagesViewData.php
packages/framework/src/Support/Facades/Render.php
packages/framework/src/Support/Models/Render.php
packages/framework/tests/Feature/GlobalMetadataBagTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/RenderHelperTest.php
packages/framework/tests/Feature/RouteTest.php
packages/framework/tests/Unit/HydeFileHelpersTest.php
packages/framework/tests/Unit/Views/Components/LinkComponentTest.php
packages/framework/tests/Unit/Views/ScriptsComponentViewTest.php
packages/framework/tests/Unit/Views/StylesComponentViewTest.php
packages/testing/src/TestCase.php

Resolves the following todo in [ManagesViewData.php](https://github.com/hydephp/develop/blob/c11fa85ffe3e038da0fa3c3f8383752744c6924b/packages/framework/src/Foundation/Concerns/ManagesViewData.php#L14-L15):
> "Consider if this logic is better suited for a "Render" class solely for handling data related to the current render."
I think this change in addition to having a stricter schema for these very important core properties will also further separate concerns by bringing this out of the HydeKernel which is used to store information about the project, whereas this render data is for the specific page being compiled and should be reset after each page compile.
To migrate existing code, replace the following (and only these specific keys need to be replaced)
```php
use …
```

Create render helper to canonicalize the schema for data passed to renders

---

packages/framework/src/Framework/Actions/MarkdownFileParser.php
packages/framework/tests/Feature/MarkdownFileParserTest.php

Makes the following changes:
- Remove data unsetter for property that hasn't been used in a long while
- Trims the end of the parsed markdown body as it leads to a more consistent data state (you can always add it back if needed)

Refactor markdown file parsing

---

packages/framework/src/Framework/Actions/MarkdownFileParser.php
packages/framework/src/Markdown/Models/Markdown.php

This provides an even more consistent state than in https://github.com/hydephp/develop/pull/723

Move Markdown end-of-document normalizer from parser to constructor

---

packages/framework/src/Markdown/Models/Markdown.php
packages/framework/tests/Unit/MarkdownDocumentTest.php

Further provides a more consistent state across platforms, see https://github.com/hydephp/develop/pull/723 and https://github.com/hydephp/develop/pull/724.

Normalize CRLF sequences to LF in parsed Markdown objects

---

packages/framework/src/Framework/Actions/PublicationPageCompiler.php
packages/framework/src/Framework/Concerns/InvokableAction.php
packages/framework/src/Framework/Features/Publications/Models/PublicationListPage.php
packages/framework/src/Pages/PublicationPage.php
packages/framework/tests/Feature/Actions/PublicationPageCompilerTest.php
packages/framework/tests/Feature/HydeServiceProviderTest.php
packages/framework/tests/Feature/PublicationTypeTest.php

Since these page types have dynamic source files, their compiling logic is a bit more complex than other pages. This refactor PR moves these to a dedicated action, and adds an experimental base action that adds a static call method to provide syntactic sugar for invokable classes.
The short snippet shows the call method alternative. Both lines to the exact same thing.
```php
return (new PublicationPageCompiler($this))->__invoke();
return PublicationPageCompiler::call($this);
```

Extract action for publications compiling

---

packages/framework/src/Console/Commands/Helpers/InputStreamHandler.php
packages/framework/src/Console/Commands/MakePublicationTagCommand.php
packages/framework/src/Console/Concerns/ValidatingCommand.php
packages/framework/src/Framework/Features/Publications/PublicationService.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/tests/Feature/Commands/MakePublicationTagCommandTest.php
packages/framework/tests/Feature/ValidatingCommandTest.php

Refactor and add tests for MakePublicationTagCommand and adds an infoComment helper (for a lack of a better term)

Refactor and add tests for MakePublicationTagCommand

---

packages/framework/src/Framework/Concerns/InvokableAction.php
packages/framework/tests/Feature/InvokableActionTest.php

Adds an experimental base action that adds a static call method to provide syntactic sugar for invokable classes. This PR cherry picks this feature from the publications-feature branch, originally added by https://github.com/hydephp/develop/pull/726.
The short snippet shows the call method alternative. Both lines to the exact same thing.
```php
return (new ExampleAction($this))->__invoke();
return ExampleAction::call($this);
```

Add base class for invokable action classes

---

packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationPageTest.php
packages/framework/tests/Feature/PublicationTypeTest.php

Resolves the following:
> I think the default values used in the make pubtype command can be set as default values in the constructor as it is extremely verbose, making it bulky to test.
_Originally posted by @caendesilva in https://github.com/hydephp/develop/issues/685#issuecomment-1336199055_

Add default values to the publication type class

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Actions/CreatesNewPublicationType.php
packages/framework/src/Framework/Features/Publications/Models/PaginationSettings.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationPageTest.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationTypeTest.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationListPageTest.php
packages/framework/tests/Feature/PublicationPageTest.php
packages/framework/tests/Feature/PublicationTypeTest.php
packages/framework/tests/Unit/Pages/PublicationPageUnitTest.php
packages/framework/tests/Unit/PaginationSettingsTest.php
tests/fixtures/test-publication-schema.json

Changes the schema for pagination settings for publication types by putting the settings in a sub-array and using a data object internally. It also changes the sort direction string to be a boolean as I don't see the need for sorting in any other way than asc/desc. All in all this leads to a more consistent and predictable schema and state.

Extract class for pagination settings

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Features/Publications/Concerns/PublicationFieldTypes.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldType.php
packages/framework/tests/Feature/PublicationFieldTypeTest.php
packages/framework/tests/Feature/PublicationFieldTypesEnumTest.php

As we are starting to get a lot of logic regarding these, I think it might be worth playing around with adding an enum for them.

Create enum for publication types

---

packages/framework/src/Console/Commands/BuildSiteCommand.php

> https://github.com/hydephp/develop/issues/643
>
> There should be a vertical space before "All done"
>
> ![image](https://user-images.githubusercontent.com/95144705/199830747-5dec77b6-036f-4265-96bf-f78de69f5098.png)

Fix visual bug where there is no spacing before the finishing message of a site build

---

monorepo/HydeStan/HydeStan.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php

I think there's no point in creating a bunch of new objects each time we want to access a route, however since only pages with actual source files generally get added to the route index, the old behaviour is present as a fall back (for example when using `new MarkdownPage` in a test)

Get page routes from the route index

---

config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Unit/RelativeLinksAcrossPagesRetainsIntegrityTest.php

Implements the data generation backend for this feature.  We are still going to need to actually implement frontend code to support automatic dropdowns.
> https://github.com/hydephp/develop/issues/669
>
> Say we have a structure like this, where pages are in a directory of their source directory:
> 
> ```
> _pages/about/foo.md
> _pages/about/bar.md
> ```
> 
> How should Hyde handle the navigation for these pages? Currently they get added to the navigation menu, but maybe they shouldn't? I have a few ideas for improvement, and I think this should be configurable. I am very happy to get input on this, and also which option should be the default.
> 
> 1. Add the pages to the navigation menu (current behaviour)
> 2. Put them in an automatic dropdown based on the subdirectory name (my fav)
> …

Make navigation behaviour for nested pages configurable

---

packages/framework/src/Foundation/Concerns/ImplementsStringHelpers.php
packages/framework/src/Framework/Services/MarkdownService.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/MarkdownServiceTest.php

This will ease usages for things like https://github.com/hydephp/develop/pull/668 where the source markdown might be indented.
This means a Markdown document like this:
```markdown
Lorem Ipsum...
Indented code block
```
Will be normalized to this:
```markdown
Lorem Ipsum...
Indented code block
```
Since it auto-detects the root indentation level, it still allows for code blocks to be created by indentation. Tabs will also be converted to four spaces.

Add helper to strip indentation from a Markdown string

---

packages/framework/src/Framework/Actions/AnonymousViewCompiler.php
packages/framework/tests/Feature/Actions/AnonymousViewCompilerTest.php

Adds a class to compile any Blade file using the Blade facade as it allows us to render it without having to register the directory with the view finder.

Add simple class to compile any Blade file without having to register it as a view path

---

packages/framework/src/Framework/Exceptions/FileNotFoundException.php
packages/framework/tests/Feature/Actions/AnonymousViewCompilerTest.php

This adds more visual consistency and makes it easier to distinguish the path

Wrap the file path in brackets for the FileNotFoundException

---

packages/framework/src/Foundation/Concerns/ImplementsStringHelpers.php
packages/framework/src/Framework/Actions/CreatesNewPageSourceFile.php
packages/framework/src/Framework/Services/MarkdownService.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/MarkdownServiceTest.php

Adds a simple helper method that normalizes Windows line ending sequences to the (in my opinion, much cleaner) Unix LF endings. Also adds some related refactors.

Add normalizeNewlines helper to the Hyde facade and refactor related methods

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Console/Commands/ValidatePublicationsCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationPageTest.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationFieldTest.php
packages/framework/tests/Feature/PublicationPageTest.php
packages/framework/tests/Feature/PublicationTypeTest.php
packages/framework/tests/Unit/PublicationFieldValidationRulesTest.php
tests/fixtures/test-publication-schema.json

The range validations add a very large amount of complexity. I'm starting to think about how much we really need them. Sure length validation for article descriptions might be good, but do we really need to validate date ranges and integer values? Maybe it would be better to allow arbitrary Laravel validation rules to be specified in the schema file instead of its min/max values.
> _Originally posted by @caendesilva in https://github.com/hydephp/develop/issues/765#issuecomment-1361564784_

Remove range values from publications to reduce complexity

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/ValidatePublicationsCommand.php
packages/framework/src/Framework/Actions/SeedsPublicationFiles.php
packages/framework/src/Framework/Features/Publications/Models/PublicationField.php
packages/framework/src/Framework/Features/Publications/PublicationService.php
packages/framework/tests/Feature/Actions/SeedsPublicationFilesTest.php
packages/framework/tests/Feature/PublicationFieldTest.php

Simplifies how publication tags are handled.
Notably:
- The tagGroup property is now removed. It's assumed the tag group is the same as the publication type's identifier (same as the publication's directory name)
- Removes the $reload parameter and the caching of tags

Simplify publication tag handling

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Actions/CreatesNewPublicationType.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationTypeTest.php

From Robert RE: Generate list and detail pages when creating publication types
> That is a good idea, it could just be a simple/stupid template which does
> <p>{{ $fieldName}}: {{ $fieldValue}</p>
> Maybe something a bit more involved, but some sort of basic generic template which displays the data
_Originally posted by @caendesilva in https://github.com/hydephp/develop/issues/685#issuecomment-1328113544_

Generate list and detail pages when creating publication types 

---

packages/framework/src/Framework/Actions/CreatesNewPublicationType.php
packages/framework/src/Framework/Actions/PublicationPageCompiler.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Actions/PublicationPageCompilerTest.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/PublicationListPageTest.php
packages/framework/tests/Feature/PublicationPageTest.php
packages/framework/tests/Feature/PublicationTypeTest.php
packages/framework/tests/Unit/Pages/PublicationPageUnitTest.php
tests/fixtures/test-publication-schema.json

Refactors to check if template key ends with .blade.php and using that to signify if it's an anonymous view. This leads to a more verbose and intuitive system. If you specify a filename, Hyde will use the filename. If not, Hyde will assume it's a globally registered view.
This may break code on the [publications-feature](https://github.com/hydephp/develop/tree/publications-feature) branch as the schemas need to be updated: (see https://github.com/hydephp/develop/commit/9b471efa09c8c8ecd9b9d8ce394f0e5bb26daca9 for an example)
```diff
- "detailTemplate": "detail",
- "listTemplate": "list",
+ "detailTemplate": "detail.blade.php",
+ "listTemplate": "list.blade.php",
```
The files are still assumed to be in the same directory as the schema.json file.

Refactor view finder for publication templates to check file extensions instead of if view exists

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Concerns/ValidatingCommand.php
packages/framework/tests/Feature/ValidatingCommandTest.php

Refactors, fixes, and integrates, a console choice helper that can reload the choices by evaluating a supplied closure.

Properly implement reloadable choice helper for the validating command class

---

packages/framework/src/Console/Commands/BuildSiteCommand.php

This was originally contributed by @rgasch in https://github.com/hydephp/develop/pull/667 and is cherry-picked to master to resolve https://github.com/hydephp/develop/pull/685#discussion_r1057827407

Display maximum memory used during the site build

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Framework/Actions/ConvertsArrayToFrontMatter.php
packages/framework/src/Framework/Actions/CreatesNewPublicationPage.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/ArrayField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/TagField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/TextField.php
packages/framework/src/Framework/Features/Publications/PublicationFieldTypes.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationPageTest.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/PublicationFieldValueObjectsTest.php

This will bring better type safety and eventually reduce complexity in the command class and action. See https://github.com/hydephp/develop/pull/789
Also makes some refactors to the types themselves and surrounding logics as I now know better how they fit together.

Refactor the make:publication command to use the new field value objects

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Framework/Features/Publications/PublicationFieldTypes.php
packages/framework/src/Framework/Features/Publications/Rules/BooleanRule.php
packages/framework/src/Framework/Features/Publications/Validation/BooleanRule.php
packages/framework/tests/Feature/PublicationFieldTypesEnumTest.php

See https://github.com/hydephp/develop/issues/786#issuecomment-1366835331

Create custom validation rule for booleans

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/ArrayField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/PublicationFieldValue.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/TagField.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationPageTest.php
packages/framework/tests/Feature/PublicationFieldValueObjectsTest.php

Refactors the new field value classes to reduce complexity, primarily by overriding base class constructors instead of variadic argument unpacking.

Refactor publication field classes to reduce complexity

---

packages/framework/src/Console/Commands/Helpers/InputStreamHandler.php
packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Framework/Actions/CreatesNewPublicationPage.php
packages/framework/src/Framework/Features/Publications/PublicationFieldTypes.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/PublicationFieldValueObjectsTest.php
packages/framework/tests/Unit/InputStreamHandlerTest.php

Improves the integration between the new publication field classes and the make:publication command and fixes some bugs.

Refactor publication page creation internals

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/CanonicableTrait.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/Concerns/CanonicableTrait.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/Contracts/Canonicable.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/DatetimeField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/IntegerField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/StringField.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldValues/TextField.php
packages/framework/src/Framework/Features/Publications/PublicationFieldTypes.php
packages/framework/tests/Feature/PublicationFieldTypesEnumTest.php
packages/framework/tests/Features/Publications/Models/PublicationFieldValues/Concerns/CanonicableTraitTest.php

Refactors to add an interface and trait for publication field values that can be canonical

Refactor canonicable publication field internals

---

docs/digging-deeper/advanced-markdown.md
packages/framework/resources/views/components/filepath-label.blade.php
packages/framework/src/Framework/Services/MarkdownService.php
packages/framework/src/Markdown/Processing/CodeblockFilepathProcessor.php
packages/framework/tests/Feature/MarkdownServiceTest.php
packages/framework/tests/Feature/Services/Markdown/CodeblockFilepathProcessorTest.php

- Supports `/*` in filepath comments (just don't add a closing tagas that won't get removed)
- Refactor filepath patterns to be case insensitive as it makes no discernible performance difference but it does increase usability
- Removes support for the internal `{"shortcodes": false}` flag (see below) 42fade7ca1
- Echo filepath label as-is if HTML in Markdown is enabled to support links and more 7fe64842ff [^1]
- Adds the not-prose class to the filepath-label view 14b659be6f
- Remove support for Hyde Markdown Parser annotations (`// HYDE!`) as they are only used in one place[^2] which is simplified (see above) f4fd751408
- <s>Remove Hyde annotations on a line-by-line basis as it breaks when there is more than one annotation (multiple annotations on the same line still break and could be …

Refactor Markdown processing to improve usability and remove unnecessary internal code

---

packages/framework/src/Console/Commands/MakePublicationTagCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationTags.php
packages/framework/src/Framework/Features/Publications/PublicationService.php
packages/framework/tests/Feature/PublicationTagsTest.php
packages/framework/tests/Feature/Services/PublicationServiceTest.php

This refactor solves two problems:
1. It groups together related logic in a single class
2. It makes the data structure of the tags file more clear and structured thanks to rich type annotations

Create object representation for the tags.json file.

---

packages/framework/src/Console/Commands/MakePublicationCommand.php
packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Console/Commands/ValidatePublicationsCommand.php
packages/framework/src/Framework/Actions/SeedsPublicationFiles.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldDefinition.php
packages/framework/src/Framework/Features/Publications/Models/PublicationTags.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Actions/SeedsPublicationFilesTest.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationFieldDefinitionTest.php
packages/framework/tests/Feature/PublicationTagsTest.php
packages/framework/tests/Feature/PublicationTypeTest.php
packages/testing/src/TestCase.php

Adds back the tagGroup option for publication tag fields and adds a few tests and minor refactors for the publication type code.

Add back the tagGroup option for publication tag fields

---

packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php

This getter currently normalizes periods so there is always a leading period, but for page types without extensions (like https://github.com/hydephp/develop/pull/809) this would cause a trailing period to be added. This adds an additional normalization to trim those.

Update HydePage::fileExtension() getter to trim trailing periods to support extension-less page types

---

packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Pages/VirtualPage.php
packages/framework/tests/Unit/Pages/VirtualPageUnitTest.php

While I've been a bit hesitant about this before, since I like having the one-to-one mapping of a source file to a compiled file, I now see use cases where this is helpful.
For example, when generating pagination pages it would be helpful to have those internally represented as `HydePage`s as they'd otherwise require a separate compile process (which could be done in a post-build task but that adds a lot of unnecessary complexity that might not actually be needed).
Those pages could then instead be represented as a `VirtualPage` instance. It's then on the package developer to make sure the page is added to the `HydeKernel`'s `PageCollection` container; usually within the `boot` method of the package's service provider.
The actual class itself is minimal as it's designed to be extended.

Create VirtualPage class to make it easier for package developers to create pages without source files

---

packages/framework/src/Foundation/Concerns/ManagesHydeKernel.php
packages/framework/src/Pages/Contracts/DynamicPage.php
packages/framework/src/Pages/VirtualPage.php
packages/framework/tests/Feature/HydeKernelDynamicPageClassesTest.php
packages/framework/tests/Feature/HydeServiceProviderTest.php

This interface can be applied to virtual pages like in https://github.com/hydephp/develop/pull/809 and dynamic pages like publication pages in https://github.com/hydephp/develop/pull/685
Instances of this interface are excluded from the autodiscovery process

Create a DynamicPage interface for HydePages without (or with dynamic) source files

---

packages/framework/src/Framework/Actions/SeedsPublicationFiles.php
packages/framework/tests/Feature/Actions/SeedsPublicationFilesTest.php
packages/framework/tests/Feature/StaticSiteBuilderPublicationModuleTest.php

Improve publication feature testing

---

packages/framework/src/Framework/Features/Publications/Models/PublicationFieldDefinition.php
packages/framework/tests/Feature/ValidatesPublicationsTest.php

Takes a bit more pragmatic approach to the field name normalization

Refactor publication field definition name normalization 

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Console/Commands/ValidatePublicationsCommand.php
packages/framework/src/Framework/Actions/CreatesNewPublicationType.php
packages/framework/src/Framework/Features/Publications/Models/PaginationSettings.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Actions/CreatesNewPublicationTypeTest.php
packages/framework/tests/Feature/Actions/SeedsPublicationFilesTest.php
packages/framework/tests/Feature/Commands/MakePublicationCommandTest.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationListPageTest.php
packages/framework/tests/Feature/PublicationPageTest.php
packages/framework/tests/Feature/PublicationTypeTest.php
packages/framework/tests/Unit/Pages/PublicationPageUnitTest.php
packages/framework/tests/Unit/PaginationSettingsTest.php
packages/testing/src/TestCase.php
tests/fixtures/test-publication-schema.json

- Improves the publication type create command to better integrate pagination settings
- Removes the prevNextLinks setting as it's unlikely one would enable page size limits without a way to traverse them
- Makes the pagination settings property of publication types nullable, whilst also making pagination not be the default
- The publication type constructor now only accepts arrays for the publication setting (to keeps things simple, and since all other arguments are primitive PHP types)
- Change default publication type canonicalField value from identifier to __createdAt as this is what is being null coalesced to in the creator action, plus it matches the pagination defaults
- Refactor internal field data state to be parsed as this makes it impossible to create an invalid schema only to …

Refactor publication types to simplify the code and integrate publication pagination settings

---

packages/framework/src/Foundation/PageCollection.php
packages/framework/src/Foundation/RouteCollection.php

Exposes a previously internal method to the PageCollection class, which allows package developers to add pages to the PageCollection.
This is useful for adding on-off pages; if you are registering multiple pages, it's better to register an entire custom page class instead. It also normalizes the API of the matching method in the RouteCollection, and adds/improves package developer documentation for both.

Improve the public page and route discovery API

---

packages/framework/src/Foundation/Concerns/BootsHydeKernel.php
packages/framework/src/Foundation/Concerns/ManagesHydeKernel.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeKernelDynamicPageClassesTest.php
packages/framework/tests/Feature/PageCollectionTest.php
packages/testing/src/CreatesApplication.php

Refactors how and when the Kernel is booted, to allow package developers to register any services before it's too late in the lifecycle.
Integrates working changes from https://github.com/hydephp/develop/pull/822

Refactor kernel booting to defer until all providers have been registered

---

packages/framework/src/Pages/VirtualPage.php
packages/framework/tests/Unit/VirtualPageTest.php

Makes improvements to `VirtualPage.php`, such as
- Support Blade rendering of anonymous view files (any arbitrary project file path)
- Custom instance macros (more or less based on the Illuminate Macroable trait (MIT) but refactored to work on the instance not static class. The idea is that there will be very few virtual page instances around, if there are many it might be better to create a dedicated page class)

Virtual page improvements

---

packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/src/Commands/MakePublicationTagCommand.php
packages/publications/src/Commands/MakePublicationTypeCommand.php
packages/publications/src/Models/PublicationTags.php
packages/publications/tests/Feature/MakePublicationCommandTest.php
packages/publications/tests/Feature/MakePublicationTagCommandTest.php
packages/publications/tests/Feature/MakePublicationTypeCommandTest.php
packages/publications/tests/Feature/PublicationServiceTest.php
packages/publications/tests/Feature/PublicationTagsTest.php
packages/publications/tests/Feature/SeedsPublicationFilesTest.php

Since Yaml is a superset of Json, all Json will still validate. To migrate existing tag files, simply change the `.json` extension to `.yml` (example in https://github.com/hydephp/develop/commit/2c16bcd274871e90f45c40ac9f91b8d0277c3c82)

Change publication tags to use Yaml instead of Json

---

packages/publications/src/Models/PublicationListPage.php
packages/publications/tests/Feature/PublicationListPageTest.php

Publication list (index) pages now automatically show up in the navigation menu using the publication type's name as a label.
This can be disabled by adding the publication type's identifier (directory name) to the `hyde.navigation.exclude` config array settings. This is something that could be done in the schema, but frankly I think the config option is so easy it's not worth the added complexity of a schema change.

Show publication list pages in navigation

---

packages/publications/src/Commands/MakePublicationTypeCommand.php

Resolves the following code review comment:
> Also, when asking if you want another field, I think that "yes" is a better default than "no" because you'll hit yes more times than no (which by definition you'll only hit once)
However, when a terminal is not interactive, it still defaults to no to prevent the program from getting stuck.

Set default value of add another field question to yes in make:publicationType command

---

packages/framework/src/Framework/Services/MarkdownService.php

Refactors `MarkdownService::normalizeIndentationLevel()` to simplify control flow handling, and extracts some helper methods.

Refactor Markdown service helper for normalizing indentation 

---

packages/framework/src/Console/Commands/ValidateCommand.php
packages/framework/src/Framework/Concerns/TracksExecutionTime.php
packages/framework/src/Framework/Features/BuildTasks/BuildTask.php
packages/framework/src/Framework/Features/DataCollections/DataCollection.php
packages/framework/src/Framework/Features/XmlGenerators/SitemapGenerator.php
packages/framework/tests/Feature/TracksExecutionTimeTest.php

Since a few classes track execution time, we might as well extract all those helpers for reduced repeated code and consistency.

Extract trait for classes that track execution time

---

packages/framework/src/Framework/Concerns/InvokableAction.php

None of these child classes are ever used invokably used. A better alternative is to simply use a static `handle` method as that offers full type and IDE support.

Deprecate base class InvokableAction

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php

Fixes https://github.com/hydephp/develop/issues/867

Bugfix: Do not hide documentation pages in subdirectories

---

docs/digging-deeper/advanced-customization.md
packages/framework/src/Console/Commands/ChangeSourceDirectoryCommand.php
packages/framework/src/Console/HydeConsoleServiceProvider.php
packages/framework/tests/Feature/Commands/ChangeSourceDirectoryCommandTest.php

Adds a command that can be used to quickly change source directories. When run, Hyde will update the source directory setting in the config file, then create the directory if it doesn't exist, then move all source directories into it.

Add a command to automatically change source directories

---

packages/framework/src/Framework/Features/DataCollections/DataCollection.php
packages/framework/tests/Feature/DataCollectionTest.php

This class acts so fast, so there is virtually no reason to track execution time in it. Here are some results (all rounded to 5 decimals)
```
0ms
0ms
5.0E-5ms
0.00098ms
0.00032ms
3.0E-5ms
2.0E-5ms
```

Remove execution time tracking from the DataCollection class

---

docs/digging-deeper/collections.md
packages/framework/src/Framework/Features/DataCollections/DataCollection.php
packages/framework/src/Framework/Features/DataCollections/DataCollectionServiceProvider.php
packages/framework/tests/Feature/DataCollectionTest.php

Moving the (default) `_data` directory to `resources/collections` accomplishes two things:
1. Makes the top level directory structure leaner (which also distinguishes it from page directories.
2. The name collections makes more semantic sense for the usage, and I think the kind of data used fits within the resources domain too.
The directory is configurable, so this is just the defaults.
Any existing sites will need to move their data before upgrading. This is as easy as `mv -r _data resources/collections`
Tracked in [#877](https://github.com/hydephp/develop/issues/877)

Breaking: Change default DataCollection directory from `_data` to `resources/collections`

---

packages/framework/src/Console/Commands/ChangeSourceDirectoryCommand.php
packages/framework/src/Console/Concerns/Command.php
packages/framework/tests/Feature/CommandTest.php

Allows you to use this:
```php
$this->dynamicInfoComment('info [comment] moreInfo');
```
Instead of this:
```php
$this->infoComment('info', 'comment', 'moreInfo');
```
Both render the same thing:

Update InfoComment command helper to dynamically format output from a single fluent string

---

packages/framework/src/Console/Commands/RebuildStaticSiteCommand.php
packages/framework/src/Console/Concerns/Command.php
packages/framework/tests/Feature/CommandTest.php
packages/publications/src/Commands/ValidatingCommand.php
packages/publications/tests/Feature/MakePublicationCommandTest.php
packages/publications/tests/Feature/MakePublicationTypeCommandTest.php
packages/publications/tests/Feature/StaticSiteBuilderPublicationModuleTest.php
packages/publications/tests/Feature/ValidatePublicationTypesCommandTest.php
packages/publications/tests/Feature/ValidatePublicationsCommandTest.php
packages/publications/tests/Feature/ValidatingCommandTest.php
packages/testing/src/TestCase.php

This is part one of this refactor, where I'm moving the commands within this branch, next I'll cherry pick the changes to master. I'm also doing some refactoring to the actual command class while I'm at it.

Merge validating command features into base command

---

packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateSearch.php
packages/framework/src/Framework/Services/DocumentationSearchService.php
packages/framework/tests/Feature/Services/DocumentationSearchServiceTest.php

Cleans up `DocumentationSearchService.php`. The class is marked as internal, so nothing here is considered breaking.

Clean up the documentation search service class

---

packages/framework/src/Framework/Concerns/InteractsWithDirectories.php
packages/framework/tests/Unit/InteractsWithDirectoriesConcernTest.php

Refactor InteractsWithDirectories to use absolute paths using the filesystem helpers

Refactor the InteractsWithDirectories trait to use absolute paths for filesystem interactions

---

packages/framework/src/Facades/Site.php
packages/framework/src/Foundation/Filesystem.php
packages/framework/src/Framework/Concerns/RegistersFileLocations.php
packages/framework/src/Framework/Services/BuildService.php
packages/framework/tests/Feature/Commands/BuildSearchCommandTest.php
packages/framework/tests/Feature/HydeServiceProviderTest.php
packages/framework/tests/Feature/StaticPageBuilderTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php
packages/framework/tests/Unit/BuildOutputDirectoryCanBeChangedTest.php

This is intended to force a more consistent internal value state. Now there's no reason to have a bunch of warnings that the path must be relative, we can (and now do) just normalize it before assignment.
To upgrade external code using this class, replace the following:
`Site::$outputPath` => `Site::getOutputPath()` d9ca4a1045df4726aead75963b83b5704aaaf592
`Site::$outputPath = 'foo'` => `Site::setOutputPath('foo')` 50bdc1c517e35d7ffaace655d0944972d803deeb

Breaking: Make `Site::$outputPath` protected and accessible through setter/getters

---

packages/framework/src/Hyde.php
packages/framework/tests/Feature/HydeKernelTest.php

Adds a new shorter alias `Hyde::kernel()` that can be used to fluently call methods on the kernel, but with full IDE support. This because some things in the facade honestly don't feel like they need a method annotation but we still want IDE support without having to use verbose getInstance methods etc.
```php
Hyde::kernel(); // Same as HydeKernel::getInstance()
Hyde::kernel()->version(); // Same as HydeKernel::getInstance()->version() and the same as Hyde::version()
```

Add method alias to fluently interact with the HydeKernel through the Hyde facade

---

.idea/develop.iml
.idea/php.xml
composer.json
composer.lock

Adds https://github.com/JetBrains/phpstorm-attributes to the development dependencies for this monorepo. This will prevent us from getting undefined class errors from static analysis when using those attributes. This will not affect any of the downstream split packages.

Add JetBrains PhpStorm Attributes package to monorepo dev-dependencies

---

packages/framework/src/Facades/Site.php
packages/framework/src/Foundation/Concerns/ManagesHydeKernel.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Unit/BuildOutputDirectoryCanBeChangedTest.php

The variable location determining which directory the site is compiled to is moved from the Site facade to the HydeKernel.
Thanks to the accessors added in https://github.com/hydephp/develop/pull/902, this doesn't mess with the API (not that anyone has had time to use the new methods in the two hours since, but still)
I did not move the normalization forcing relative paths, as anyone messing with the HydeKernel should know what they're doing, but I might port the warning that the directory will be emptied (though I should double check if we need it since I'm pretty sure we warn if the directory seems unsafe) Edit: yeah there's a warning so all good. No need to add extra warnings IMO.

Move internal data store for the site output directory to the HydeKernel

---

.styleci.yml

As I strongly dislike the default ordering that mixes function and class imports I'm going to try to disable it, and let PhpStorm manually sort imports when needed.

Update monorepo `.styleci.yml` configuration to disable the `alpha_ordered_imports` rule

---

packages/framework/src/Facades/Site.php
packages/framework/tests/Feature/SiteTest.php

This alias allows you to get the absolute path to where the site is compiled to, or a file therein. This matches the `HydePage::path()` and `Hyde::path()` helpers.

Add method Site::path() to match similar model helper methods

---

.github/workflows/static-analysis.yml

Since GitHub Actions for some reason doesn't support exiting with warnings, we work around this by adding a second job. If the first job fails, this one won't run, thus resulting with a skipped status which we can interpret as a "warning".

Internal: Update GitHub action to exit more or less gracefully with skipped status instead of fail

---

packages/framework/src/Console/Commands/PublishHomepageCommand.php
packages/framework/src/Console/Commands/UpdateConfigsCommand.php

Cleans up some code related to the publishing commands
- Make the update:config command hidden
- Revert UpdateConfigsCommand deprecation
- Revert PublishHomepageCommand deprecation
- Remove resolved todo

Publishable code cleanup

---

packages/framework/src/Foundation/Concerns/ForwardsHyperlinks.php
packages/framework/src/Foundation/Hyperlinks.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/Foundation/HyperlinksTest.php
packages/framework/tests/Feature/HydeKernelTest.php

Convenience method that's a Mix between `Hyde::relativeLink()` and `Hyde::image()`.
It's accessible as `Hyde::mediaLink()` and can be used in Blade views to get a resolved relative link to a file in the media directory.

Add `Hyperlinks::mediaLink()` method

---

packages/framework/tests/Unit/Views/HeadComponentViewTest.php

This component is pretty important, so we might as well have some tests for it!

Add tests for the head component

---

packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/LocalFeaturedImage.php
packages/framework/tests/Feature/FeaturedImageTest.php

Prior to this refactor, the `$source` property of `LocalFeaturedImage` classes was forced to start with `_media/`, and threw an exception if it did not. The value was then normalized to the desired format upon accessing the value.
This PR changes so that the internal data value no longer contain the path information, as it is instead prepended when accessing the value. To keep the internal state consistent, any leading `_media/` prefixes are removed. Thus this change is entirely unbreaking as no usage outside the class is affected since the public accessors still function the same.
This change is important from an internal perspective however, as is more compatible with [customizable media directories #920](https://github.com/hydephp/develop/pull/920)

Refactor internal data store of LocalFeaturedImage $source property to not include directory information

---

packages/framework/src/Console/Commands/RebuildStaticPageCommand.php
packages/framework/src/Console/Commands/RebuildStaticSiteCommand.php
packages/framework/src/Console/HydeConsoleServiceProvider.php
packages/framework/tests/Feature/Commands/RebuildStaticPageCommandTest.php
packages/framework/tests/Feature/Commands/RebuildStaticSiteCommandTest.php

Refactors the `RebuildStaticSiteCommand `class to use newer helpers to reduce repeated code and to utilize an anonymous build task to keep a consistent output. Also renames the command to `RebuildStaticPageCommand` since it only rebuilds a single page.

Refactor the RebuildStaticSiteCommand class

---

packages/framework/src/Support/Filesystem/ProjectFile.php
packages/framework/tests/Feature/Support/MediaFileTest.php
packages/framework/tests/Feature/Support/ProjectFileTest.php
packages/framework/tests/Feature/Support/SourceFileTest.php

This method is only used in tests, and I see no real scenario when one would even want to cast something like this to string.

ProjectFile and inheritors no longer implement Stringable interface

---

packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Foundation/Concerns/HydeExtension.php
packages/framework/tests/Feature/Commands/RouteListCommandTest.php

Since these pages don't have source files it makes little sense to attempt to show one.
We could also in the future add a dynamic annotation briefly explaining what this means, and have a link to the docs/blog post.

Display different message for dynamic pages in route list command

---

packages/framework/src/Foundation/Filesystem.php
packages/framework/src/helpers.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php
packages/framework/tests/Feature/HelpersTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/HydeServiceProviderTest.php
packages/framework/tests/Unit/HydePathHelperTest.php

This will affect virtually all paths generated and assembled by HydePHP to use Unix style directory separators (`/`) instead of using the system-dependent `DIRECTORY_SEPARATOR` constant.
Since Windows fully accepts these directory separators, I don't see enough reason to have to bother concatenating in a bulky constant when a simple slash in a scalar value suffices.
You can't honestly tell me that `'foo'.DIRECTORY_SEPARATOR.'bar'` is prettier than `'foo/bar'` can you?

Refactor Filesystem to use Unix directory separators

---

packages/publications/src/Commands/Helpers/InputStreamHandler.php
packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/tests/Feature/InputStreamHandlerTest.php
packages/publications/tests/Feature/MakePublicationCommandTest.php
packages/publications/tests/Feature/MakePublicationTagCommandTest.php
packages/publications/tests/Feature/MakePublicationTypeCommandTest.php

Changes `InputStreamHandler` termination sequence from an empty line (`''`) to `'<<<'`.
While this is slightly more verbose, it prevents confusion and accidental premature termination as input strings might have empty lines. And the use case for entering paragraphs through the command line is (I assume) so slim that the extra characters are acceptable.
Fixes https://github.com/hydephp/publications/issues/2 and resolves code review comment https://github.com/hydephp/develop/pull/685#discussion_r1094682091

Change input string handler termination sequence to `<<<`

---

.github/workflows/smoke-tests.yml
packages/publications/src/Commands/Helpers/InputStreamHandler.php
packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/src/Commands/MakePublicationTagCommand.php
packages/publications/tests/Feature/InputStreamHandlerTest.php
packages/publications/tests/Feature/MakePublicationTagCommandTest.php

In addition to the added `'<<<'` sequence added in https://github.com/hydephp/develop/pull/936, this PR allows for an alternate method to terminate an input stream: by sending an [End-of-Transmission character](https://en.wikipedia.org/wiki/End-of-Transmission_character), usually via `CTRL+D`
<s>You still need to finish with hitting enter as I have not yet figured out a way to read live input instead of a line-to-line basis.</s>
Edit: It seems like `CTRL+D` on Windows sends an EOT Ascii character, `but CTRL+Z+Enter` on Windows seems to provide the same result as `CTRL+D` on Unix. This actually seems to return false from the standard input stream in PHP, so I think we should use that. It's also what [Symfony uses](https://github.com/symfony/console/blob/4c631f95ca95bfa4ed9869c7b74e12a29e28d …

Allow input stream termination by sending end-of-transmission character

---

packages/framework/src/Foundation/Providers/ConfigurationServiceProvider.php
packages/framework/src/Framework/HydeServiceProvider.php

Moves the `$this->publishes('configs')` call to the new `ConfigurationServiceProvider`

Move config publisher to configuration service provider

---

packages/framework/src/Foundation/Concerns/ForwardsFilesystem.php
packages/framework/src/Foundation/Filesystem.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php
packages/framework/tests/Unit/HydeVendorPathHelperTest.php

This allows the helper to access vendor files from our other packages. The added argument is optional and provides a default value matching existing behaviour, so this change is not breaking.

Update Hyde::vendorPath() helper to allow a Hyde package to be specified

---

packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeServiceProviderTest.php

Assuming the class is loaded, it only takes around `0.040ms/0.020ms` to instantiate a new `MarkdownConverter` instance. Compare that to `0.070ms/0.030ms` for accessing the singleton through the service container.
This tiny difference will never be noticeable in actual use. What's more, since there's nothing special about the singleton it doesn't even need to be registered as one. You can simply call `app(MarkdownConverter::class)` and the service container will resolve a new instance.
Since there's no reason to register this class into the service container I don't think we should. Fixes https://github.com/hydephp/develop/issues/952

No longer register the Markdown converter into the service container

---

packages/realtime-compiler/src/Http/HttpKernel.php
packages/realtime-compiler/src/Http/Middleware/PathNormalizerMiddleware.php
packages/realtime-compiler/src/Routing/Router.php
packages/realtime-compiler/tests/RealtimeCompilerTest.php

Adds a simple middleware feature to the realtime compiler `HttpKernel`.
The PR also refactors the path rewriting from https://github.com/hydephp/develop/pull/958 to use a middleware. This separates out the concerns from the router.
There is currently no public API added for this feature. As such, the middleware types are not explicitly enforced.
Middlewares are simple. They are callables that accept the incoming `Request` instance, and returns a modified one. Each middleware gets executed in order, and override the request instance, before being passed to the `Router`.
```php
$this->middleware[] = function (Request $request): Request {
// Do something with the request here...
return $request;
};
```
```php
class ExampleMiddleware extends BaseHttpKernel
{
public function __invoke(Request …
```

Add internal middlewares to the realtime compiler

---

app/Providers/AppServiceProvider.php

Since Laravel **X** (yes, I meant X, I refuse to call it anything else) is shipping with strong types, we should to! (We actually should have had in any case, I simply overlooked this file)

Add strong types to the bundled AppServiceProvider class

---

packages/framework/src/Framework/Features/Documentation/DocumentationSearchPage.php
packages/framework/tests/Feature/DocumentationSearchPageTest.php

Forgot to remove this when extending the documentation page class. The directory should not be included in the identifier, as that leads it to being added twice. If this page were file based, it would be in _docs/search.blade.php
Adds a helper to act as the source of truth for the route key. Makes it easier for things like the realtime compiler to use the same route key value that automatically supports the configured output directory.

Documentation search page class bugfix and cleanup

---

config/docs.php
packages/framework/config/docs.php

Reference environment variable instead of configuration option in config/docs.php as the loading order of configuration files is not guaranteed.
Fixes https://github.com/hydephp/develop/issues/967

Reference environment variable instead of configuration option in docs.php config file

---

packages/framework/src/Framework/Services/YamlConfigurationService.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Support/Models/RouteKey.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Unit/Pages/BaseHydePageUnitTest.php
packages/framework/tests/Unit/Pages/BladePageUnitTest.php
packages/framework/tests/Unit/Pages/DocumentationPageUnitTest.php
packages/framework/tests/Unit/Pages/HtmlPageUnitTest.php
packages/framework/tests/Unit/Pages/InMemoryPageUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPageUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPostUnitTest.php

Adds a static helper accessor method to get the output directory, as it makes the tight relationship between routes and output directories clearer in my opinion.

Add static `HydePage::baseRouteKey()` helper method

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/tests/Unit/DocumentationPageTest.php

Allows us to use `DocumentationPage::homeRouteName()` instead of `DocumentationPage::$outputDirectory.'/index'`, or worse yet, hardcoding `'docs/index'` which breaks if the user changes the output directory.
Fixes https://github.com/hydephp/develop/issues/972

Create helper to get the documentation page home route name

---

config/app.php
packages/framework/src/Console/ConsoleServiceProvider.php
packages/framework/src/Foundation/Providers/ViewServiceProvider.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeServiceProviderTest.php

Further restructures the Hyde service providers so each one has their own scoped function. See https://github.com/hydephp/develop/issues/939
1. Register providers in the `app.php` config instead of through the `HydeServiceProvider`
\- This allows them to be swapped out by advanced end users
2. Renames `HydeConsoleServiceProvider` to `ConsoleServiceProvider`
\- This is because no other providers have such a prefix, nor is it warranted
3. Normalize service provider code style and presentation
\- This is purely cosmetic

Restructure service providers

---

app/config.php
packages/framework/src/Foundation/Internal/LoadConfiguration.php
packages/framework/src/Foundation/Providers/ConfigurationServiceProvider.php

Since the removed config files like view and cache were moved to the vendor directory in https://github.com/hydephp/develop/pull/873, they then became dependent on a service provider registration. Since their registration order is not guaranteed, this PR refactors to merge those configuration files in the configuration loading bootstrapper.
See https://github.com/hydephp/develop/pull/873#discussion_r1103767486
The PR also deprecates `ConfigurationServiceProvider.php` as it's so simplified that it can be merged into the HydeServiceProvider.

Register inlined configuration files in bootstrapper class

---

packages/framework/src/Console/Commands/RebuildStaticPageCommand.php
packages/framework/src/Foundation/Facades/Files.php
packages/framework/src/Foundation/Facades/Pages.php
packages/framework/src/Foundation/Facades/Routes.php
packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Framework/Features/Navigation/BaseNavigationMenu.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/src/Framework/Services/RebuildService.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Support/Models/Route.php
packages/framework/tests/Feature/HydeKernelDynamicPageClassesTest.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Unit/FoundationFacadesTest.php

| Old                                      | New                              |
|------------------------------------------|----------------------------------|
| `Hyde\Foundation\Facades\FileCollection` | `Hyde\Foundation\Facades\Files`  |
| `Hyde\Foundation\Facades\PageCollection` | `Hyde\Foundation\Facades\Pages`  |
| `Hyde\Foundation\Facades\Router`         | `Hyde\Foundation\Facades\Router` |
This provides two benefits:
1. First, better IDE autocompletion as the facades will not conflict with the underlying classes.
2. And second, they would match the syntax of `Hyde::files()`, `Hyde::pages()`, and `Hyde::routes()`.
Fixes https://github.com/hydephp/develop/issues/980

Rename foundation collection facades

---

packages/framework/src/Markdown/Processing/ColoredBlockquotes.php
packages/framework/tests/Feature/ColoredBlockquoteShortcodesTest.php
packages/framework/tests/Feature/Services/Markdown/ShortcodeProcessorTest.php

Since the shortcode resolves to an already compiled `<blockquote>` element, the Markdown processor treats its contents as literal strings. This PR fixes https://github.com/hydephp/develop/issues/971 and renders the Markdown value within to HTML.
In other words, `>info foo **bar**` now becomes 'foo **bar**' instead of just 'foo \*\*bar**'
As a side effect, this means that the content is also wrapped in a `<p>` element, but since that I think is more semantically correct I'm okay with that. 
Note that it does mean that the rendered result has some increased padding which I think is good because it makes them blend in better with the normal blockquotes.
| Before                                                                                                          | After …

Update coloured blockquotes to support inner Markdown

---

packages/framework/src/Foundation/Providers/ConfigurationServiceProvider.php

Adds two new publishable groups, one for Hyde configs, and one for support configs.
Fixes the following code review comment:
> Split out publishable key vendor config files? Maybe vendor-configs? It's a bit weird now that when you run the update:config commands new (the removed) files get added. Might be better to have a --no-vendor or --include-vendor option. https://github.com/hydephp/develop/pull/873

Add more publishable options for configs so specific tags can be selected

---

packages/framework/src/Console/Commands/UpdateConfigsCommand.php
packages/framework/tests/Feature/Commands/UpdateConfigsCommandTest.php

Takes advantage of the tags introduced in https://github.com/hydephp/develop/pull/983 to allow user to select to only publish Hyde configs, Laravel configs, or both (default).

Update UpdateConfigsCommand to prompt for which tag to publish

---

packages/framework/src/Foundation/Concerns/ManagesExtensions.php
packages/framework/src/Foundation/Concerns/ManagesHydeKernel.php
packages/framework/src/Foundation/Concerns/ManagesKernelExtensions.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php

Splits out internal ManagesHydeKernel trait to move the helpers related to extensions into a new internal ManagesExtensions trait.

Split out internal ManagesHydeKernel trait

---

packages/framework/src/Framework/Features/BuildTasks/BuildTask.php

Fixes https://github.com/hydephp/develop/issues/994

Remove deprecated BuildTask::getExecutionTime() method

---

packages/framework/src/Framework/Services/BuildTaskService.php
packages/framework/tests/Feature/Services/BuildTaskServiceTest.php

Fixes https://github.com/hydephp/develop/issues/995

Remove deprecated BuildTaskService::findTasksInAppDirectory() method from the public API

---

app/config.php
packages/framework/src/Framework/Features/DataCollections/Facades/MarkdownCollection.php
packages/framework/tests/Feature/DataCollectionTest.php

This class is so incredibly simple it offers very little value.
To upgrade, simply replace the following:
```diff
- MarkdownCollection::get($collectionKey);
+ DataCollection::markdown($collectionKey);
```
Yeah, that's all the class does. It's just an alias for this single method. No need to have an entire file for it.
Fixes https://github.com/hydephp/develop/issues/997

Removes deprecated MarkdownCollection class

---

packages/framework/src/Console/Concerns/Command.php
packages/framework/src/Framework/Actions/ConvertsMarkdownToPlainText.php
packages/framework/src/Pages/Concerns/UsesFlattenedOutputPaths.php
packages/realtime-compiler/src/Http/DashboardController.php

The following have had their `@experimental` status removed
1. Command.php (methods `gray` and `inlineGray`))
- These methods are unlikely to change at this point 
2. ConvertsMarkdownToPlainText.php (class)
- Class only has one public method (excluding constructor) so API is unlikely to change
3. UsesFlattenedOutputPaths.php (trait)
- Trait has not been changed in a long time and is unlikely to do so
4. DashboardController.php (RealtimeCompiler class)
- The Realtime Compiler package has no backwards compatibility guarantees outside of its coupling with standard HydePHP versions, and thus all of its classes can be considered internal
See https://github.com/hydephp/develop/issues/998

Remove `@experimental` annotations for stable code

---

packages/realtime-compiler/README.md
packages/realtime-compiler/SECURITY.md

- Adds the upcoming version to realtime compiler readme
- Realtime Compiler LTS version 1.0 reaches End of Life: 2023-03-01

Update Realtime Compiler readme

---

config/docs.php
packages/framework/config/docs.php

Deprecates the config option `docs.output_directory` (in docs.php) as it will conflict with https://github.com/hydephp/develop/pull/1014

Deprecate config option `docs.output_directory`

---

config/docs.php
docs/creating-content/documentation-pages.md
packages/framework/config/docs.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeServiceProviderTest.php
packages/framework/tests/Feature/StaticPageBuilderTest.php
packages/framework/tests/Unit/DocumentationPageTest.php

This is being replaced by `hyde.source_directories.Hyde\Pages\DocumentationPage` in https://github.com/hydephp/develop/pull/1014
So, instead of the following in `config/docs.php`
```php
'output_directory' => 'foo',
```
You would use the following in `config/hyde.php`
```php
'output_directories' => [
// [...]
\Hyde\Pages\DocumentationPage::class => 'foo',
],
```

Remove config option `docs.output_directory`

---

app/config.php
packages/framework/src/Facades/Config.php
packages/framework/tests/Feature/TypedConfigFacadeTest.php

Adds an extension of the Laravel Config facade with extra accessors that ensure the types of the returned values. In strict mode, the type must match, in cast mode (currently default) an attempt to cast the values will be made.
Will aid tremendously with https://github.com/hydephp/develop/issues/1021.
I will probably play around with the strict mode, and then decide to keep it, or inline either strict or cast mode, then I'll revert making it experimental/internal.

Create superset Config facade with strongly typed accessors

---

config/docs.php
packages/framework/config/docs.php
packages/framework/resources/views/components/docs/sidebar.blade.php

Makes the documentation sidebar footer configurable
| With footer (default)                                                                                                                                     | Without footer                                                                                                                                        |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![localhost_8080_docs_index html(Macbook Pro) (1)](https://user-images.githubusercontent.com/95144705/219017752-2fa2370f-17b1- …

Add configuration option to disable the sidebar footer

---

packages/framework/resources/views/components/docs/grouped-sidebar-navigation.blade.php
tests/Browser/HighLevelViewTest.php

Fixes https://github.com/hydephp/develop/issues/1028
Changes the inner conflicting element. As far as I can tell, this the only internal use we have is for Dusk identifiers but custom sites may of course rely on this, but that's a BC risk I'm willing to take as this is a bug and the framework is still in beta and has no BC promise yet.
**Before:** `#sidebar-navigation > #sidebar-navigation`
**After:**  `#sidebar-navigation > #sidebar-navigation-items`

Rename conflicting sidebar HTML ID

---

packages/framework/src/Foundation/Concerns/BaseFoundationCollection.php
packages/framework/src/Foundation/Concerns/BootsHydeKernel.php
packages/framework/tests/Feature/FileCollectionTest.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php
packages/framework/tests/Feature/PageCollectionTest.php
packages/framework/tests/Feature/RouteCollectionTest.php
packages/framework/tests/Unit/BaseFoundationCollectionTest.php

This breaking (though I doubt anyone is using these methods yet) PR splits the `BaseFoundationCollection::boot()` method into two: `BaseFoundationCollection::init()` and `$foundationCollectionInstance->boot()`. This allows us to execute code between the object construction and the booting process, for example to run a booting callback like is being added in https://github.com/hydephp/develop/pull/1037.
Previous behaviour can easily be attained by chaining the boot method to the init call. See 1280c262d3bb24615fb2571524e98f385c1f69be
```php
- BaseFoundationCollection::boot(HydeKernel::getInstance())
+ BaseFoundationCollection::init(HydeKernel::getInstance())->boot()
```

Breaking: Decouple discovery booting from foundation collection instantiation

---

packages/framework/src/Foundation/Concerns/BootsHydeKernel.php
packages/framework/tests/Feature/HydeKernelTest.php

While the Extensions API is very powerful and simple to use, it's often overkill user projects; they're designed for package developers after all.
This PR adds a system of callbacks run before and after the `HydeKernel` boots, just like you might be familiar with from Laravel.
For example, let's say you want to register an `InMemoryPage` like the `Redirect` page, you can now easily do so, suggestively in the `boot` method of your `AppServiceProvider`:
```php
class AppServiceProvider extends ServiceProvider {
public function boot(): void {
Hyde::kernel()->booting(function (HydeKernel $kernel): void {
$kernel->pages()->addPage(new Redirect('foo', 'bar'));
});
}
}
```
Since the initialization and booting of foundation collections were decoupled in …

Add HydeKernel booting callback API

---

packages/framework/resources/views/components/docs/grouped-sidebar-navigation.blade.php

> If possible to create without complexity and bloat, it'd be nice if the grouped sidebar had an option to be collapsible. Preferably, the active sidebar group would automatically be open. And others would be togglable with a chevron justified to the right of the group heading.
> 
> To further signify the interactivity the heading row should darken when hovered upon, similar to the actual navigation items.
> 
> Bonus if the transition is animated.
Todos

Add feature to use collapsible grouped documentation sidebars

---

packages/framework/src/Facades/Config.php
packages/framework/tests/Feature/TypedConfigFacadeTest.php

This removes a lot of complexity, and if you are using a typed config facade it's probably because you want to be sure of the type. Implicit type casting may cause unintended results when a failing state is desired for invalid/missing data.

Typed config facade now only uses strict mode

---

packages/framework/src/Framework/Services/AssetService.php
packages/framework/tests/Feature/AssetServiceTest.php

Updates the AssetService constructor to check config for if a custom HydeFront version is specified. This will then be loaded into the Asset Singleton.
I say it's "hidden" as it's not in the base config file as I think the option is an edge case. I just want it so we can use the master version for the monorepo preview sites, like the upcoming documentation one.

Add "hidden" configuration option for setting the HydeFront version

---

packages/framework/src/Framework/Services/AssetService.php
packages/framework/tests/Feature/AssetServiceTest.php

Adds another "hidden" config option, here letting users specify a custom CDN URI to load. For example, if you want to use something other than jsDelivr. This is of course not compatible with the custom versioning or dynamic paths supported by the defaults, but the option is there for power users who want customization without having to publish the view component which may get outdated.

Add feature to allow custom HydeFront CDN link to be set in config

---

docs/advanced-features/page-models.md
packages/framework/src/Console/Commands/ChangeSourceDirectoryCommand.php
packages/framework/src/Framework/Concerns/RegistersFileLocations.php
packages/framework/src/Framework/Features/DataCollections/DataCollection.php
packages/framework/src/Framework/Features/Documentation/DocumentationSearchPage.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/src/Pages/BladePage.php
packages/framework/src/Pages/Concerns/BaseMarkdownPage.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/src/Pages/HtmlPage.php
packages/framework/src/Pages/InMemoryPage.php
packages/framework/src/Pages/MarkdownPage.php
packages/framework/src/Pages/MarkdownPost.php
packages/framework/src/Support/Filesystem/SourceFile.php
packages/framework/tests/Feature/Commands/BuildSearchCommandTest.php
packages/framework/tests/Feature/DataCollectionTest.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Feature/DocumentationSearchPageTest.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Feature/HydeServiceProviderTest.php
packages/framework/tests/Feature/PageCollectionTest.php
packages/framework/tests/Feature/SourceDirectoriesCanBeChangedTest.php
packages/framework/tests/Feature/StaticPageBuilderTest.php
packages/framework/tests/Unit/ConfigFileTest.php
packages/framework/tests/Unit/SourceFilesInCustomDirectoriesCanBeCompiledTest.php

To scope down the public API, the discovery information properties will be made protected, which is breaking, but will fix https://github.com/hydephp/develop/issues/1010. They may also be moved down to the classes that are discoverable, possibly via a trait or (unlikely a new base class)
```php
// Before
HydePage::$sourceDirectory;
HydePage::$sourceDirectory = 'foo';
// After
HydePage::sourceDirectory();
HydePage::setSourceDirectory('foo');
```
- Only one canonical place to get the source information (just getter, not getter or property)
- Can normalize and validate input using setter
- Needs setter which adds extra methods
- No PhpStorm default value hint when using accessor<br>
&nbsp; &nbsp; ![image](https://user-images.githubusercontent.com/95144705/218426657-dd6ad51a-5d6f-4d2e-9944-71f …

Breaking: Make page discovery information properties protected

---

packages/framework/src/Pages/Concerns/Discoverable.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php

To scope down the public API, the discovery information properties were made protected in https://github.com/hydephp/develop/pull/1062. This PR extracts the contracted methods for classes that are discoverable, into a Discoverable trait that can be shared among HydePage child classes.

Extract trait for Discoverable HydePages

---

packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php

This implicit dynamic state became obsolete by https://github.com/hydephp/develop/pull/1061 as state now does not need to be calculated as contracted implementations are forced to implement discovery data.
This partially reverts PR https://github.com/hydephp/develop/pull/1019.

Determine discoverable state depending on interface implementation

---

packages/framework/src/Pages/BladePage.php
packages/framework/src/Pages/Concerns/BaseMarkdownPage.php
packages/framework/src/Pages/Concerns/Discoverable.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Pages/HtmlPage.php
packages/framework/tests/Feature/HydePageTest.php

Changes the HydePage classes to use the Discoverable trait added in https://github.com/hydephp/develop/pull/1066 so that only discoverable pages use the trait, not the base HydePage class.

Breaking: Break out discoverable properties from HydePage base class

---

docs/advanced-features/page-models.md
packages/framework/src/Pages/BladePage.php
packages/framework/src/Pages/Concerns/DiscoverablePage.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/src/Pages/HtmlPage.php
packages/framework/src/Pages/InMemoryPage.php
packages/framework/src/Pages/MarkdownPage.php
packages/framework/src/Pages/MarkdownPost.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php
packages/framework/tests/Feature/HydePageTest.php

This reverts some mistakes I made when thinking in the following PRs, none of which has yet been merged into master. The problem was including the outputDirectory setting when refactoring properties relating to discovery. 
This reverts some of the changes in the following PRs:
- https://github.com/hydephp/develop/pull/1061
- https://github.com/hydephp/develop/pull/1062
- https://github.com/hydephp/develop/pull/1066
- https://github.com/hydephp/develop/pull/1067
- https://github.com/hydephp/develop/pull/1068
I'm keeping commits like e4522ca53e9e90f7994ff8e868cd8e7f838e08fc and f24bfb4068e9207fc119ea658bcc9e33236d199b as they still are valid, though they are broken out of the contract and put back into the base class.
After this simplification, I will also have to reconsider which of these …

Revert breaking output directory changes

---

docs/advanced-features/page-models.md
packages/framework/src/Pages/BladePage.php
packages/framework/src/Pages/Concerns/BaseMarkdownPage.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/src/Pages/HtmlPage.php
packages/framework/src/Pages/InMemoryPage.php
packages/framework/src/Pages/MarkdownPage.php
packages/framework/src/Pages/MarkdownPost.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php
packages/framework/tests/Feature/HydePageTest.php

Partially reverts PR https://github.com/hydephp/develop/pull/1062 (not yet merged into master)
- Reverts the making of public properties protected (mainly because all other properties are protected in the class, and that's not a huge problem IMO)
- It does keep the added setters as an alternative syntax (and it's still recommended* to use these as they normalize the input)
*It's actually best to use the configuration options, but if you have to modify the static properties, do it via the setters.

Revert overengineered PR changes

---

packages/framework/src/Foundation/Kernel/Filesystem.php
packages/framework/src/Foundation/PharSupport.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php
packages/framework/tests/Feature/PharSupportTest.php

Adds a `PharSupport` helper class to get and mock the Phar state. Also refactors the `vendorPath` helper to properly support running in vendorless Phars.

Add experimental framework support for compiling the HydeCLI to a standalone application

---

packages/framework/src/Foundation/Kernel/FileCollection.php

This issue was somehow surfaced after upgrading to Laravel 10, and presented itself in the `publications-feature` branch (since that extension registers an `InMemoryPage`). Nonetheless, I consider it a bug as discovery should not be attempted for non-discoverable page classes.

Only attempt file discovery for discoverable page classes

---

packages/framework/src/Framework/Actions/CreatesNewMarkdownPostFile.php
packages/framework/src/Framework/Actions/CreatesNewPageSourceFile.php
packages/framework/src/Pages/Concerns/BaseMarkdownPage.php
packages/framework/tests/Feature/Actions/CreatesNewPageSourceFileTest.php
packages/framework/tests/Feature/HydePageTest.php

These files have been around since pretty much the start of Hyde, so they deserve another round of polishing before the 1.0 release to refactor to use newer helpers and anything else as needed.
Major changes:
- Refactor: Change `CreatesNewMarkdownPostFile` action to save file by creating a new object then saving it
- Refactor: Change `CreatesNewPageSourceFile` action to save Markdown files by creating new objects then saving then
- Bugfix: Update `BaseMarkdownPage::save` method to create parent directory if needed
- Breaking: Constructor parameters `$date` and `$identifier` in `CreatesNewMarkdownPostFile` have been removed as they are always null within the application (only affects if anyone has used this class outside of the framework, which is discouraged at this time)
- Change: Append …

Refactor page creation actions

---

packages/framework/src/Framework/Exceptions/FileConflictException.php
packages/framework/tests/Feature/Actions/CreatesNewPageSourceFileTest.php
packages/framework/tests/Feature/Commands/MakePageCommandTest.php
packages/framework/tests/Unit/FileConflictExceptionTest.php

Updates the `FileConflictException` message to turn absolute paths to relative. This may break output that depends on the output. Some tests will need to be updated. Also adds a unit test for the exception class.

Update FileConflictException message to turn absolute paths to relative

---

packages/framework/src/Framework/Concerns/InteractsWithDirectories.php

This trait is intended to provide helpers for the class using it, not to add to its public API. So there should be no reason for these methods to be public.

Make public InteractsWithDirectories trait methods protected

---

packages/framework/resources/views/layouts/head.blade.php
packages/framework/src/Framework/Features/Metadata/PageMetadataBag.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Unit/Pages/BaseHydePageUnitTest.php
packages/framework/tests/Unit/Pages/BladePageUnitTest.php
packages/framework/tests/Unit/Pages/DocumentationPageUnitTest.php
packages/framework/tests/Unit/Pages/HtmlPageUnitTest.php
packages/framework/tests/Unit/Pages/InMemoryPageUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPageUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPostUnitTest.php
packages/framework/tests/Unit/Views/HeadComponentViewTest.php
packages/ui-kit/docs/components-demo.blade.php

Shortens the wierdly named helper methods. Thanks to Twitter for voting on the new method name! This will break any published views.
```blade
- <title>{{ $page->htmlTitle() }}</title>
+ <title>{{ $page->title() }}</title>
```

Rename HydePage::htmlTitle method to HydePage::title

---

packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

Updates the navigation group isActive logic so that the first navigation group of a collapsed sidebar is considered active when on the documentation page, even if the index page does not have a specified navigation group. This automatic state is not applied if the index page has a navigation menu group set in its front matter. Fixes https://github.com/hydephp/develop/issues/1083
| Before                                                                                                                                               | After                                                                                                                                                    |
|------------------------------------------------------------------------------------------------------------- …

Expand first collapsed sidebar group for documentation index page

---

packages/framework/src/Facades/Filesystem.php

This makes it easier to swap out the container object without having to boot facades. It should not affect any semantics.

Refactor Filesystem facade to get Illuminate filesystem from service container instead of facade root

---

docs/digging-deeper/advanced-customization.md
packages/framework/src/Console/Commands/BuildRssFeedCommand.php
packages/framework/src/Console/Commands/BuildSearchCommand.php
packages/framework/src/Console/Commands/BuildSitemapCommand.php
packages/framework/src/Console/Commands/RebuildStaticPageCommand.php
packages/framework/src/Framework/Features/BuildTasks/BuildTask.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateBuildManifest.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateRssFeed.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateSearch.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateSitemap.php

Goes over the BuildTasks feature and their API. Contains breaking changes to any existing BuildTasks.
Notable and breaking changes:
- Breaking: Rename BuildTask::$description to BuildTask::$message
- Minor breaking: BuildTask::handle() no longer has nullable return type
- Minor breaking: BuildTask::$exitCode is no longer nullable
- May break things: Set default BuildTask exit code from null to 0

Polish the BuildTask API

---

packages/framework/src/Foundation/Concerns/ForwardsHyperlinks.php
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/Foundation/HyperlinksTest.php

Adds an argument to the Hyde::mediaLink helper that will enable a validation that will throw an exception if the file could not be found in the configured _media directory.

Add Hyde::mediaLink argument to enable source media file existence validation

---

packages/framework/src/Markdown/Contracts/FrontMatter/BlogPostSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/PageSchema.php
packages/framework/tests/Unit/SchemaContractsTest.php

Updates the syntax of the front matter schema arrays to change how subschemas are referenced. This is breaking as it modifies interfaces.
The previous format for referencing sub-schemas is a bit unclear. Take the following as an example:
```php
'string|array|featured_image'
```
To me, this looks like the property accepts three input types. But in fact, it only accepts two. String, OR an array conforming to the `FeaturedImage` subschema.
```php
'string|array<featured_image>'
```
I believe this makes it more clear that two types are accepted and due to the `|` operator it's one `OR` the other. And I think it signifies that the array is of the generic shape of `FeaturedImage`.
For the `BlogPostSchema` interface that has a secondary constant for the author schema, this is referenced as …

Breaking: Update schema interfaces to use a pseudo-generic array specifier

---

packages/framework/src/Markdown/Contracts/FrontMatter/BlogPostSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/PageSchema.php
packages/framework/tests/Unit/SchemaContractsTest.php

Similar to https://github.com/hydephp/develop/pull/1090, this change changes the `'string|url'` syntax to be `'string(url)'` to make it clearer that the auxiliary type is a specifier not an alternative standalone type.
It uses `(parentheses)` instead of `<generics>` to distinguish it from the subschema identifiers added in #1090. I also considered a pseudo type of `'url-string'` but I think this change is more easily machine-and-humanly modifiable.

Breaking: Update schema interface syntax for union typed url-strings

---

docs/creating-content/blog-posts.md
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/LocalFeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/RemoteFeaturedImage.php
packages/framework/src/Markdown/Contracts/FrontMatter/SubSchemas/FeaturedImageSchema.php
packages/framework/tests/Feature/FeaturedImageFactoryTest.php
packages/framework/tests/Feature/FeaturedImageTest.php
packages/framework/tests/Feature/MarkdownPostTest.php
packages/framework/tests/Feature/MetadataTest.php
packages/framework/tests/Unit/SchemaContractsTest.php
packages/framework/tests/Unit/Views/FeaturedImageViewTest.php

Implements the proposed change in https://github.com/hydephp/develop/pull/1093#issuecomment-1439109372 to simplify the API by merging `image.path` and `image.url` into a single `image.source` (or just the `image` one when not using array) property that determines local/remote state depending on whether it starts with `http` or `//`. 
Although this is a breaking change, I believe it is worth it. This change also aligns with the internal data structure, where both input options are stored in the `$source` property. Furthermore, we no longer need to specify that one property overrides the other.
In other words, both `image.url` and `image.path` are now `image.source`, which equals the behaviour of when using `image: somestring`
No change here.
```yaml
image: image.jpg
```
```yaml
image: …
```

Breaking: Merge blog post featured image source front matter properties

---

docs/creating-content/blog-posts.md
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/LocalFeaturedImage.php
packages/framework/src/Framework/Features/Blogging/Models/RemoteFeaturedImage.php
packages/framework/src/Markdown/Contracts/FrontMatter/SubSchemas/FeaturedImageSchema.php
packages/framework/tests/Feature/FeaturedImageFactoryTest.php
packages/framework/tests/Feature/FeaturedImageTest.php
packages/framework/tests/Feature/MarkdownPostTest.php
packages/framework/tests/Feature/MetadataTest.php
packages/framework/tests/Unit/SchemaContractsTest.php
packages/framework/tests/Unit/Views/FeaturedImageViewTest.php
tests/fixtures/_posts/typography-front-matter.md

This provides a nice feature, but there's honestly not enough reason to use three classes for such a scoped feature. Hence this (obviously breaking) refactor to aggressively simplify these classes, merging in the two child classes into the base abstract class.

Aggressively simplify the featured image classes

---

packages/framework/tests/Unit/BaseFoundationCollectionTest.php
packages/framework/tests/Unit/BlogPostFrontMatterIsOptionalTest.php
packages/framework/tests/Unit/BuildOutputDirectoryCanBeChangedTest.php
packages/framework/tests/Unit/EnsureCommandsFollowNamingConventionTest.php
packages/framework/tests/Unit/FrontMatterModelTest.php
packages/framework/tests/Unit/MarkdownFacadeTest.php
packages/framework/tests/Unit/RelativeLinksAcrossPagesRetainsIntegrityTest.php
packages/framework/tests/Unit/RouteNotFoundExceptionTest.php
packages/framework/tests/Unit/SchemaContractsTest.php
packages/framework/tests/Unit/SerializableContractTest.php
packages/framework/tests/Unit/SerializableTest.php
packages/framework/tests/Unit/UnsupportedPageTypeExceptionTest.php
packages/testing/src/UnitTestCase.php

Refactors and updates unit tests, making the entire unit test suite be about 500ms faster which accounts to about one minute less CI time each day on average which according to calculations made by ChatGPT will save about 200 grams of CO2 emissions per year.

Internal: Update unit tests

---

packages/publications/src/PublicationService.php
packages/publications/tests/Feature/PublicationServiceTest.php

The `getPublicationsForPubType` method in the `PublicationService` class is missing the ability to sort the publications by a specified field and direction. Currently, it only returns the publications in the order they were found. 
This pull request fixes issue https://github.com/hydephp/publications/issues/7.
This pull request adds the ability to sort the publications by a specified field and direction. The `getPublicationsForPubType` method now accepts two new optional parameters: `$sortField` and `$sortAscending`. If `$sortField` is set, it will sort the publications by that field. If `$sortAscending` is set to `true`, it will sort the publications in ascending order; if set to `false`, it will sort them in descending order.
- Added new parameters to `getPublicationsForPubType` method …

Add ability to specify sort field when retrieving publication list

---

packages/framework/src/Markdown/Models/MarkdownDocument.php

This changes no semantics (apart from two new inherited helpers) but allows us to use the same methods implementations as the MarkdownPage class to provide a consistent API and have less repeated code.

Refactor MarkdownDocument class to use InteractsWithFrontMatter trait

---

packages/publications/src/Actions/CreatesNewPublicationPage.php
packages/publications/src/Actions/PublicationFieldValidator.php
packages/publications/src/Actions/PublicationSchemaValidator.php
packages/publications/src/Actions/SeedsPublicationFiles.php
packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/src/Commands/SeedPublicationCommand.php
packages/publications/src/Models/PublicationType.php
packages/publications/src/PublicationService.php
packages/publications/src/PublicationsExtension.php
packages/publications/tests/Feature/PublicationServiceTest.php
packages/publications/tests/Feature/PublicationTypeTest.php

Renames the following methods to remove the Pub prefix as it's implied since the method belongs to the PublicationService.
- Renames method `PublicationService::getMediaForPubType` to `PublicationService::getMediaForType`
- Renames method `PublicationService::getPublicationsForPubType` to `PublicationService::getPublicationsForType`
Expands `pubType` to `publicationType` for both local variables, class properties, constructor parameters, and internal helper methods, in the following classes:
- SeedsPublicationFiles
- SeedPublicationCommand
- PublicationService
- PublicationSchemaValidator
- CreatesNewPublicationPage

Breaking publication package renames

---

packages/framework/src/Framework/Factories/HydePageDataFactory.php
packages/framework/tests/Unit/HydePageDataFactoryTest.php

This PR updates the dynamic title generation for index pages to use the parent basename as the page title. This adresses issue https://github.com/hydephp/develop/issues/1107.
The existing codebase was rewriting the titles of index and docs/index pages, unless explicitly set. The new internal method `findTitleFromParentIdentifier()` has been added to retrieve the title of the parent identifier, which is called from the existing `findTitleForPage()` method when a title is not explicitly set or found from the markdown headings.
This is because almost no time do index pages need to be named "index", so updating this making them easier to navigate and understand.
- Added `findTitleFromParentIdentifier()` method to retrieve title from parent identifier.
- Updated `findTitleForPage()` method to …

Update dynamic title generation for index pages to use parent basename

---

packages/framework/src/Pages/InMemoryPage.php
packages/framework/tests/Unit/Pages/InMemoryPageTest.php

Adds a simple helper method to determine if an InMemoryPage instance has a macro of the given name registered.

Add a `InMemoryPag::hasMacro()` helper method

---

packages/framework/src/Markdown/Models/FrontMatter.php
packages/framework/tests/Unit/FrontMatterModelTest.php

This class already has a very nice public API to work with, so there's really no reason for this to be public.
In addition to accessors with support for fallbacks, the exact same $data property can be retrieved using the ->toArray method.

Change visibility of FrontMatter::$data array to protected

---

packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/src/Framework/Exceptions/BuildWarning.php
packages/framework/src/Support/BuildWarnings.php
packages/framework/tests/Feature/StaticSiteServiceTest.php
packages/framework/tests/Unit/BuildWarningsTest.php

Adds an experimental system for us to buffer warnings that don't usually warrant a site build to fail (though there is an option to do just that) but that we want to alert the user about.
- Added experimental system to buffer warnings that don't warrant a site build to fail.
- Add a helper to display where the warning took place. (Enabled when verbose)
- Add an option to make the site build fail when certain warnings occur
Here's how it looks now:
When output is set to verbose, it will display where the warning took place as it's not that helpful to say "hey here's a warning but we won't tell you where".
Exceptions can be enabled to get a full stack trace + exit with code 2.
To add a warning, use the `BuildWarnings::report` method. You can either pass a string, or a `BuildWarning` object …

Add build warning system

---

packages/framework/tests/Feature/TracksExecutionTimeTest.php

This covers an extreme edge case causing tests to very rarely fail. Since the time difference between starting and stopping the clock is about 0.00048 seconds, or less than half a millisecond, this means the clock can switchover to a new second during this time.
This means that about when running the test around 1400 times, there is a 50% chance of this to occur. Given the scale we run tests on this means this issue is likely to happen again. 
```math
0.5 = (0.99952)^n
ln(0.5) = n * ln(0.99952)
n = ln(0.5) / ln(0.99952) ≈ 1438.96
```
So this PR fixes this by checking the time diff instead of rounded equality.

Update test to account for time drift

---

packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/tests/Unit/Foundation/HyperlinkFormatHtmlPathTest.php

Updates the Hyde::formatLink helper to trim all index.html suffixes when using pretty URLs.
This means `Hyde::formatLink('foo/bar/index.html')` now returns `'foo/bar/'` instead of 'foo/bar/index.html'.
This makes it more in line with how both standard index and documentation pages were rewritten, providing a more consistent and broadly usable result.

Update Hyde::formatLink helper to trim all index.html suffixes when using pretty URLs

---

packages/framework/src/Console/Concerns/Command.php
packages/framework/src/Foundation/Kernel/Filesystem.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php

Originally there has been two reasons for now doing this:
1. Paths should almost always already be relative
2. Performance concerns due to increased operations
After actually measuring this, I can confidently state that concern two is no concern at all. Firstly, performance is not that big of a concern in a static site generator, and secondly: after benchmarking this, it's clear that the method is lightning fast in either case.
| Input string           | Avg time (before) | Avg time (after) |
|------------------------|-------------------|------------------|
| ''                     | 0.001ms           | 0.001ms          |
| 'foo'                  | 0.002ms           | 0.003ms          |
| Hyde::path('foo')      | 0.004ms           | 0.006ms          |
| Hyde::path(Hyde::path) | 0.003ms …

Refactor the Hyde::path() helper to normalize already absolute paths

---

.env.example
config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php

Since we have arguments for both the port and the host, it's weird we only have config options for the port. Well, now we have both.

Add configuration option for the realtime compiler server host

---

packages/framework/resources/views/components/breadcrumbs.blade.php
packages/framework/tests/Unit/BreadcrumbsComponentViewTest.php

Merges the span divider element into the list item. Now validates under https://validator.w3.org/nu/#textarea

Fix breadcrumbs component markup

---

packages/publications/src/PublicationService.php
packages/publications/src/PublicationsExtension.php
packages/publications/tests/Feature/PublicationServiceTest.php

Removes the deprecated `PublicationService::parsePublicationFile` method, so you would call `PublicationPage::parse($identifier)` instead. 
May break things on the `publications-feature` branch.
This is breaking because the called method does not accept identifiers ending with file extensions. This is intentionally not "fixed" as identifiers by definition cannot have file extensions, and this inconsistent leniency is unexpected since the core extension classes and the framework itself does not do this.
```php
- PublicationService::parsePublicationFile('test-publication/foo.md')
- PublicationService::parsePublicationFile('test-publication/foo')
+ PublicationPage::parse('test-publication/foo')
```

Inline and simplify publication parsing method

---

packages/framework/src/Console/Commands/ServeCommand.php

Fixes critical bug in https://github.com/hydephp/develop/pull/1132 where the command times out after 60 seconds, which is of course not desired at all.

Set the serve command process to run forever

---

packages/framework/src/Foundation/Concerns/HydeExtension.php
packages/framework/src/Foundation/Concerns/ManagesExtensions.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Foundation/Kernel/PageCollection.php
packages/framework/src/Foundation/Kernel/RouteCollection.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php
packages/framework/tests/Unit/ExtensionsUnitTest.php

This PR refactors the Extensions API so that its discovery handler methods are no longer static, and loaded extensions are now stored as singletons within the kernel container. This makes extensions much easier to test as state is cleared and methods are mockable. Resolves https://github.com/hydephp/develop/issues/1139.
This will break all existing extensions. It should be easy enough however, just remove the static keyword. As it currently stands, the getPageClasses method is still static. Also improves the extensions feature/unit tests.
Remove the `static` keyword from the discovery handler methods in your extension.
```php
class MyExtension extends HydeExtension()
{
- public static function discoverFiles(FileCollection $collection): void;
- public static function …
```

Refactor the Extensions API to use Kernel Singletons instead of static classes

---

packages/framework/src/Console/Commands/BuildRssFeedCommand.php
packages/framework/src/Console/Commands/BuildSearchCommand.php
packages/framework/src/Console/Commands/BuildSitemapCommand.php
packages/framework/src/Console/Commands/RebuildStaticPageCommand.php
packages/framework/src/Framework/Features/BuildTasks/BuildTask.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateBuildManifest.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateRssFeed.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateSearch.php
packages/framework/src/Framework/Features/BuildTasks/PostBuildTasks/GenerateSitemap.php
packages/framework/src/Framework/Services/BuildTaskService.php
packages/framework/tests/Feature/Services/BuildTaskServiceTest.php
packages/framework/tests/Unit/BuildTaskServiceUnitTest.php
packages/framework/tests/Unit/GenerateBuildManifestTest.php

Since build tasks are in a sense "micro commands," it is more semantic to have the handle method be the abstract method used to provide the task logic, and the run method be the one called by the service.
This requires an inversion of how the exit code is handled too, but I think it's more intuitive as it changes the child method to return a value instead of needing a class property for the exit code.
Targets https://github.com/hydephp/develop/pull/1152 and fixes https://github.com/hydephp/develop/issues/1158

Invert the run/handle methods of build tasks 

---

packages/framework/src/Pages/Concerns/UsesFlattenedOutputPaths.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/tests/Unit/DocumentationPageTest.php

Removes the UsesFlattenedOutputPaths trait, and the overall feature, as it breaks pages with the same name in different directories. Fixes https://github.com/hydephp/develop/issues/1164
This is unfortunately likely lead to URL breaks in built sites.

Breaking: Remove flattened output documentation paths

---

packages/framework/src/Framework/Features/Navigation/BaseNavigationMenu.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

This means that items in groups with the same name are not considered duplicate. Fixes https://github.com/hydephp/develop/issues/1169

Update duplicate navigation item filtering to include group prefix

---

config/docs.php
docs/creating-content/documentation-pages.md
packages/framework/config/docs.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/tests/Unit/DocumentationPageTest.php

Reverts hydephp/develop#1166 but reimplements it as a configurable feature

Reimplement flattened output documentation paths feature

---

packages/framework/src/Framework/Concerns/InteractsWithFrontMatter.php
packages/framework/src/Markdown/Models/FrontMatter.php
packages/framework/tests/Unit/FrontMatterModelTest.php

The get function was returning the entire object $this when it was called without a $key argument, instead of returning the entire data array. This caused confusion for users of the code, as the semantics were not consistent with what was expected.
To fix this issue, the function was modified to return the entire data array when it is called without a $key argument. Additionally, this change modifies the way that the `InteractsWithFrontMatter` trait interacts with the `FrontMatter` method, ensuring that the trait method complies with the contracted description in the implemented interface. This auxiliary change also ensures backwards compatibility for the $page->matter() methods.
This pull request fixes issue #1157.

Update FrontMatter::get method to return data array instead of $this

---

.github/workflows/end-to-end-testing.yml

Since we have a limited number of screenshots each month, this limits the usages for when we don't actually need them. This PR is internal as it only affects the monorepo.

Update end-to-end-testing workflow to only call Browserstack based on pull request labels

---

config/hyde.php
packages/framework/config/hyde.php

Fixes https://github.com/hydephp/develop/issues/1173. This is not breaking as the stubs just contain the default values.
Also adds a section for general advanced options to the Hyde config for things that are so obscure they don't need their own whole documented section.

Add "hidden" configuration options to the config stubs

---

packages/framework/src/Foundation/Providers/ViewServiceProvider.php
packages/framework/src/Publications/Views/Components/RelatedPublicationsComponent.php

This is the promised refactoring of the RelatedPublicationsComponent; it should be more readable and easily understandable than the original version. j
Sorry for the superfluous registration of the component in the wrong file. It tried to reset/undo the commit for this (which seems to have worked locally) but github refuses to honor it. So please undo this 1 line change after merging this PR.

Refactor RelatedPublicationsComponent

---

packages/framework/src/Foundation/Facades/Files.php
packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Framework/Services/BuildService.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/src/Support/Filesystem/MediaFile.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Feature/FileCollectionTest.php
packages/framework/tests/Feature/Support/MediaFileTest.php

In all honesty, MediaFile objects do not need to be auto-discovered at all, considering they are only ever used in the build loop. Since they are never further processed, that complexity is not warranted. Nor do they have any need to be cached. Fixes https://github.com/hydephp/develop/issues/1204

Aggressively simplify MediaFile/FileCollection discovery

---

packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Foundation/Kernel/PageCollection.php
packages/framework/src/Foundation/Kernel/RouteCollection.php
packages/framework/src/Framework/Exceptions/FileConflictException.php
packages/framework/src/Framework/Exceptions/FileNotFoundException.php
packages/framework/src/Framework/Exceptions/RouteNotFoundException.php
packages/framework/src/Framework/Exceptions/UnsupportedPageTypeException.php
packages/framework/src/Support/Filesystem/MediaFile.php
packages/framework/tests/Feature/FileCollectionTest.php
packages/framework/tests/Feature/PageCollectionTest.php
packages/framework/tests/Feature/RouteCollectionTest.php
packages/framework/tests/Feature/Support/MediaFileTest.php
packages/framework/tests/Unit/CustomExceptionsTest.php
packages/framework/tests/Unit/FileConflictExceptionTest.php
packages/framework/tests/Unit/RouteNotFoundExceptionTest.php
packages/realtime-compiler/tests/RealtimeCompilerTest.php

The whole reason we created these exceptions was to provide a normalized and consistent output. That disappears the moment we introduce complexity like this.
I also don't think messages like `"Could not get the content length of file [$this->path]"` is required when the stacktrace shows the message was thrown in a `getContentLength()` method. Since all exceptions are targeted at developers, we can count on the stacktraces to be visible.

Remove support for customizing the messages in custom exceptions

---

packages/framework/src/Foundation/Kernel/PageCollection.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Feature/SourceDirectoriesCanBeChangedTest.php

Broad level code polishing covering multiple concerns where a scoped finalization PR is impractical. As this is part of the sprint to prepare HydePHP 1.0 there are breaking changes here, and they are not all going to be documented as the BC promise has not yet kicked in.

Refactor DiscoveryService related code

---

packages/framework/src/Console/Commands/RebuildPageCommand.php
packages/framework/src/Console/ConsoleServiceProvider.php
packages/framework/tests/Feature/Commands/RebuildPageCommand.php

Only renames the command class, not the signature.

Rename RebuildStaticPageCommand class to RebuildPageCommand as all pages are static

---

packages/framework/src/Pages/MarkdownPost.php

Since the front matter data can differ in format, we should sort using the normalized DateTime object. By using the Unix timestamp we will always be able to sort using the proper order in time.

Update MarkdownPost::getLatestPosts helper to sort using the DateTime object timestamp

---

_pages/404.blade.php
packages/framework/resources/views/pages/404.blade.php
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/tests/Unit/BreadcrumbsComponentTest.php
packages/framework/tests/Unit/Foundation/HyperlinkFileHelperRelativeLinkTest.php

This fixes an edge case bug when using pretty URLs in a subdirectory where the index page was not properly resolved relatively.
So a link to 'index.html' when using pretty URLs is now actually relative, instead of linking to the webroot which breaks subdirectories and local browsing. Both `.` and `./` work, so I choose the latter as I think it looks better.

Update pretty relative index links to rewrite to `./` instead of `/`

---

RELEASE_NOTES.md
docs/getting-started/basic-architecture-concepts.md
packages/framework/src/Support/Models/RouteKey.php
packages/framework/tests/Unit/RouteKeyTest.php

Fixes https://github.com/hydephp/develop/issues/1240

Remove RouteKey normalization for dot notation support

---

RELEASE_NOTES.md
_ide_helper.php
packages/framework/src/Foundation/Concerns/ManagesViewData.php
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Support/Facades/Render.php
packages/framework/src/Support/Models/RenderData.php
packages/framework/tests/Feature/DarkmodeFeatureTest.php
packages/framework/tests/Feature/GlobalMetadataBagTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Feature/RenderHelperTest.php
packages/framework/tests/Unit/BreadcrumbsComponentTest.php
packages/framework/tests/Unit/Facades/RouteFacadeTest.php
packages/framework/tests/Unit/HydeFileHelpersTest.php
packages/framework/tests/Unit/NavItemIsCurrentHelperTest.php
packages/framework/tests/Unit/NavItemTest.php
packages/framework/tests/Unit/RouteTest.php
packages/framework/tests/Unit/Views/Components/LinkComponentTest.php
packages/framework/tests/Unit/Views/ScriptsComponentViewTest.php
packages/framework/tests/Unit/Views/StylesComponentViewTest.php
packages/testing/src/InteractsWithPages.php

This will hopefully be the last breaking change. The old accessors are present but deprecated and will be removed before v1.0-proper. I think the RC break is justified here as since the properties are not documented I don't think many people use it so the impact is low, and the naming issue is quite severe. These are legacy properties introduced before route keys were a thing.
- The global `$currentRoute` variable will be renamed to `$route` as "current" is implied
- The global `$currentRoute` variable will be renamed to `$routeKey` as "current" is implied, and it's not a page.
For this, the location of the actual shared variables (in the ViewData) class are also deprecated, and updated for the renames. Most of these changes should be easy to upgrade with search+replace in project files.

Breaking: Rename global properties

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

- Added a new `HydeKernel::currentPage()` method to return the page being rendered.
- Renamed global `$currentRoute` and `$currentPage` variables to `$route` and `$routeKey` respectively.
- Renamed `Render::getCurrentRoute()` to `Render::getRoute()` to match renamed property.
- Renamed `Render::getCurrentPage()` to `Render::getRouteKey()` to match renamed property.
This release candidate version contains a few deprecations, these will be removed before the final 1.0.0 release.
- Deprecate `RouteKey::normalize` method as it no longer performs any normalization.
- Deprecate `RenderData::getCurrentRoute()` as it is renamed to `getRoute()` to match renamed property.
- This change affects the `Render::getCurrentRoute()` and `Hyde::currentRoute()` facade methods.
- Deprecate …

HydePHP v1.0.0 - Release Candidate Two

---

RELEASE_NOTES.md
packages/framework/src/Markdown/Contracts/FrontMatter/PageSchema.php
packages/framework/src/Pages/Concerns/HydePage.php

This property requires information that is setup-dependent, and will work better through a runtime accessor. Since it is mainly related to blog posts, the schema option will be moved there.

Deprecate HydePage canonical url property

---

RELEASE_NOTES.md
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php

Makes HydePage::$title property readonly as it does not support being persisted

Make HydePage::$title property readonly

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

- Made the `HydePage::$title` property readonly
- `HydePage::$canonicalUrl`

HydePHP v1.0.0 - Release Candidate Three

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php
packages/framework/tests/Feature/GlobalMetadataBagTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php

This adds better IDE support, but changes no behaviour. It uses the same concatenation as in the docs header option.

Add default RSS feed description value to config stub

---

RELEASE_NOTES.md
packages/framework/resources/views/components/post/article.blade.php
packages/framework/src/Framework/Factories/HydePageDataFactory.php
packages/framework/src/Framework/Features/Metadata/PageMetadataBag.php
packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php
packages/framework/src/Markdown/Contracts/FrontMatter/PageSchema.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Unit/HydePageDataFactoryTest.php
packages/framework/tests/Unit/HydePageSerializableUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPostHelpersTest.php

The idea is that the internal data state should be as portable as possible. Having a canonicalUrl as part of the internal data structure breaks this portability as it is in many cases entirely dependent on the environment the data is used in. This means that it should not be part of the internal data structure, nor its serialized form. It's much better suited as a runtime accessor method. Thus, this PR removes the deprecated property, and replaces it with a new public method that uses the same logic ported from the page factory creator so the end result is still the same.

Remove deprecated `HydePage::$canonicalUrl` property

---

RELEASE_NOTES.md
config/hyde.php
docs/digging-deeper/customization.md
packages/framework/config/hyde.php
packages/framework/src/Facades/Features.php
packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/Commands/BuildRssFeedCommandTest.php
packages/framework/tests/Feature/GlobalMetadataBagTest.php
packages/framework/tests/Feature/MetadataTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php

I believe this to be the (or one of the) last breaking change as HydePHP enters GA in two days.
While **this is a breaking change**, the impact is very low. It's a really easy change, and I don't think that many people have changed this setting, and the BC has not fully kicked in yet, so I think the risk is acceptable.
```php
// Should the RSS feed be generated?
'generate_rss_feed' => true,
// What filename should the RSS file use?
'rss_filename' => 'feed.xml',
// The channel description.
'rss_description' =>  env('SITE_NAME', 'HydePHP').' RSS Feed',
```
```php
'rss' => [
// Should the RSS feed be generated?
'enabled' => true,
// What filename should the RSS file use?
'filename' => 'feed.xml',
// The channel description.
'description' => env('SITE_NAME', 'HydePHP').' RSS Feed',
],
``` …

Create new array-based RSS feed config structure

---

RELEASE_NOTES.md
packages/framework/src/Framework/Actions/CreatesNewPageSourceFile.php
packages/framework/tests/Feature/Actions/CreatesNewPageSourceFileTest.php

This method is removed as the save method now returns the path

Remove deprecated `CreatesNewPageSourceFile::getOutputPath` method

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

- Added new method `HydePage::getCanonicalUrl()` to replace deprecated `HydePage::$canonicalUrl` property.
- Added default RSS feed description value to the config stub in [#1253](https://github.com/hydephp/develop/pull/1253)
- Changed the RSS feed configuration structure to be an array of feed configurations in [#1258](https://github.com/hydephp/develop/pull/1258)
- Replaced option `hyde.generate_rss_feed` with `hyde.rss.enabled`
- Replaced option `hyde.rss_filename` with `hyde.rss.filename`
- Replaced option `hyde.rss_description` with `hyde.rss.description`
- Removed `RouteKey::normalize` method deprecated in v1.0.0-RC.2
- Removed `RenderData:.getCurrentPage` method deprecated in v1.0.0-RC.2
- Removed `RenderData:.getCurrentRoute` method deprecated in v1.0.0-RC.2
- Removed deprecated …

HydePHP v1.0.0 - Release Candidate Four

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/documentation-article.blade.php

This is needed when using the edit page link in the footer

Bugfix: Fix missing `justify-between` class on the documentation article header

---

SECURITY.md
packages/framework/SECURITY.md

Updates the security documents to include v1.0 General Availability, and to keep a consistent presentation.

Update supported versions in package security policies

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php
packages/framework/tests/Feature/MetadataViewTest.php

This was lost when moving to a version constant instead of Composer value. Thus I consider this to be a bugfix.

Prefix version for default meta generator value

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

- Removed IDE helpers for removed global variables from the IDE helper file. https://github.com/hydephp/develop/pull/1274
- Removed default values from Hyde facade method annotations. https://github.com/hydephp/develop/pull/1275
- Added missing version prefix to default generator meta tag value. https://github.com/hydephp/develop/pull/1272

HydePHP v1.0.0 - Release Candidate Six

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

- Added generics to the Hyde facade method annotations https://github.com/hydephp/develop/pull/1280
- Updated 404 page home link to use the index route instead of the site URL https://github.com/hydephp/develop/pull/1278
- Improved generic type usage in the RegisterFileLocations trait https://github.com/hydephp/develop/pull/1279
- Bumped HydeFront to v3.1 https://github.com/hydephp/develop/pull/1281

HydePHP v1.0.0 - Release Candidate Seven

---

RELEASE_NOTES.md
packages/framework/src/Support/ReadingTime.php
packages/framework/tests/Feature/ReadingTimeTest.php

Fixes https://github.com/hydephp/develop/issues/1286 by rounding up the `Stringable` results of the `getFormatted` method in the `ReadingTime` class.

Update ReadingTime to round up to one minute

---

RELEASE_NOTES.md
packages/framework/src/Console/ConsoleServiceProvider.php
packages/framework/tests/Unit/ConsoleServiceProviderUnitTest.php

Fixes https://github.com/hydephp/develop/issues/1127

Use "HydePHP" as the application logo when running without ANSI formatting

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

- General compatible code quality improvements https://github.com/hydephp/develop/pull/1284
- Removed test class references from main codebase https://github.com/hydephp/develop/pull/1287
- Fixed "ReadingTime calculation should never be under one minute" [#1286](https://github.com/hydephp/develop/issues/1286) in [#1285](https://github.com/hydephp/develop/pull/1285)
- Fixed "The HydeCLI list command logo should respect the --no-ansi setting" [#1127](https://github.com/hydephp/develop/issues/1127) in [#1288](https://github.com/hydephp/develop/pull/1288)

HydePHP v1.0.0 - Release Candidate Eight

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

We're thrilled to announce HydePHP v1.0.0, the first general availability release of the Laravel-based static site generator you've been waiting for! HydePHP allows you to build lightning-fast static websites with ease, using the familiar syntax and functionality of the Laravel framework.
HydePHP is a powerful static site generator that is built on top of Laravel, one of the most popular PHP frameworks out there. HydePHP's architecture and design principles allow for a flexible and intuitive development experience, making it a great choice for developers looking to create static websites quickly and efficiently.
This release marks the first stable version of HydePHP, with many exciting new features and improvements. Here are some of the highlights:
- Upgraded to Laravel 10 and requires …

HydePHP version v1.0.0

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Internal/LoadConfiguration.php
packages/framework/tests/Unit/LoadConfigurationTest.php

Updates the custom configuration loader to check for CLI flags in the server globals. This allows us to collect information very early on in the internal application lifecycle. It contains a flag check which fixes https://github.com/hydephp/develop/issues/1301

Check for config flags in server globals when loading the configuration

---

.github/workflows/continuous-integration.yml

Should stop this from randomly happening on Windows CI runs:

Update test matrix to explicitly set the Zip extension for PHP setup

---

packages/framework/src/Framework/Features/Documentation/SemanticDocumentationArticle.php
packages/framework/src/Framework/Views/Components/BreadcrumbsComponent.php
packages/framework/src/Framework/Views/Components/LinkComponent.php
packages/framework/src/Markdown/Processing/CodeblockFilepathProcessor.php
packages/framework/tests/Unit/BreadcrumbsComponentTest.php

This gives better type support and is easier to mock and work with.

Refactor to use the View facade instead of view function

---

RELEASE_NOTES.md
packages/framework/src/Framework/Factories/BlogPostDataFactory.php
packages/framework/src/Framework/Factories/HydePageDataFactory.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php

- **Changed:** Cleaned up PageDataFactory, NavigationDataFactory, and BlogPostDataFactory internals for better type safety
- **Removed:** Classes PageDataFactory, NavigationDataFactory, and BlogPostDataFactory no longer use the InteractsWithFrontMatter trait

Clean up page data factories

---

packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Console/Commands/VendorPublishCommand.php
packages/framework/src/Foundation/ConsoleKernel.php
packages/framework/src/Foundation/Internal/LoadConfiguration.php
packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Foundation/Kernel/PageCollection.php
packages/framework/src/Foundation/Kernel/RouteCollection.php
packages/framework/src/Framework/Actions/MarkdownFileParser.php
packages/framework/src/Framework/Actions/PreBuildTasks/CleanSiteDirectory.php
packages/framework/src/Framework/Concerns/Internal/ForwardsIlluminateFilesystem.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Blogging/Models/PostAuthor.php
packages/framework/src/Framework/Features/Documentation/DocumentationSearchPage.php
packages/framework/src/Framework/Features/Metadata/GlobalMetadataBag.php
packages/framework/src/Framework/Features/Navigation/BaseNavigationMenu.php
packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php
packages/framework/src/Framework/Services/MarkdownService.php
packages/framework/src/Pages/Concerns/BaseMarkdownPage.php
packages/framework/src/Support/BuildWarnings.php
packages/framework/src/Support/Models/RenderData.php
packages/framework/src/Support/Models/RouteList.php
packages/framework/src/helpers.php

Increases type coverage from 98.25% to 99.25% by adding type annotations, generics, and type casts. This not only improves type coverage but also provides better IDE support and may eliminate type related bugs.
| Class          | Start   | End    |
|----------------|---------|--------|
| PostAuthor     | 90.48%  | 100%   |
| ConsoleKernel  | 92.31%  | 100%   |
| BuildWarnings  | 91.67%  | 95.74% |
| PageCollection | 93.10%  | 96.55% |
| RssFeedGenerator | 93.33% | 99.35% |
| LoadConfiguration | 93.62% | 95.74% |
| DocumentationSearchPage | 93.33%	| 100% |
| **Total**      | 98.25%  | 99.25% |
Note that more classes than this are improved, I just haven't noted them in the table.

Improve type and IDE support

---

RELEASE_NOTES.md
packages/framework/resources/views/components/article-excerpt.blade.php

Description
-----------
This PR fixes the issue where the blog post feed component was not working on nested pages due to incorrect link formatting. The issue was caused by the use of the legacy style of links in `article-excerpt.blade.php`. The fix changes the link format to use `$post->getRoute`, which dynamically resolves relative paths.
The change was made by replacing the following code:
```blade
- <a href="posts/{{ Hyde::formatLink($post->identifier . '.html') }}"> Read post</a>
+ <a href="{{ $post->getRoute() }}" > Read post</a>
```
This PR has been tested and verified to resolve the issue. This fixes https://github.com/hydephp/develop/issues/1316

Update article excerpt component to use route helper method instead of legacy link formatter

---

RELEASE_NOTES.md
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/tests/Feature/HydePageTest.php

Adds a check in the navigation data factory so that a page like `_pages/posts/index.md` is considered internally as `_pages/posts.md`, as I think that closest matches the served site. This means this case is excluded from the default "hidden" setting for nested pages, but I think this better follows the principle of least astonishment since the page does not appear to be nested the same way, from a user's perspective. Fixes https://github.com/hydephp/develop/issues/1318

Fix nested index pages not showing in navigation 

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php

Fixes https://github.com/hydephp/develop/issues/1320

Update FeaturedImage class to only make API calls when not disabled

---

RELEASE_NOTES.md
packages/framework/resources/views/components/navigation/dropdown.blade.php

Fixes https://github.com/hydephp/develop/issues/1324, but requires a minor HydeFront bump.
Now looks like this:
But we probably need to offset it left: Edit: done,

Add "whitespace-nowrap" class to dropdown list item and align it right

---

RELEASE_NOTES.md
packages/framework/src/Framework/Services/AssetService.php
packages/framework/tests/Unit/AssetServiceUnitTest.php

Fixes https://github.com/hydephp/develop/issues/1326

Update AssetService::injectTailwindConfig method to handle missing config file gracefully

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php
packages/realtime-compiler/src/Http/DashboardController.php
packages/realtime-compiler/src/Routing/PageRouter.php

Adds a configuration option to view RealtimeCompiler pages without saving them to disk

Add RealtimeCompiler option to not store rendered pages to disk

---

packages/framework/tests/Unit/HydeConfigFilesAreMatchingTest.php

Fixes unrelated test failures in https://github.com/hydephp/framework/pull/572. We mostly have this check to catch any mistakes before merging config changes when developing in the monorepo.

Skip unit test when not running in the monorepo

---

packages/framework/tests/Feature/StaticSiteBuilderDocumentationModuleTest.php

Originally created to debug/repro/fix https://github.com/hydephp/develop/issues/1337, but now I'm just confused about this exception.

Add test for the documentation page compiler module

---

CHANGELOG.md
RELEASE_NOTES.md
package-lock.json
package.json
packages/framework/src/Foundation/HydeKernel.php

This release is the first since the official release of HydePHP 1.0.0. It contains a number of bug fixes and improvements, but no breaking changes as the project has reached general availability and adheres to the semantic versioning backwards compatibility promise.
- Added a RealtimeCompiler config option to disable rendered pages being stored to disk in https://github.com/hydephp/develop/pull/1334
- Documentation sidebars now support table of contents when using Setext headings in https://github.com/hydephp/develop/pull/1343
- Updated discovery exception message to include the causing exception message in https://github.com/hydephp/develop/pull/1305
- Cleaned up `PageDataFactory`, `NavigationDataFactory`, and `BlogPostDataFactory` internals for better type safety in …

HydePHP v1.1.0 - 2023-03-22

---

packages/framework/src/Foundation/Internal/LoadYamlConfiguration.php
packages/framework/tests/Feature/LoadYamlConfigurationTest.php

This PR is not breaking, as the actual class is marked as internal. As long as none of the features the class provides change (which they are not by this PR), BC is retained.
Edit: Okay so my plan was to refactor to use the Filesystem facade, but since this runs during the internal framework bootstrapping process, facades are not available yet. So this now just adds some more tests.

Clean up and refactor the internal LoadYamlConfiguration test

---

docs/digging-deeper/customization.md
packages/framework/src/Foundation/Internal/LoadYamlConfiguration.php
packages/framework/tests/Feature/LoadYamlConfigurationTest.php

If you are running `v1.2` or higher, you can also use namespaced configuration options in the YAML file.
This allows you to set the settings of **any** configuration file normally found in the `config` directory.
This feature is automatically enabled when you have a `hyde:` entry **first** in your `hyde.yml` file
```yaml
hyde:
name: HydePHP
docs:
sidebar:
header: "My Docs"
```
This would set the `name` setting in the `config/hyde.php` file, and the `sidebar.header` setting in the `config/docs.php` file.
Each top level key in the YAML file is treated as a namespace, and the settings are set in the corresponding configuration file.
You can of course use arrays like normal even in namespaced configuration.

Improve the Yaml configuration file feature to support multiple config namespaces

---

.github/workflows/split-monorepo.yml

The HydePHP organization no longer allows legacy personal access tokens. Instead, the new fine-grained tokens must be used, as they can be heavily scoped to only perform specific functions on specific repositories. This PR updates the monorepo splitting workflows to use the new added scoped token secret.

Update monorepo workflows to use new fine grained personal access tokens

---

RELEASE_NOTES.md
composer.json
composer.lock
packages/framework/src/Console/Commands/DebugCommand.php

This composer file has become widely different from the actual hyde/hyde composer file, so it doesn't make semantic sense for this project to be branded the same way as the hyde/hyde package. This change is not breaking, as the monorepo structure is not included in the HydePHP BC promise.

Change root monorepo Composer name to `hyde/monorepo`

---

RELEASE_NOTES.md
packages/hyde/tailwind.config.js

Creates `packages/hyde/tailwind.config.js`, and removes the Tailwind safelist from it as it is not required there. Fixes https://github.com/hydephp/develop/issues/1358

Split out monorepo Tailwind config from persisted hyde/hyde package files

---

RELEASE_NOTES.md
packages/framework/src/Markdown/Models/FrontMatter.php

Forgot to update the union type when was changed to return data instead of static

Fix type annotations in front matter class 

---

webpack.mix.js

This method seems more reliable than existing behaviour, and should provide a better fix for https://github.com/hydephp/hyde/issues/224 than https://github.com/hydephp/develop/pull/1375.

Invert Webpack asset synchronization flow

---

webpack.mix.js

Fixes accidental BC break in https://github.com/hydephp/develop/pull/1376. **This commit has not yet made it into a release as it was caught immediately.** The original issue still seems to be fixed by this.
> System testing CI caught a side effect I missed, the mix manifest ends up in a different location.
https://github.com/hydephp/develop/actions/runs/5047110370/jobs/9053512838
_Originally posted by @caendesilva in https://github.com/hydephp/develop/issues/1376#issuecomment-1557660162_

Revert Webpack public path to include media subdirectory

---

RELEASE_NOTES.md
packages/framework/src/Framework/Actions/CreatesNewMarkdownPostFile.php
packages/framework/src/Framework/Actions/CreatesNewPageSourceFile.php
packages/framework/tests/Feature/Actions/CreatesNewPageSourceFileTest.php
packages/framework/tests/Feature/Commands/MakePageCommandTest.php
packages/framework/tests/Feature/Commands/MakePostCommandTest.php
packages/framework/tests/Unit/CreatesNewMarkdownPostFileTest.php

**Main features:**
- Allows custom content to be added when calling the source file creator actions directly.
- Allows custom date to be setwhen calling the post creator action directly.
- Updates the post creator action to use a mockable time helper from `Illuminate\Carbon` to improve testing

Improve source file creator actions

---

RELEASE_NOTES.md
packages/realtime-compiler/src/Http/DashboardController.php

Marks the `DashboardController` class as internal, as it is not intended to be used outside of the package.
RFC: https://twitter.com/CodeWithCaen/status/1716145658426519821

Mark DashboardController as internal

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php
packages/realtime-compiler/src/Http/DashboardController.php

This moves the dashboard settings into an array. While this is a somewhat intrusive change, requiring user intervention due to the implicit deprecation, it helps make the configuration file cleaner by grouping semantically related elements. An added check makes sure to provide backwards compatibility with older configuration options.
The shortened editor/tips keys are not breaking, as they have not been released yet.
To upgrade, replace the following in `config/hyde.php`:
```php
'server' => [
// ...
'enabled' => env('SERVER_DASHBOARD', true),
],
```
With this:
```php
'server' => [
// ...
'dashboard' => [
'enabled' => env('SERVER_DASHBOARD', true),
],
],
```

Update realtime compiler dashboard configuration schema

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php

This method is quite complex due to it's many conditionals. Extracting helpers with describing names makes the code easier to read, maintain, and understand.

Break down complex helper method

---

packages/publications/src/Commands/ValidatePublicationTypesCommand.php

This method has high cyclomatic complexity. Extracting additional helper methods reduces the scope of method.

Break down complex command class helper method

---

.github/workflows/continuous-integration.yml
.github/workflows/smoke-tests.yml
.github/workflows/test-pull-requests.yml
packages/framework/.github/workflows/run-tests.yml

Realised we have been using the old version for a while (and thus not receiving statistics, as the old script uses the old CI server) This updates the script to the latest one.

Internal: Update test runner statistics server script version

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/tests/Unit/FeaturedImageUnitTest.php

Fixes an embarrassing bug in error output, that I missed due to PHPUnit (for some reason) using substring comparisons for testing exception messages.
This lead to the following:
File [Image at _media/foo does not exist] not found.
This uses the new custom message feature from https://github.com/hydephp/develop/pull/1398 so it instead looks like this:
Featured image [_media/default] not found.

Use a custom exception message when failing to get image size

---

RELEASE_NOTES.md
docs/creating-content/documentation-pages.md
packages/realtime-compiler/src/Routing/Router.php

Previously we required a site build to generate the documentation search index, leaving the realtime compiler to return a 404. This update automatically generates the index on each request.
I decided against caching because of how fast the generator is. The request time (which is asynchronous) is increased to `~160ms` instead of `~30ms` for the entire HydePHP documentation. Considering that this happens in the background, I find this an entirely acceptable tradeoff. 
Fixes https://github.com/hydephp/develop/issues/1404

Update realtime compiler to generate search indexes on demand

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Navigation/BaseNavigationMenu.php
packages/framework/tests/Feature/NavigationMenuTest.php

This means that the duplication filter will run based on the defined item priorities, giving config items precedence, fixing https://github.com/hydephp/develop/issues/1406

Update navigation menu generator to remove duplicates after sorting

---

RELEASE_NOTES.md
packages/framework/src/Framework/Factories/BlogPostDataFactory.php
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php

We throw an exception when an image without a source is specified, but we don't mention which file. Now we do.
```
// Old
No featured image source was found
// New
No featured image source was found in "_posts/my-new-post.md"
```

Update the featured image factory to specify the file causing an exception

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/PublishHomepageCommand.php
packages/framework/src/Facades/Filesystem.php
packages/framework/src/Foundation/Kernel/Filesystem.php
packages/framework/src/Framework/Actions/BladeMatterParser.php
packages/framework/src/Framework/Actions/PreBuildTasks/CleanSiteDirectory.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Metadata/MetadataBag.php
packages/framework/src/Framework/Features/Navigation/DropdownNavItem.php
packages/framework/src/Framework/Services/BuildTaskService.php

Brings up type coverage by another `~0.20%`

Improve type coverage

---

RELEASE_NOTES.md
packages/framework/src/Facades/Config.php
packages/framework/src/Framework/Features/Metadata/MetadataBag.php
packages/framework/tests/Feature/TypedConfigFacadeTest.php
packages/framework/tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php

General cleanups and improvements. Nothing breaking. Also brings our code coverage back up to 100%.

General code quality cleanups

---

packages/framework/src/Foundation/Internal/LoadConfiguration.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/tests/Unit/LoadConfigurationTest.php

Resolves https://github.com/hydephp/develop/pull/1408#pullrequestreview-1702819229

Add runtime configuration option for the `--no-api` build flag

---

RELEASE_NOTES.md
packages/framework/src/Markdown/Processing/ColoredBlockquotes.php
packages/framework/src/Markdown/Processing/ShortcodeProcessor.php
packages/framework/tests/Feature/ColoredBlockquoteShortcodesTest.php
packages/framework/tests/Feature/Services/Markdown/ShortcodeProcessorTest.php

Refactors the internal class to extract blockquote class names from the signature, instead of creating new anonymous classes. This is not breaking, as the class was marked internal for this very reason before the first stable release.

Refactor colored blockquote internals to extract class name from signature

---

CHANGELOG.md
RELEASE_NOTES.md
packages/framework/src/Foundation/HydeKernel.php
packages/hyde/composer.json

- Added support for setting custom content when calling source file creator actions directly in https://github.com/hydephp/develop/pull/1393
- Added support for setting a custom post date when calling post file creator action directly in https://github.com/hydephp/develop/pull/1393
- Added optional `FileNotFoundException` constructor parameter to set a custom exception message https://github.com/hydephp/develop/pull/1398
- Added a new helper method to the base `Command` class to ask for a string input from the user in https://github.com/hydephp/develop/pull/1416
- The realtime compiler dashboard is now interactive, and allows you to make edits to your project right from the browser https://github.com/hydephp/develop/pull/1392
- Realtime Compiler: The `DashboardController` class is now …

HydePHP v1.3.0 - 2023-10-30

---

packages/framework/README.md

Replaces a broken link with the same text as in the `hyde/hyde` readme.

Update Framework readme contribution section to match the Hyde package

---

packages/framework/src/Pages/DocumentationPage.php

This fixes a bug where the sidebar header brand is not clickable when setting the documentation page output path to `''`.

Unslash documentation page home route name

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/tests/Unit/NavigationDataFactoryUnitTest.php

Previously, documentation pages supported the following for setting navigation priorities in the config:
```php
'foo', // Gets priority 500
'bar', // Gets priority 501
'baz', // Gets priority 502
```
And the main navigation menu supported the following syntax:
```php
'foo' => 10,
'bar' => 50,
'baz' => 75,
```
This PR makes it so both menu types support both config syntaxes, and even a combination of both:
```php
'foo',        // Gets priority 500
'bar' => 100, // Gets priority 100
'baz',        // Gets priority 501
```

Improve navigation priority discovery to allow sidebars and main navigation to support both list and keyed config syntax

---

packages/realtime-compiler/src/Http/DashboardController.php

As the dashboard is not password-protected, and it can make changes to the file system, we block any requests that are not coming from the host machine. While we are clear in the documentation that the realtime compiler should only be used for local development, we still want to be extra careful in case someone forgets.

Update realtime compiler dashboard to block unsafe requests

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy-documentation-preview.yml
.github/workflows/smoke-tests.yml
.github/workflows/test-pull-requests.yml
packages/framework/.github/workflows/run-tests.yml
packages/testing/stubs/hyde-testing-workflow.stub

Now uses the same version as Laravel, instead of pinning to a hash.

Use dynamic PHP setup action version for test runners

---

RELEASE_NOTES.md
package.json
packages/hyde/package.json

Updates the `hyde/hyde` `package.json` to be a bit more minimalistic and only have the actually useful stuff. Inspired by https://github.com/laravel/laravel/blob/10.x/package.json.

Create slim package.json

---

packages/realtime-compiler/src/ConsoleOutput.php
packages/realtime-compiler/src/Http/DashboardController.php

Allows the dashboard to send messages to the new fancy console provided by https://github.com/hydephp/develop/pull/1444

Add dashboard hook to interact with fancy serve command output

---

packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/src/Foundation/Internal/LoadConfiguration.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php
packages/framework/tests/Unit/LoadConfigurationTest.php
packages/framework/tests/Unit/ServeCommandOptionsUnitTest.php
packages/realtime-compiler/bin/server.php
packages/realtime-compiler/src/ConsoleOutput.php
packages/realtime-compiler/src/Http/DashboardController.php
packages/realtime-compiler/tests/ConsoleOutputTest.php

Adds a few new options to the `php hyde serve` command to allow some settings to be specified with command-line options. This is done by creating environment variables passed through to the Symfony process, and which are then injected into the configuration repository by our custom runtime configuration loader originally used for Yaml configuration. This makes so that the options are fully integrated into the request lifecycle. Also cleans up some adjacent code.

Pass through settings to realtime compiler

---

packages/framework/src/Console/Commands/ServeCommand.php

Fixes a mistake in https://github.com/hydephp/develop/pull/1450

Fix command extending wrong base class

---

packages/realtime-compiler/resources/dashboard.blade.php
packages/realtime-compiler/src/Http/BaseController.php
packages/realtime-compiler/src/Http/DashboardController.php
packages/realtime-compiler/src/Routing/PageRouter.php

While we make it clear that the realtime compiler is only intended to be used for local development (as it uses the built in PHP server, which is not designed for public use, as per the manual), since it does allow access to the file system I felt it responsible to at least add some CSRF protection to the dashboard forms. Also extracts a base class while I'm at it.
I ran benchmarks, and adding the session has a negligible performance impact of about `2.5` seconds for `10 000` requests, and that's only for the dashboard page.

Add realtime compiler dashboard CSRF protection

---

docs/digging-deeper/extensions.md

Improves heading structure, and vastly expands on the realtime compiler documentation

Revamp extensions documentation

---

packages/realtime-compiler/src/ConsoleOutput.php

Makes this dashboard-agnostic.

Change internal realtime compiler console context handling

---

packages/realtime-compiler/README.md

This legacy beta version of the realtime compiler package has only been receiving security fixes. This PR marks the end of life for this version to the end of this year.

Legacy realtime compiler beta version reaches end of life 2023-12-31

---

config/hyde.php
packages/framework/config/hyde.php
packages/realtime-compiler/resources/live-edit.blade.php
packages/realtime-compiler/resources/live-edit.css
packages/realtime-compiler/resources/live-edit.js
packages/realtime-compiler/src/ConsoleOutput.php
packages/realtime-compiler/src/Http/LiveEditController.php
packages/realtime-compiler/src/Routing/PageRouter.php
packages/realtime-compiler/tests/RealtimeCompilerTest.php

The live edit feature allows you to quickly edit Markdown-based pages (posts, docs, and pages) directly in the browser.
To enter the live editor, simply double-click on the article you want to edit, and it will be replaced with a text editor.
When you're done, click the save button to save the changes to the page's source file.
The live editor supports the following keyboard shortcuts:
- `Ctrl + E` - Enter/Exit editor
- `Ctrl + S` - Save changes
- `esc` - Exit editor if active
The live editor can be disabled in the `config/hyde.php` file.
The live editor plugin code will not be saved to your static site.
```php
// filepath config/hyde.php
'server' => [
'live_edit' => env('SERVER_LIVE_EDIT', true),
],
```

Add a live edit feature to the realtime compiler

---

docs/architecture-concepts/extensions-api.md

The Extensions API a powerful interface designed for package developers who want to extend the functionality of HydePHP.
Using the API, you can hook directly into the HydePHP Kernel and extend sites with custom page types and new features.
This documentation page functions heavily through examples, so it's recommended that the sections are read in order.
Before creating your extension, it will certainly be helpful if you first become familiar with
the basic internal architecture of HydePHP, as well as how the auto-discovery system works,
so you can understand how your code works with the internals.
- [Core concepts overview](core-concepts)
- [Architecture concepts](architecture-concepts)
- [Autodiscovery](autodiscovery)
HydePHP being a static site generator, the Extensions API is centered …

Document the Extensions API

---

packages/realtime-compiler/resources/live-edit.blade.php
packages/realtime-compiler/resources/live-edit.js
packages/realtime-compiler/src/Http/LiveEditController.php

Updates the live edit feature to protect against overwriting content modified in other tabs/editors. This works by restoring the JavaScript form handler together with a hidden input for the source file hash as it is on the page load. The backend returns a 409 response when the supplied content hash does not match the current one. The frontend then catches the 409 response, prints a JavaScript alert to ask the user if they want to overwrite the page, if they select yes, then the request is send again with a force parameter.

Update live edit feature to protect against overwriting modified content

---

packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

Automatically include the index page in the documentation sidebar when it is the only page present. This ensures the sidebar is not empty for a single-page documentation site, providing a more user-friendly experience.

Add documentation index page to the sidebar when it's the only page

---

RELEASE_NOTES.md
config/docs.php
docs/creating-content/documentation-pages.md
packages/framework/config/docs.php
packages/framework/resources/views/components/docs/sidebar-footer-text.blade.php
packages/framework/resources/views/components/docs/sidebar.blade.php
packages/framework/tests/Feature/SidebarViewTest.php

Fixes https://github.com/hydephp/develop/issues/1474 by checking if the existing `docs.sidebar.footer` option is a string, and if so it replaces the default "Back to home" link  with that content. Like before, if the option is `false` the footer is not rendered at all.

Update configuration option for the documentation sidebar footer to allow custom Markdown to be specified

---

RELEASE_NOTES.md
docs/creating-content/documentation-pages.md
packages/framework/resources/views/components/docs/sidebar-items.blade.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

When using the automatic sidebar grouping feature (based on subdirectories), the titles of the groups are generated from the directory names. If these are not to your liking, for example if you need to use special characters, you can override them in the Docs configuration file. The array key is the directory name, and the value is the label.
Please note that this option is not added to the config file by default, as it's not a super common use case. No worries though, just add the following yourself!
```php
// Filepath: config/docs.php
'sidebar_group_labels' => [
'questions-and-answers' => 'Questions & Answers',
],
```

Add config option to customize automatic sidebar navigation group names

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Unit/ServeCommandOptionsUnitTest.php

```bash
php hyde serve --open
```

Add option to open site in the browser when starting the realtime compiler

---

packages/realtime-compiler/bin/server.php
packages/realtime-compiler/src/Concerns/InteractsWithLaravel.php

Improves the portability of the realtime compiler to better support running through the standalone executable.
Pulls changes from https://github.com/hydephp/realtime-compiler/pull/20

Improve portability of the realtime compiler

---

CHANGELOG.md
RELEASE_NOTES.md
packages/framework/src/Foundation/HydeKernel.php

- Adds a new fancy output for the realtime compiler serve command in https://github.com/hydephp/develop/pull/1444
- Added support for dot notation in the Yaml configuration files in https://github.com/hydephp/develop/pull/1478
- Added a config option to customize automatic sidebar navigation group names in https://github.com/hydephp/develop/pull/1481
- Added a new `hyde serve --open` option to automatically open the site in the browser in https://github.com/hydephp/develop/pull/1483
- The `docs.sidebar.footer` config option now accepts a Markdown string to replace the default footer in https://github.com/hydephp/develop/pull/1477
- Links in the `sitemap.xml` file are now relative when a site URL is not set, instead of using the default localhost URL in …

HydePHP v1.4.0 - 2023-12-11

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Kernel/Filesystem.php
packages/framework/src/Foundation/PharSupport.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php
packages/framework/tests/Feature/PharSupportTest.php
packages/realtime-compiler/src/Http/DashboardController.php

These will fix https://github.com/hydephp/cli/issues/49, as well as other probable compatibility issues in that repo.
Removes the requirement that the vendor package is `framework` and updates the resolver to handle other Hyde packages.
This should resolve a lot of the issues we're having with the standalone, due to Phar paths being formatted like `'H:\monorepo/phar://foo'`, when they should be unchanged (`'phar://foo'`)
Update dashboard to inject scripts directly from archive when running in Phar

Improve support for running HydePHP through the Phar archive

---

RELEASE_NOTES.md
packages/realtime-compiler/src/Http/DashboardController.php

Uses just the relative path, instead of the absolute one, partly because having the qualifier adds nothing since Hyde always only modifies files in the project, and partly to make it shorter to fit smaller consoles.

Shorten path printed to console when using dashboard to create a page

---

RELEASE_NOTES.md
packages/realtime-compiler/resources/dashboard.blade.php

Fixes https://github.com/hydephp/realtime-compiler/issues/21
**Before:**
**After:**

Add info banners when dashboard content is empty

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/BuildRssFeedCommand.php
packages/framework/src/Console/Commands/BuildSearchCommand.php
packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/src/Console/Commands/BuildSitemapCommand.php
packages/framework/src/Console/Commands/ChangeSourceDirectoryCommand.php
packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/src/Console/Commands/MakePageCommand.php
packages/framework/src/Console/Commands/MakePostCommand.php
packages/framework/src/Console/Commands/PackageDiscoverCommand.php
packages/framework/src/Console/Commands/PublishConfigsCommand.php
packages/framework/src/Console/Commands/PublishHomepageCommand.php
packages/framework/src/Console/Commands/RebuildPageCommand.php
packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Console/Commands/ValidateCommand.php
packages/framework/src/Foundation/Kernel/RouteCollection.php
packages/framework/src/Framework/Actions/StaticPageBuilder.php
packages/framework/src/Framework/Concerns/InteractsWithFrontMatter.php
packages/framework/src/Framework/Features/Blogging/Models/PostAuthor.php
packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/src/Commands/MakePublicationTypeCommand.php
packages/publications/src/Commands/SeedPublicationCommand.php
packages/publications/src/Commands/ValidatePublicationTypesCommand.php
packages/publications/src/Commands/ValidatePublicationsCommand.php

Made this crude script to help, posting here in case of me wanting it in the future again.
```php
<?php
// Create a list of all class descriptions (the first line in a PHPDoc) in the Framework package.
require_once __DIR__.'/../vendor/autoload.php';
$files = (new \Illuminate\Filesystem\Filesystem())->allFiles(__DIR__.'/../packages/framework/src');
$html = '';
foreach ($files as $file) {
$source = file_get_contents($file->getPathname());
// If file is not a class, skip it.
if (!str_contains($source, 'class ')) {
continue;
}
$reflection = new ReflectionClass('Hyde\\'.str_replace('/', '\\', substr($file->getPathname(), strlen(__DIR__.'/../packages/framework/src/'), -4)));
$doc = $reflection->getDocComment();
if (empty($doc)) {
$commentText = '<span style="color: red">Missing PHPDoc</span>'; …
```

Clean up and normalize class description comments

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/ChangeSourceDirectoryCommand.php
packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/src/Console/Commands/PublishHomepageCommand.php
packages/framework/src/Console/Commands/PublishViewsCommand.php
packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/src/Console/Commands/ValidateCommand.php

Crude script to get a good overview of all of these
```php
<?php
// Create a list of all console command descriptions in the Framework package.
require_once __DIR__.'/../vendor/autoload.php';
$html = '';
$classes = (new \Illuminate\Filesystem\Filesystem())->allFiles(__DIR__.'/../packages/framework/src/Console/Commands');
foreach ($classes as $class) {
$source = file_get_contents($class->getPathname());
$description = 'No description found';
foreach (explode("\n", $source) as $line) {
if (str_contains($line, 'protected $description')) {
$description = trim(str_replace(['protected $description = ', ';', "'"], '', $line));
break;
}
}
$name = str_replace('.php', '', $class->getFilename());
$path = str_replace('\\', '/', substr($class->getPathname(), …
```

Normalize console command descriptions

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/documentation-article.blade.php
packages/framework/tests/Feature/Services/HydeSmartDocsTest.php

- This also makes it more inline with the `$article` used by blog posts.
- Allows for them to be passed from a model class, for example.

Improve the semantic documentation article Blade view

---

RELEASE_NOTES.md
packages/realtime-compiler/resources/dashboard.blade.php

Realtime compiler dashboard bugfix, where `.ico` files had their binary data printed instead of being previewed.

Fix icons not being considered as images by dashboard viewer

---

RELEASE_NOTES.md
packages/hydefront/sass/docs/heading-permalinks.scss

Should fix a bug where crawlers like Google Bot thinks this is a part of the heading, leading to it being visible in search results.
Adding `display: hidden` would likely solve this, but that breaks the transition. Using visibility modifiers should work the same, but retain the existing visual behaviour.

Make heading permalink hashes hidden when not hovered

---

RELEASE_NOTES.md
packages/hydefront/sass/markdown/codeblocks.scss

Removes the HydeFront style specified to make `inline code` tags render as `inline-block`, instead letting them be the default `inline` display.
This fixes the visual overflow bug in https://github.com/hydephp/hydefront/issues/65, and improves line height compatibility as the code background now fits to the text instead of taking up the full line height. This also desirably removes the extra background above the text.

Remove inline block display from inline code elements

---

RELEASE_NOTES.md
packages/realtime-compiler/resources/dashboard.blade.php
packages/realtime-compiler/src/Http/DashboardController.php

Merges https://github.com/hydephp/realtime-compiler/pull/24 into hydephp/develop

Visual dashboard bugfixes

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php

Since I've gotten a few people wondering about changing the extensions, I figure we should include it in the default config. See https://github.com/hydephp/develop/pull/105 for the PR that implemented this "hidden" option.

Add media extensions option to default config

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/src/Console/Commands/RebuildPageCommand.php
packages/framework/src/Framework/Actions/PreBuildTasks/TransferMediaAssets.php
packages/framework/src/Framework/Services/BuildService.php
packages/framework/src/Framework/Services/BuildTaskService.php
packages/framework/tests/Unit/BuildTaskServiceUnitTest.php
packages/framework/tests/Unit/RelativeLinksAcrossPagesRetainsIntegrityTest.php

Changes have been visually tested to ensure console output state is not changed.
<details>
<summary>Click to show</summary>
</details>

Refactor media asset transferring to a build task

---

RELEASE_NOTES.md
packages/framework/src/Framework/Services/BuildService.php

This method will be replaced by a build task in v2.0. See https://github.com/hydephp/develop/pull/1536
Drafting until implementation is made for the v2 branch, at which point the release notes for this branch will be updated.

Deprecate `BuildService::transferMediaAssets()`

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/tests/Unit/NavItemTest.php

Part of https://github.com/hydephp/develop/pull/1538 and allows for deferring the route link evaluation instead of forcing it at construction time. This has the side effect that the destination method now may return a route object instead of string. This targets v2.

Update NavItem class to support deferring route resolves

---

.github/workflows/deploy-documentation-preview.yml

Moves to a faster deployment server than GitHub Pages. Paired with using the runner PHP, and the fact that deployments are instant, we now get previews live in about 10 seconds, instead of a minute, massively reducing the friction of deployment previews.

Internal: Update monorepo documentation previews to use the new server

---

RELEASE_NOTES.md
docs/digging-deeper/helpers.md
packages/framework/src/Support/Includes.php
packages/framework/tests/Feature/IncludesFacadeTest.php

Adds a new helper to the `Includes` facad: to include raw HTML contents.

Add `Includes::html()` helper

---

docs/digging-deeper/helpers.md

Merges the examples that have repeated content to be more concise

Simplify the includes facade documentation

---

docs/advanced-features/build-tasks.md
docs/advanced-features/in-memory-pages.md
docs/architecture-concepts/architecture-concepts.md
docs/architecture-concepts/autodiscovery.md
docs/architecture-concepts/extensions-api.md
docs/architecture-concepts/page-models.md
docs/architecture-concepts/the-hydekernel.md
docs/creating-content/blog-posts.md
docs/creating-content/compile-and-deploy.md
docs/creating-content/documentation-pages.md
docs/creating-content/managing-assets.md
docs/creating-content/static-pages.md
docs/digging-deeper/advanced-customization.md
docs/digging-deeper/advanced-markdown.md
docs/digging-deeper/collections.md
docs/digging-deeper/helpers.md
docs/digging-deeper/navigation.md
docs/digging-deeper/troubleshooting.md
docs/digging-deeper/updating-hyde.md
docs/getting-started/console-commands.md
docs/getting-started/core-concepts.md
docs/getting-started/front-matter.md
docs/getting-started/quickstart.md
monorepo/scripts/docs/MarkdownFormatter.php

Normalizes heading two levels to be title case. Not sure if I prefer it, but at least it is consistent now.

Normalize documentation heading level formatting

---

RELEASE_NOTES.md
packages/framework/src/Framework/Actions/ConvertsMarkdownToPlainText.php
packages/framework/tests/Feature/Actions/ConvertsMarkdownToPlainTextTest.php

This is especially helpful if there are HTML tags that we stripped

Update Markdown to plaintext formatter to trim whitespace

---

CHANGELOG.md
RELEASE_NOTES.md
packages/framework/src/Foundation/HydeKernel.php
packages/hyde/composer.json

This release experiments some changes into how releases are handled to clarify the patch versioning of distributed packages compared to the monorepo source versioning.
In short: We are now experimenting with rolling patch releases, where patches are released as soon as they're ready, leading to faster rollout of bugfixes. This means that the patch version discrepancy between the monorepo and the distributed packages will be increased, but hopefully the end results will still be clearer, thanks to the second related change: Prefixing the subpackage changes in this changelog with the package name. If there is no prefix, the change applies to the core package or the monorepo.
All this to say, please keep in mind that when the monorepo gets a new minor version, the prefixed changes may …

HydePHP v1.5.0 - 2024-02-13

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/documentation-article.blade.php
packages/framework/src/Framework/Features/Documentation/DocumentationSearchPage.php
packages/framework/tests/Feature/DocumentationSearchPageTest.php

This is the most elegant solution I have been able to come up with for reusing the base documentation layout for search pages.
Before this change, the following empty HTML is added to the full page search page:
```html
<header id="document-header" class="flex items-center flex-wrap justify-between prose-h1:mb-3">
</header>
<section id="document-main-content" itemprop="articleBody">
</section>
<footer id="document-footer" class="flex items-center flex-wrap mt-8 prose-p:my-3 justify-between text-[90%]">
</footer>
```
This is of course not very semantic. But now, we can set the article to false, and this won't render.

[2.x] Add conditional semantic documentation article rendering

---

RELEASE_NOTES.md
packages/framework/resources/views/layouts/head.blade.php

Adds a `@head` stack to the `head.blade.php` component. My original plan was to move the existing meta stack, but this makes more sense and is more compatible. It allows code to be pushed to just before the end of the `head` component, just like in the scripts component.

Add a `@head` stack to the `head.blade.php` component

---

packages/framework/tests/Unit/RelativeLinksAcrossPagesRetainsIntegrityTest.php

We don't need a complex service mock when all we want to do is to run the build loop

Refactor unit test to replace complex mock with inlined build loop

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Features/Navigation/GeneratesDocumentationSidebarMenu.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Unit/HydePageSerializableUnitTest.php
packages/framework/tests/Unit/Pages/DocumentationPageUnitTest.php

It's kinda weird that we've been using `'other'` as a sort of pseudo-null state. It only makes sense for the group to be other when there are other groups, so that should be handled in the frontend Blade, thus we instead now null coalesce to `'Other'` when creating the group title.
This is breaking and targets V2 (specifically https://github.com/hydephp/develop/pull/1568)

[2.x] Change default DocumentationPage group to be `null` instead of `'other'`

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Navigation/GeneratesDocumentationSidebarMenu.php
packages/framework/src/Framework/Features/Navigation/GeneratesMainNavigationMenu.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

This targets HydePHP v2.x via https://github.com/hydephp/develop/pull/1568
> I realized something, do we actually want to remove duplicate items? What's really the point of that? If two pages have the same label the user might be doing something wrong, so should we try to obscure that by hiding one of them? Better to have visibility so the user can find the issue and manually hide the page they don't want,
_Originally posted by @caendesilva in https://github.com/hydephp/develop/issues/1568#issuecomment-1952387747_

[2.x] Remove duplicate navigation item filtering

---

packages/framework/resources/views/components/docs/sidebar-item.blade.php
packages/framework/resources/views/components/navigation/navigation-link.blade.php
packages/framework/src/Framework/Features/Navigation/GeneratesDocumentationSidebarMenu.php
packages/framework/src/Framework/Features/Navigation/GeneratesMainNavigationMenu.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/NavItemTest.php

This is part of HydePHP v2.x via https://github.com/hydephp/develop/pull/1568
A **breaking** change here is that the NavItem properties are no longer public. Instead they must be used through (already existing) accessors. While this adds extra boilerplate and inconvenience, it also allows us to open up the class data to being edited, the reason we protect the properties is so that we can control the data being added for a consistent and predictable state.
**How to upgrade:**
Simply replace any usage where you manually called a property with its accessor. (see the [file diff](https://github.com/hydephp/develop/pull/1574/files) for an example)
```php
use Hyde\Framework\Features\Navigation\NavItem;
$item = new NavItem();
$item->destination => $item->getDestination(); 
$item->label => …
```

[2.x] Change NavItem class API to be fluent instead of readonly

---

packages/framework/src/Framework/Features/Navigation/GeneratesDocumentationSidebarMenu.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Unit/NavItemTest.php

This targets v2.x via https://github.com/hydephp/develop/pull/1568 and picks up the idea behind https://github.com/hydephp/develop/pull/1575
This PR makes improvements to how navigation group labels are generated
<s>This PR makes improvements to how navigation item labels are generated. The biggest change which could be breaking is that all labels are now formatted. So if you create a navigation item with the label "foo" it will now be normalized to "Foo". This may be opinionated, but considering that we do the same for page titles, why should this be different?</s>

[2.x] Improved navigation group label generation

---

packages/framework/src/Framework/Features/Navigation/BaseMenuGenerator.php
packages/framework/src/Framework/Features/Navigation/GeneratesDocumentationSidebarMenu.php
packages/framework/src/Framework/Features/Navigation/GeneratesMainNavigationMenu.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php

Targets v2.x via https://github.com/hydephp/develop/pull/1568 and refactors the new generator to be deterministic and reduces overlapping code with the sidebar generator.

[2.x] Refactor navigation menu generators

---

packages/framework/src/Foundation/Providers/NavigationServiceProvider.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Features/Navigation/MainNavigationMenu.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Feature/NavigationManagerTest.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Feature/SidebarViewTest.php
packages/framework/tests/Unit/NavigationMenuUnitTest.php
packages/framework/tests/Unit/Views/NavigationBrandViewTest.php

Targets v2.x via https://github.com/hydephp/develop/pull/1568
See https://github.com/hydephp/develop/pull/1568#pullrequestreview-1895565140

[2.x] Split out base navigation menu class from main menu class

---

config/docs.php
docs/creating-content/documentation-pages.md
docs/digging-deeper/customization.md
docs/digging-deeper/navigation.md
packages/framework/config/docs.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/NavigationDataFactoryUnitTest.php

This changes the configuration option `docs.sidebar_order` to `docs.sidebar.order` in order to normalize the configuration API. It targets HydePHP v2.x via https://github.com/hydephp/develop/pull/1568.
Move the `sidebar_order` option's array in the `config/docs.php` file into the `sidebar` array in the same file.
```php
return [
'sidebar' => [
// ...
],
'sidebar_order' => [
'readme',
'installation',
'getting-started',
],
];
```
```php
return [
'sidebar' => [
// ...
'order' => [
'readme',
'installation',
'getting-started',
],
],
];
```

[2.x] Breaking: Change configuration option `docs.sidebar_order` to `docs.sidebar.order`

---

config/docs.php
docs/creating-content/documentation-pages.md
packages/framework/config/docs.php
packages/framework/resources/views/components/docs/sidebar-item.blade.php
packages/framework/src/Framework/Actions/GeneratesTableOfContents.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/tests/Feature/MarkdownServiceTest.php
packages/framework/tests/Unit/DocumentationPageTest.php

This changes the configuration option `docs.table_of_contents` to `docs.sidebar.table_of_contents` in order to normalize the configuration API. It targets HydePHP v2.x via https://github.com/hydephp/develop/pull/1568.
Move the `table_of_contents` option's array in the `config/docs.php` file into the `sidebar` array in the same file.
```php
return [
'sidebar' => [
// ...
],
'table_of_contents' => [
'enabled' => true,
'min_heading_level' => 2,
'max_heading_level' => 4,
],
];
```
```php
return [
'sidebar' => [
// ...
'table_of_contents' => [
'enabled' => true,
'min_heading_level' => 2,
'max_heading_level' => 4,
],
],
];
```

[2.x] Breaking: Change configuration option `docs.table_of_contents` to `docs.sidebar.table_of_contents`

---

docs/creating-content/documentation-pages.md

I can't find any other references to this option in the codebase or on GitHub code search, so I'm assuming it's some kind of legacy layover. Since it's not supported, this removes it from the docs.
'smooth_page_scrolling' => true, // Removed this from the table of contents example

Remove old smooth page scrolling config entry from documentation

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Unit/NavigationDataFactoryUnitTest.php

Further normalizes the configuration API. Targets https://github.com/hydephp/develop/pull/1568

[2.x] Support setting sidebar labels and visibility in docs config

---

.idea/php-test-framework.xml
packages/framework/tests/Feature/Views/SidebarBrandViewTest.php
packages/testing/src/Support/TestView.php

Adds some testing helpers and a new test. This PR is considered internal since it only affects the test suite and no public code.

Improve and add more view tests

---

RELEASE_NOTES.md
docs/digging-deeper/helpers.md
packages/framework/src/helpers.php
packages/framework/tests/Feature/HelpersTest.php

Adds helper function documentation and adds a few new global helper functions:
- Add a global `asset()` helper function
- Add a global `route()` helper function
- Add a global `url()` helper function
Design notes:
I debated weather these functions should be global or under the Hyde function namespace. I think making them global is the best. For the majority of users, this will be the most convenient, and for a small subset of users where there are conflicts (such as including Hyde in a Laravel application (which is not "officially" supported)), we can add a constant to disable these functions in case of function registration race conditions. TLDR: I think the small conflict risk is worth the major convenience of global functions. 
Compatibility mode:
To disable the new global functions, …

Improved helper functions

---

RELEASE_NOTES.md
packages/realtime-compiler/resources/dashboard.blade.php

Fixes https://github.com/hydephp/realtime-compiler/issues/25

Make the dashboard table properly responsive

---

packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php

Makes so that the generator always place navigation menu items in dropdowns when set in front matter, regardless of subdirectory group config.

[2.x] Always place navigation menu items in dropdowns when set in front matter

---

packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php

Extracts constants for the default priorities used for navigation menu design.
```php
NavigationMenu::DEFAULT = 500
NavigationMenu::LAST = 999
``` 
For example, the following is not very clear: (What does 999 mean and why do we use it?
```php
$priority ?? 999
``` 
But here, with the constant it's clear that we are falling back to putting the item last in the menu.
```php
$priority ?? NavigationMenu::LAST
``` 
It also makes things like this clearer
```php
$priority = NavigationMenu::LAST + 1
``` 
And a good IDE also shows the underlying integer values of the constants.

[2.x] Create positioning priority constants in the navigation menu class

---

packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/DocumentationSidebarUnitTest.php
packages/framework/tests/Unit/NavItemIsCurrentHelperTest.php
packages/framework/tests/Unit/NavItemTest.php

Major/breaking changes:
- Rename dropdown method to forGroup
- Merge fromRoute method into forRoute
- The destination value is now always null for parents with children

[2.x] Refactor NavItem class

---

packages/framework/resources/views/components/docs/sidebar-item.blade.php
packages/framework/resources/views/components/navigation/navigation-link.blade.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/NavItemIsActiveHelperTest.php
packages/framework/tests/Unit/NavItemTest.php

**Makes some breaking changes to the NavItem class.**
Since the destination property in v2 is normalized to always be a route it no longer makes sense to have a divergent name for it.
While the method is implemented by using the `currentRoute` helper, the actual end usage is to compare active state, so it makes more sense for this to use that in the name.
Renames `getGroup()` to `getGroupIdentifier()` to clarify the purpose of the method.
Renames `getLink()` to `getUrl()` for clarity on what the method returns.

[2.x] Rename NavItem fields to normalize its API

---

packages/framework/tests/Unit/Views/NavigationMenuViewTest.php

This is internal as it does not affect any package code, just tests.

Add more view tests for the navigation menu

---

packages/framework/tests/Unit/Views/NavigationHtmlLayoutsTest.php

Adds another test for https://github.com/hydephp/develop/pull/1568. This might be slightly overkill, but considering how important these features are, it's nice to have high level visual-style tests that can signal smoke before end-to-end testing kicks in (as that is painfully slow).

Create HTML tests for the navigation layouts 

---

packages/framework/tests/Unit/HtmlTestingSupportMetaTest.php
packages/testing/src/Support/HtmlTesting/DumpsDocumentState.php
packages/testing/src/Support/HtmlTesting/HtmlTestingAssertions.php
packages/testing/src/Support/HtmlTesting/TestableHtmlDocument.php
packages/testing/src/Support/HtmlTesting/TestableHtmlElement.php

Accidentally creates a pretty great HTML to AST parser.
See static export at https://git.desilva.se/random/abstract-syntax-tree-node-inspection-dump.html

Internal: Create new HTML testing framework

---

SECURITY.md
packages/framework/SECURITY.md
packages/hydefront/README.md
packages/realtime-compiler/README.md

While HydePHP v2.x is still some time away, HydePHP v1.x should be supported for a long time, hence this PR officially gives it an LTS status.

Designate HydePHP v1.x as LTS

---

RELEASE_NOTES.md
packages/framework/resources/views/components/docs/search-widget.blade.php
packages/framework/resources/views/pages/documentation-search.blade.php

This breaking PR renames some HTML identifiers that are using camelCase instead of kebab-case.
Upgrade path:
If you have used any of the following selectors in custom code you wrote yourself, you will need to update to use the new changed IDs.
- Rename HTML ID `#searchMenu` to `#search-menu`
- Rename HTML ID `#searchMenuButton` to `#search-menu-button`
- Rename HTML ID `#searchMenuButtonMobile` to `#search-menu-button-mobile`

[2.x] Normalize navigation HTML ID naming

---

RELEASE_NOTES.md
config/hyde.php
docs/digging-deeper/navigation.md
packages/framework/config/hyde.php
packages/framework/resources/views/components/docs/sidebar-items.blade.php
packages/framework/resources/views/layouts/navigation.blade.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Features/Navigation/GroupedNavigationItem.php
packages/framework/src/Framework/Features/Navigation/NavGroupItem.php
packages/framework/src/Framework/Features/Navigation/NavigationItem.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/DocumentationSidebarUnitTest.php
packages/framework/tests/Unit/GroupedNavigationItemTest.php
packages/framework/tests/Unit/NavGroupItemTest.php
packages/framework/tests/Unit/NavigationItemIsActiveHelperTest.php
packages/framework/tests/Unit/NavigationItemTest.php
packages/framework/tests/Unit/NavigationMenuUnitTest.php
packages/framework/tests/Unit/Views/NavigationLinkViewTest.php

Renames the NavItem and NavItemGroup classes to not be abbreviated. Sure, the NavItem naming is very broadly understood and there is a balance between verboseness and conciseness, but these are the only two abbreviated classes in all of HydePHP and I think the consistency weights in most here. 
Targets https://github.com/hydephp/develop/pull/1568

[2.x] Expand abbreviated navigation item class names

---

.github/workflows/smoke-tests.yml
.github/workflows/static-analysis.yml

We could probably verify things using the runs api `https://api.github.com/repos/hydephp/develop/actions/runs/<run_id>`, but for now, skipping them seems easiest

Internal: Update continuous integration server integrations to better handle forks

---

composer.lock

While Laravel Zero 11 is not out yet, at least this gets us a bit closer on the way to be up to date with our dependencies.

Bump Composer dependencies

---

packages/framework/resources/views/components/docs/sidebar-items.blade.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/DocumentationSidebarGetActiveGroupUnitTest.php
packages/framework/tests/Unit/DocumentationSidebarUnitTest.php

Targets https://github.com/hydephp/develop/pull/1568

[2.x] Simplify navigation item group state handling to be deterministic

---

packages/framework/src/Framework/Features/Navigation/NavigationItem.php
packages/framework/tests/Unit/NavigationItemTest.php

Targets https://github.com/hydephp/develop/pull/1568
Since null is not allowed, we needed to coalesce to an empty string. This makes no sense from a practical usability perspective: What's the point of a link in the menu that you can't click because there is no label to click? It makes more sense to fall back to the link to make it usable, and give a nudge to the developer that they may want to change it into something more visually pleasing.

[2.x] Create better fallbacks when not supplying a navigation item label

---

packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/src/Framework/Features/Navigation/NavigationElement.php
packages/framework/src/Framework/Features/Navigation/NavigationGroup.php
packages/framework/src/Framework/Features/Navigation/NavigationItem.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php
packages/framework/tests/Unit/DocumentationSidebarGetActiveGroupUnitTest.php
packages/framework/tests/Unit/NavigationGroupTest.php
packages/framework/tests/Unit/NavigationItemTest.php

Targets https://github.com/hydephp/develop/pull/1568.
> Do we actually need this? We should just care if it's physically stored in a group. Adding the group key here doesn't magically make it appear in the group, it needs to be added to the group's items array, so why should we care about the key here?

[2.x] Remove the group property from the navigation item class

---

RELEASE_NOTES.md
config/hyde.php
docs/creating-content/documentation-pages.md
packages/framework/config/hyde.php
packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/src/Facades/Features.php
packages/framework/src/Foundation/Concerns/Feature.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Framework/Services/ValidationService.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/ConfigurableFeaturesTest.php
packages/framework/tests/Feature/DarkmodeFeatureTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Unit/ConfigFileTest.php
packages/framework/tests/Unit/ConfigurableFeaturesUnitTest.php
packages/testing/src/ResetsApplication.php

Follow up to https://github.com/hydephp/develop/pull/1647. Contains a highly breaking config change in c5484800f76f135a1269e53147fd247a9384b542

[2.x] Refactor features class to simplify it and extract an enum

---

RELEASE_NOTES.md
config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/src/Enums/Feature.php
packages/framework/src/Facades/Features.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Framework/Concerns/Internal/MockableFeatures.php
packages/framework/src/Framework/Services/ValidationService.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/ConfigurableFeaturesTest.php
packages/framework/tests/Feature/DarkmodeFeatureTest.php
packages/framework/tests/Feature/HydeKernelTest.php

Cherry picks some changes from https://github.com/hydephp/develop/pull/1647 and https://github.com/hydephp/develop/pull/1649 in order to make the v2 upgrade path smoother. See https://twitter.com/CodeWithCaen/status/1777647925939593341
To upgrade to use the enum cases instead of the now deprecated static features methods, simply replace the following usages:
If you are using PhpStorm, you can follow these steps to do it automatically

Introduce a new Feature enum to improve the Features facade

---

RELEASE_NOTES.md
packages/framework/src/Framework/Actions/PostBuildTasks/GenerateRssFeed.php
packages/framework/src/Framework/Actions/PostBuildTasks/GenerateSitemap.php

Fixes a bug where the sitemap and RSS feed generator commands did not work when the `_site/` directory was not present, and adds some cleanups to the commands.

Fix issues with the sitemap and RSS feed generator commands

---

RELEASE_NOTES.md
docs/advanced-features/build-tasks.md
packages/framework/src/Framework/Features/BuildTasks/BuildTask.php
packages/framework/src/Framework/Features/BuildTasks/BuildTaskSkippedException.php
packages/framework/tests/Unit/BuildTaskSkippedExceptionTest.php
packages/framework/tests/Unit/BuildTaskUnitTest.php

Designed to match the exception formatting but with less scary output
```php
if (blank(Hyde::url()) || str_starts_with(Hyde::url(), 'http://localhost')) {
$this->skip('Cannot generate sitemap without a valid base URL');
}
```

Add a skip feature to build tasks

---

RELEASE_NOTES.md
packages/framework/src/Framework/Actions/PostBuildTasks/GenerateSitemap.php
packages/framework/tests/Feature/Services/BuildTaskServiceTest.php

Before, this would fall back to a relative URL, but these no longer validate by Google and will not be indexed. It feels a bit dramatic to have an exception be thrown when building test sites locally so instead we just skip the build, but with a helpful message.
Technically this can be seen as a breaking change, as this results in a sitemap file not being generated. But the end result in both cases is the same. Before this change we in this scenario when missing a base URL we get a sitemap that cannot be indexed, and after this change we don't generate a sitemap at all. In both cases, Google will not index the site using the sitemap. In the new case, we at least provide a notice to the user. I think this better follows the principle of least astonishment and thus I believe this justifies …

Skip sitemap generation when there is no valid base URL

---

docs/architecture-concepts/the-hydekernel.md
monorepo/CodeIntelligence/CodeIntelligence.php
packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/src/Console/Commands/PublishHomepageCommand.php
packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Foundation/Internal/LoadConfiguration.php
packages/framework/src/Foundation/Internal/LoadYamlConfiguration.php
packages/framework/src/Foundation/Kernel/Filesystem.php
packages/framework/src/Framework/Actions/BladeMatterParser.php
packages/framework/src/Framework/Actions/PreBuildTasks/CleanSiteDirectory.php
packages/framework/src/Framework/Concerns/Internal/ForwardsIlluminateFilesystem.php
packages/framework/src/Framework/Factories/BlogPostDataFactory.php
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Factories/HydePageDataFactory.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php
packages/framework/src/Framework/Services/ValidationService.php
packages/framework/src/Framework/Services/ViewDiffService.php
packages/framework/src/Markdown/Models/Markdown.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Support/Models/RenderData.php
packages/framework/src/Support/Paginator.php
packages/framework/tests/Feature/PaginatorTest.php
packages/framework/tests/Feature/RenderHelperTest.php
packages/framework/tests/Feature/Services/ValidationServiceTest.php
packages/framework/tests/Feature/Services/ViewDiffServiceTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php
packages/framework/tests/Unit/RenderHelperTest.php
packages/framework/tests/Unit/ViewDiffServiceTest.php

Minor code cleanup and refactors, mainly for tests. Goes through almost all tests to ensure they are properly formatted and use the best assertions. Some of these are over two years old (AKA the first tests of HydePHP) and in need of some care. It also fixes over 30 Psalm issues and increases the type coverage to as much as we're gonna be able to get it.

Clean up and refactor code

---

packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Support/Internal/RouteList.php
packages/framework/src/Support/Internal/RouteListItem.php
packages/framework/tests/Feature/Commands/RouteListCommandTest.php
packages/framework/tests/Feature/RouteListTest.php

By placing experimental or internal classes within a dedicated namespace like Hyde\Support\Internal, we make it clear to other developers that these classes are not part of the stable public API. It also allows us to organize our codebase more effectively, making it easier to maintain and evolve over time. It also gives us more freedom to create more helper classes like this, without increasing the maintenance burden.

Move internal helper classes to new internal support namespace

---

RELEASE_NOTES.md
packages/framework/src/Markdown/Processing/CodeblockFilepathProcessor.php
packages/framework/tests/Feature/Services/Markdown/CodeblockFilepathProcessorTest.php

Now supports this, and thus fixes https://github.com/hydephp/develop/issues/1564
```
```
Also cleans up the related test

Add custom filepath label support for HTML comments

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Unit/ServeCommandOptionsUnitTest.php

**Pull Request Description:**
This pull request aims to enhance the functionality of the new realtime compiler by introducing a `--open` flag. With this addition, users will have the ability to specify the page to open upon server startup. The default page will remain as 'index', ensuring backward compatibility, while the `--open` flag offers users the flexibility to easily navigate to a different page.
**Example Usage:**
```bash
php hyde serve --open=dashboard
```
Executing the command above will result in the server opening `localhost:8080/dashboard` instead of the default `localhost:8080`. This feature enhancement aims to streamline user experience by providing a convenient method to set the initial page when launching the server.
It fixes https://github.com/hydephp/develop/issues/1504

Update realtime compiler open flag to support specifying the page to open

---

RELEASE_NOTES.md
config/hyde.php
docs/digging-deeper/customization.md
packages/framework/config/hyde.php
packages/framework/resources/views/components/navigation/theme-toggle-button.blade.php
packages/framework/src/Facades/Features.php
packages/framework/tests/Feature/ConfigurableFeaturesTest.php
packages/framework/tests/Feature/DarkmodeFeatureTest.php

You can now disable the theme toggle buttons by setting `theme_toggle_buttons` to `false` in `config/hyde.php`.
If the `Feature::Darkmode` setting is disabled in the `features` array in the same file, this won't do anything, but if darkmode is enabled setting the theme toggle buttons setting to false they will not show up in the app layout nor the documentation layout; instead the appropriate color scheme will be automatically applied based on the browser system settings.

Add a config option to disable theme toggle buttons to automatically use browser settings

---

.gitattributes

Changing CRLF to LF makes sense for text files, but not images, where doing so can lead to file corruption. This commit tells Git to ignore binary files and only do the substitution in plain text files.
Fixes hydephp/hyde#239.

.gitattributes: substitute CRLF only in text files

---

RELEASE_NOTES.md
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/NavigationMenu.php
packages/framework/tests/Feature/NavigationMenuTest.php
packages/framework/tests/Unit/NavigationDataFactoryUnitTest.php

This pull request fixes #1515, which concerns the inconsistency in navigation group behavior when setting navigation groups for standard pages in front matter alongside the dropdown subdirectory setting in the configuration file.
Using the following in `_pages/page.md` will now cause the page to be put in the appropriate dropdown regardless of the `hyde.navigation.subdirectories` setting. This better follows the principle of least astonishment as setting the front matter is an explicit instruction to HydePHP.
```markdown
---
navigation.group: My Group
---

Honour front matter navigation groups set in front matter regardless of subdirectory setting

---

packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/NavigationMenuTest.php

Merges https://github.com/hydephp/develop/pull/1703 into https://github.com/hydephp/develop/pull/1565

[2.x] Honour front matter navigation groups set in front matter regardless of subdirectory setting

---

RELEASE_NOTES.md
packages/framework/src/Support/Includes.php
packages/framework/tests/Feature/IncludesFacadeTest.php

It feels weird that this creates the directory, and it violates the principle of least astonishment as it's surprising that this creates a directory when you just request the path. Fixes https://github.com/hydephp/develop/issues/1706

[2.x] Calling the `Include::path()` method will no longer create the directory

---

RELEASE_NOTES.md
docs/digging-deeper/navigation.md
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/FilenamePrefixNavigationHelper.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/tests/Feature/FilenamePrefixNavigationPriorityTest.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php
packages/framework/tests/Unit/FilenamePrefixNavigationPriorityUnitTest.php

Fixes https://github.com/hydephp/develop/issues/1646
> When source filed are numbered like so (or using the most common convention)
> 
> ```
> 1_foo.md
> 2_bar.md
> 3_baz.md
> ```
> 
> That order should be used for their navigation priorities.
> 
> This makes large sites much cleaner as local file systems match the order of the results. Of course it should be possible to disable this as well.

[2.x] Support automatic navigation priorities by prefixing a number in filenames

---

RELEASE_NOTES.md
packages/framework/src/Support/DataCollections.php

Fixes https://github.com/hydephp/develop/issues/1716 by calling `static` instead of the class self reference.
This fix can be released in a patch release since protected methods are generally not supported by our BC promise.

Use late static bindings to support overriding data collections file finding

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/tests/Feature/Commands/RouteListCommandTest.php

Fixes https://github.com/hydephp/develop/issues/1715 and opens up for more formats in the future, trying to match how Symfony does it. 
Currently only the `json` format is added.
```json
[
{
"page_type": "BladePage",
"source_file": "_pages/404.blade.php",
"output_file": "_site/404.html",
"route_key": "404"
},
{
"page_type": "BladePage",
"source_file": "_pages/index.blade.php",
"output_file": "_site/index.html",
"route_key": "index"
}
]
```
Of course, the output of this can also be redirected into a file stream:
```bash
$ php hyde route:list --format=json > routes.json
```

Add a JSON output format option to the route list command

---

composer.lock
packages/framework/composer.json
packages/framework/tests/Feature/MarkdownFileParserTest.php

Bumps the front matter parser to use https://github.com/spatie/yaml-front-matter/pull/41, thus fixing https://github.com/hydephp/develop/issues/1705. Also adds a test to proof it.

Fix undefined array key exception for empty Markdown pages

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Framework/Actions/PostBuildTasks/GenerateSitemap.php
packages/framework/tests/Feature/Foundation/HyperlinksTest.php
packages/framework/tests/Feature/HelpersTest.php
packages/framework/tests/Feature/SitesWithoutBaseUrlAreHandledGracefullyTest.php
packages/framework/tests/Feature/Views/MetadataViewTest.php
packages/framework/tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php

We're getting some issues by Hyde using `localhost` as the default site URL. Initially, this PR will target the 1.x branch because I consider these things to be bugs that should be fixed in v1, however, there may be side effects of this: primarily that output HTML will change - but I do not think anyone will depend on those undesired effects before this patch, since localhost is never desired in production. This will resolve https://github.com/hydephp/develop/issues/1720
Expanding on the reasoning behind allowing this in 1.x: Since v1 is LTS, I don't want to leave those users hanging with what is in my opinion a bug, that localhost links can "leak" through production. And I think the only way to fix this is by changing some logic which could have side effects. But I think I am okay with …

Improve behaviour when a site URL is not explicitly set

---

RELEASE_NOTES.md
packages/framework/src/Framework/Exceptions/ParseException.php
packages/framework/src/Markdown/Exceptions/ParseException.php
packages/framework/src/Support/DataCollection.php
packages/framework/tests/Feature/DataCollectionTest.php
packages/framework/tests/Unit/CustomExceptionsTest.php
packages/framework/tests/Unit/DataCollectionUnitTest.php

See the 1.x tie-in to make the upgrade smoother https://github.com/hydephp/develop/pull/1733. Fixes https://github.com/hydephp/develop/issues/1712
Main changes:
- **Breaking:** Renamed class `DataCollections` to `DataCollection`
- Fixes part of https://github.com/hydephp/develop/issues/1712
- JSON collection files are now validated
- Fixes https://github.com/hydephp/develop/issues/1736
- Yaml data files no longer need to start with triple dashes to be parsed by DataCollections
- Fixes part of https://github.com/hydephp/develop/issues/1712
- (cherry picked to 1.x via https://github.com/hydephp/develop/pull/1733)
- No longer automatically create the data collections directory 
- Fixes https://github.com/hydephp/develop/issues/1735 
- Adds a new custom `ParseException` exception
Also adds …

[2.x] DataCollections improvements

---

RELEASE_NOTES.md
docs/digging-deeper/collections.md
packages/framework/src/Support/DataCollections.php
packages/framework/tests/Feature/DataCollectionTest.php

Tie-in with https://github.com/hydephp/develop/pull/1732 to make the upgrade smoother. See https://github.com/hydephp/develop/issues/1712

[1.x] DataCollections improvements

---

RELEASE_NOTES.md
docs/digging-deeper/helpers.md
packages/framework/src/Support/Includes.php
packages/framework/tests/Feature/IncludesFacadeTest.php
packages/framework/tests/Unit/IncludesFacadeUnitTest.php

- Fixes https://github.com/hydephp/develop/issues/1734
- This means that nested directories are no longer supported, as you should use a data collection for that.
The following methods in the `Includes` facade now return `HtmlString` objects instead of `string`:
- `Includes::html()`
- `Includes::blade()`
- `Includes::markdown()`
Notes:
- This means that you no longer need to use `{!! !!}` to render the output of these methods in Blade templates, instead just use `{{ }}`.
- If you have used the return value of these methods in custom code, you may need to adjust your code to work with the new return type.
For more information, see the RFC that proposed this change: https://github.com/hydephp/develop/issues/1734
The RFC was implemented in https://github.com/hydephp/develop/pull/1738 …

[2.x] Includes facade improvements

---

tests/fixtures/_posts/typography-front-matter.md
tests/fixtures/_posts/typography-simple.md

Fixes https://github.com/hydephp/develop/issues/1730

Internal: Update test fixtures to use "class" instead of "className"

---

packages/framework/src/helpers.php
packages/framework/tests/Feature/HelpersTest.php

Fixes https://github.com/hydephp/develop/issues/1731

[2.x] Update the `route` helper function to throw if the route does not exist

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/XmlGenerators/SitemapGenerator.php
packages/framework/tests/Feature/Commands/BuildSitemapCommandTest.php
packages/framework/tests/Feature/SitemapFeatureTest.php

[2.x] Even smarter sitemap generation

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/BuildTasks/BuildTaskSkippedException.php
packages/framework/tests/Feature/Commands/BuildSitemapCommandTest.php
packages/framework/tests/Unit/BuildTaskSkippedExceptionTest.php
packages/framework/tests/Unit/BuildTaskUnitTest.php

When calling a build task directly, for example with a wrapper like `php hyde sitemap:build`, the command will now exit with status code `3` instead of `0`, in order to signal that something went wrong. If a task is skipped during the main `php hyde build` command, nothing will change.
The reason behind this is that if you call a specific command like the sitemap build command directly, and it is skipped, then something other than what the user expected happened, so the exit code should reflect that. In comparison: A skipped build task as part of the main site build is not as critical, because in those cases the build task is auxiliary to the expected outcome.
This fixes https://github.com/hydephp/develop/issues/1745, please see that issue on how we landed on using exit code `3` when …

[2x] Use a non-zero exit code 3 when skipping build tasks

---

RELEASE_NOTES.md
packages/framework/src/helpers.php

This fixes part two of https://github.com/hydephp/develop/issues/1751. See https://github.com/hydephp/develop/pull/1753 for part one.

[2.x] Remove the deprecated global `unslash` function

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/tests/Feature/Commands/DebugCommandTest.php
packages/realtime-compiler/src/Http/DashboardController.php

This feature works great in the monorepo, but in other places it's just confusing, as it shows the project version, and it's also quite uncommon to version sites using tags. The original container binding is from Laravel Zero, presumably for finding the version in the compiled standalone, something we are not using due to our version constant.
This PR targets v1 as it is not breaking, we just remove displays of this from the dashboard and debug screen.

Remove the Git version displays

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/tests/Feature/HelpersTest.php
packages/framework/tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php

This is implemented in the `Hyperlinks` class meaning it effects both the `Hyde::url()` helper and the global `url()` function.
```php
Hyde::url('https://example.com/foo');
// Before https://example.com/https://example.com/foo
// After https://example.com/foo
```

 Update the Hyde URL helper to not modify already qualified URLs

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Framework/Exceptions/BaseUrlNotSetException.php

This fixes part one of https://github.com/hydephp/develop/issues/1758. See https://github.com/hydephp/develop/pulls/1760 for part two.

[1.x] Deprecate the `BaseUrlNotSetException` class

---

packages/framework/tests/Feature/Commands/ServeCommandTest.php
packages/framework/tests/Feature/HydeKernelTest.php
packages/framework/tests/Unit/HydeConfigFilesAreMatchingTest.php

Goes over all the skipped tests to see what we can do about them (remove, fix, rework, etc)

Internal: Handle skipped tests

---

.github/workflows/continuous-integration.yml
.github/workflows/test-pull-requests.yml
composer.lock
packages/framework/.github/workflows/run-tests.yml

Runs tests on PHP 8.1 and also updates the main CI workflow to run on all three supported versions, instead of just 8.1. Not sure why that last one wasn't updated.

Internal: Run tests on PHP 8.1 through PHP 8.3

---

packages/hyde/phpunit.xml.dist

This fixes the "Your XML configuration validates against a deprecated schema" warning in the subtree splits.

Internal: Migrate PHPUnit configuration

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/XmlGenerators/SitemapGenerator.php

Fixes https://github.com/hydephp/develop/issues/1748 and normalizes with the behaviour that adds the version prefix to the HTML generator meta tag https://github.com/hydephp/develop/commit/eade477e0dd713f096d5484b5dd73444a14a1e16

Add a version prefix to the sitemap generator version attribute

---

.github/scripts/LabelInternal.js
.github/scripts/RemoveStateLabels.js
.github/workflows/label-pull-requests.yml

See https://github.com/actions/github-script?tab=readme-ov-file#run-a-separate-file

Internal: Improve pull request labeling workflow

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Internal/LoadYamlConfiguration.php
packages/framework/tests/Feature/LoadYamlConfigurationTest.php

**Overview:**
- Refactors and improves the code
- New attempt at https://github.com/hydephp/develop/pull/1691
- Fixes https://github.com/hydephp/develop/issues/1523

Improve the Yaml configuration loader

---

packages/framework/src/Foundation/ConsoleKernel.php
packages/framework/tests/Feature/ConsoleKernelTest.php

Cherry picks changes from https://github.com/hydephp/develop/pull/1771 replacing our overcomplicated bootstrapper array manipulations with just returning what we expect directly from the method.

Refactor console kernel bootstrapper loading 

---

packages/framework/src/Foundation/ConsoleKernel.php
packages/framework/tests/Feature/ConsoleKernelTest.php

Picks up where https://github.com/hydephp/develop/pull/1770 left off
> I think adding a dedicated environment configuration loader to get data from the Yaml file could work if it's in between the environment and configuration loaders

Improve Yaml environment configuration loading

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Internal/LoadYamlConfiguration.php
packages/framework/src/Foundation/Internal/LoadYamlEnvironmentVariables.php
packages/framework/src/Foundation/Internal/YamlConfigurationRepository.php
packages/framework/tests/Feature/HighLevelYamlConfigurationFeatureTest.php
packages/framework/tests/Feature/YamlConfigurationFeatureTest.php

Picks up where https://github.com/hydephp/develop/pull/1770 left off and replaces https://github.com/hydephp/develop/pull/1771 which was merged by GitHub due to a [glitch](https://github.com/hydephp/develop/pull/1771#issuecomment-2200297519).
> I think adding a dedicated environment configuration loader to get data from the Yaml file could work if it's in between the environment and configuration loaders
This pull request is a story of how I continuously lost my mind.
In short, what we ended up with is a simple system that reads the yaml configuration before the application boots, and injects an environment variable for the site name if it's needed in order to elegantly have it be used in the configuration which is loaded afterwards.

Refactor bootstrappers and improve Yaml environment configuration loading

---

packages/framework/tests/Feature/Commands/MakePostCommandTest.php
packages/framework/tests/Feature/PostsAuthorIntegrationTest.php
packages/framework/tests/Feature/StaticSiteBuilderDocumentationModuleTest.php
packages/framework/tests/Feature/StaticSiteBuilderPostModuleTest.php
packages/framework/tests/Unit/GetLatestMarkdownPostsTest.php
tests/Browser/HighLevelViewTest.php

Cleans up the test code in some one of the original tests, meaning most of this is over two years old and not too pretty

Internal: Clean up and refactor test code

---

CHANGELOG.md
RELEASE_NOTES.md
packages/framework/src/Foundation/HydeKernel.php
packages/hyde/composer.json

- Added support for using HTML comments to create Markdown code block filepath labels in https://github.com/hydephp/develop/pull/1693
- Added a config option to disable the theme toggle buttons to automatically use browser settings in https://github.com/hydephp/develop/pull/1697
- You can now specify which path to open when using the `--open` option in the serve command in https://github.com/hydephp/develop/pull/1694
- Added a `--format=json` option to the `route:list` command in https://github.com/hydephp/develop/pull/1724
- When a navigation group is set in front matter, it will now be used regardless of the subdirectory configuration in https://github.com/hydephp/develop/pull/1703 (fixes https://github.com/hydephp/develop/issues/1515)
- Use late static bindings to support overriding …

HydePHP v1.7.0 - 2024-07-05

---

docs/digging-deeper/updating-hyde.md

This has gotten feedback on the Git method being confusing, and it's actually not really needed anymore now that Hyde is stable (this method was very useful in beta when there were a lot of breaking changes to project files)
This rewrites the documentation to downplay the Git and hard reset methods, instead focusing on the recommended Composer update.

Internal: Update the updating documentation

---

RELEASE_NOTES.md
packages/framework/src/Foundation/HydeKernel.php
packages/framework/tests/Feature/HydeKernelTest.php

In case an external service uses the Kernel's array representation, for example through Json, this can help that system know the schema for that version, as it can parse the SemVer tag added.

Update the `HydeKernel` array representation to include the Hyde version

---

RELEASE_NOTES.md
packages/framework/src/Support/Concerns/Serializable.php
packages/framework/tests/Unit/SerializableTest.php

Updates the `Serializable` trait by providing a default `toArray` method implementation which return its public properties. Can be overridden for increased control and performance. Fixes https://github.com/hydephp/develop/issues/1783

Update the `Serializable` trait to provide a default automatic `toArray` method

---

packages/framework/src/Support/Concerns/Serializable.php

Since we can't do things like `parent::toArray` to utilize the trait logic, and we can't do `$this->toArray` from an overridden method, this allows classes using this to work on the original logic like this:
```php
use Serializable;
public function toArray(): array
{
return array_filter($this->automaticallySerialize());
}
```

Extract helper method for automatic serialization

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Blogging/Models/PostAuthor.php
packages/framework/tests/Feature/MarkdownPostTest.php
packages/framework/tests/Unit/PostAuthorTest.php

Tie in with https://github.com/hydephp/develop/pull/1782 to smooth over the upgrade to v2
Cherry picks commit https://github.com/hydephp/develop/pull/1782/commits/0dfb841b809d41149ba870b69d09baacf072e18d from https://github.com/hydephp/develop/pull/1782
Cherry picks commit https://github.com/hydephp/develop/pull/1782/commits/2f54b9f9aad5a9065ae51ec9df5dc9ee0d023795 from https://github.com/hydephp/develop/pull/1782
Since the author name is now always set at construct time, we can remove the nullable modifier from the property.

[1.x] Update the post author class to prepare for the v2 overhaul

---

RELEASE_NOTES.md
packages/framework/src/Framework/Exceptions/InvalidConfigurationException.php
packages/framework/tests/Unit/CustomExceptionsTest.php

Adds a new `\Hyde\Framework\Exceptions\InvalidConfigurationException` exception class to handle invalid configuration exceptions with support for showing the errored line.
Cherry picked from https://github.com/hydephp/develop/pull/1798

[2.x] Add an invalid configuration exception class

---

.idea/develop.iml

- Update develop.iml to exclude PHPUnit result caches
- Update develop.iml to exclude VS Code data

Internal: Update monorepo PhpStorm configuration files

---

packages/framework/src/Facades/Author.php

May want something in HydeStan for this to detect if line uses link to our site but with the HTML extension.

Normalize documented link in code documentation

---

config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Facades/Navigation.php
packages/framework/src/Framework/Features/Navigation/NavigationMenuConfigurationBuilder.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php
packages/framework/tests/Unit/Facades/NavigationFacadeTest.php
packages/framework/tests/Unit/NavigationMenuConfigurationBuilderTest.php

Part of https://github.com/hydephp/develop/pull/1818, please see the changelog there.
Inspired by https://github.com/hydephp/develop/issues/1508#issuecomment-1941638495 which could be adapted into this: (to normalize sidebar/mainmenu configuration)
```php
'menus' => [
NavigationMenu::configure('main')
->doStuff()
NavigationMenu::configure('docs')
->doStuff()
],
```
--- 
This syntax is optional, but can still be used as the default. It's fully compatible with array syntaxes as the builder instance can be used as an array as it's an `ArrayObject`
- Main benefit: Get IDE support and method autocomplete when defining the config
- Main drawback: Laravel Idea can't autocomplete `config()` values
---

[2.x] Add a navigation config builder class

---

packages/framework/resources/views/components/article-excerpt.blade.php

Code style change which makes the itemprop relationship clearer

Fix article excerpt indentation

---

docs/digging-deeper/navigation.md
packages/framework/src/Facades/Navigation.php

Part of https://github.com/hydephp/develop/pull/1818 and goes over the entire navigation documentation to ensure it's consistent and concise, without losing information.
Additionally, it rethinks the document outline to account for many people not reading the document top to bottom, and instead only read sections at a time. As such, words that tie together sections have been removed, in order to make each section usable on its own.
It also updates headings to be more concise, instead of fluent English, to make the sections more skimmable.

[2.x] Clean up the navigation documentation

---

monorepo/DevTools/src/MonorepoDevToolsServiceProvider.php
monorepo/DevTools/src/RefactorConfigCommand.php

Adds a command we can use to convert configuration, initially intended to quickly document alternate config syntaxes, but we could bundle it in the framework later on if we wanted. We may also then want to normalize the command namespace with the ChangeSourceDirectoryCommand

Internal: Adding an experimental config converter command to the monorepo

---

docs/creating-content/documentation-pages.md
docs/digging-deeper/customization.md
docs/digging-deeper/navigation.md
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php

Targets https://github.com/hydephp/develop/pull/1818
This PR reorganizes and improves the documentation for navigation menus and documentation pages in Hyde. The main changes are:
1. Move sidebar-specific content from `navigation.md` to `documentation-pages.md`
2. Update `customization.md` to reflect the new organization
3. Add missing information about numerical prefix ordering to `documentation-pages.md`
Motivation:
- Reduce duplication and potential inconsistencies in the documentation
- Improve the overall organization of the docs, making it easier for users to find relevant information
- Ensure all features, including numerical prefix ordering, are properly documented
Benefits:
- Clearer separation of concerns between main navigation and documentation sidebar
- More comprehensive and …

Move the sidebar documentation to the documentation pages page

---

RELEASE_NOTES.md
docs/architecture-concepts/extensions-api.md
packages/framework/src/Foundation/Concerns/HydeExtension.php
packages/framework/src/Foundation/Concerns/ManagesExtensions.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php

This PR enhances the Extensions API by adding support for `booting` and `booted` callbacks directly in the `HydeExtension` class. This allows extension developers to hook into the Hyde kernel's boot process more easily and perform setup or cleanup tasks.
- Added `booting()` and `booted()` methods to `HydeExtension` class
- Updated `ManagesExtensions` trait to register these callbacks
- Modified `BootsHydeKernel` trait to call the new callbacks
- Updated tests to cover the new functionality
- Updated documentation to reflect the new features
This change is backwards-compatible and requires no changes for existing extensions. However, developers can now take advantage of these new methods to perform actions during the kernel boot process.

[2.x] Add booting and booted callbacks to the HydeExtension feature

---

.github/workflows/smoke-tests.yml
.idea/misc.xml
RELEASE_NOTES.md
composer.lock
packages/realtime-compiler/composer.json
packages/realtime-compiler/src/Http/DashboardController.php
packages/realtime-compiler/src/Http/VirtualRouteController.php
packages/realtime-compiler/src/RealtimeCompiler.php
packages/realtime-compiler/src/RealtimeCompilerServiceProvider.php
packages/realtime-compiler/src/Routing/PageRouter.php
packages/realtime-compiler/src/Routing/Router.php

Creates a new system to instead of hardcoding virtual routes, we store them in the service container (which is loaded when the router boots)
This means it's also possible for package developers to add realtime compiler routes:
```php
<?php
namespace App\Providers;
use Illuminate\Support\ServiceProvider;
use Hyde\RealtimeCompiler\RealtimeCompiler;
class AppServiceProvider extends ServiceProvider
{
/**
* Bootstrap any application services.
*/
public function boot(): void
{
$router = $this->app->make(RealtimeCompiler::class);
$router->registerVirtualRoute('/foo', callable(\Desilva\Microserve\Request): \Desilva\Microserve\Response);
}
}
```

Refactor realtime compiler to handle virtual routes through the service container

---

RELEASE_NOTES.md
packages/realtime-compiler/resources/dashboard.blade.php

- **Add ternary check to not show source path for virtual pages**
- **Improve dashboard table item formatting**
- **Stylize formatting of dynamic source file label**
- **Disable dashboard button to edit in-memory pages**
- Fixes https://github.com/hydephp/realtime-compiler/issues/22
- **Remove identifier row from dashboard table**
- Fixes https://github.com/hydephp/realtime-compiler/issues/29

Improve the realtime compiler dashboard

---

packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Unit/ServeCommandOptionsUnitTest.php

Improves how we get the "open" command by extracting a helper method that can be unit tested without the OS constant

Refactor the serve command and add more unit tests for it

---

RELEASE_NOTES.md
packages/framework/config/commands.php

Fixes https://github.com/hydephp/develop/issues/1874

Hide the Torchlight install command

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Framework/Features/Metadata/PageMetadataBag.php
packages/framework/tests/Feature/Foundation/HyperlinksTest.php

1. New Helper Method
- Added `Hyperlinks::isRemote()` to improve URL checking
2. Featured Image Updates
- Updated featured image method to use extracted logic
- Deprecated `FeaturedImage::isRemote()` method
- Replaced by `Hyperlinks::isRemote()`
3. URL Handling Improvements
- Normalized remote URL checking across the codebase
- Updated `Hyde::asset()` method
- Now considers protocol-relative URLs (`//`) as remote
- These changes aim to standardize and improve URL handling throughout the project.
- The deprecation of `FeaturedImage::isRemote()` may require updates in code using this method.

Normalize protocol relative URL handling

---

RELEASE_NOTES.md
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php

Tie in with https://github.com/hydephp/develop/pull/1882

[2.x] Remove deprecated method `FeaturedImage::isRemote()`

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Concerns/ForwardsHyperlinks.php
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Hyde.php
packages/framework/src/helpers.php
packages/framework/tests/Feature/HelpersTest.php
packages/framework/tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php

Reverts the unreleased behaviour where this returns null. Returning null for a fault path means the developer needs to check for null types, but that solves the problem. If the developer cares about site URLs they need to set the site URL, and having a null that can silently be ignored is unintuitive. If the user tries to get a base URL and one is not set, that's a bug, and throwing an exception alerts them of it. It is not justified to have the custom exception for this, so that is still removed, and we now throw a BadMethodCallException instead. This essentially reverts most of https://github.com/hydephp/develop/pull/1760. See tie in with https://github.com/hydephp/develop/commit/e9778a968ef746ecf6f8a58b40e7e431f590e3a5

[2.x] Revert to throwing an exception when trying to get non-configured base URL

---

RELEASE_NOTES.md
packages/framework/src/Framework/Services/BuildService.php

This PR modifies the `BuildService` to group all dynamic pages (`InMemoryPage` instances) together under a "Dynamic Pages" category during the build process. This is because this otherwise can very quickly grow to have a bunch of single item progress bars when using a lot of extended pages of this type.

[2.x] Update the build service to group together dynamic pages

---

RELEASE_NOTES.md
packages/framework/src/Markdown/Models/Markdown.php
packages/framework/tests/Feature/ColoredBlockquoteShortcodesTest.php
packages/framework/tests/Unit/MarkdownFacadeTest.php

This simplification means that the method is more predictable, and better follows the principle of least astonishment. I've been so confused so many times about this that using our Markdown helper does not always mean that we get our Markdown features. This change means that any time you call this method, custom Markdown features like our shortcodes and processors will be applied.
A side effect of this is in unit tests, as the method now requires the kernel and config to be set up.

[2.x] Update the `Markdown::render` method to always use the smart Markdown service

---

RELEASE_NOTES.md
config/hyde.php
docs/digging-deeper/customization.md
packages/framework/config/hyde.php
packages/framework/src/Framework/Services/AssetService.php
packages/framework/tests/Unit/AssetServiceUnitTest.php

I can't see a good reason to want to change the version to load assets that are unlikely to work with the versions in the views in the project Hyde version. Changing the CDN URL could be useful if you want to change the host to another CDN provider, but this current system is way too convoluted for that.
This is a part of https://github.com/hydephp/develop/pull/1904

[2.x] Remove HydeFront version and CDN URL configuration options

---

RELEASE_NOTES.md
packages/framework/src/Framework/Services/AssetService.php
packages/framework/tests/Unit/AssetServiceUnitTest.php

This PR simplifies the AssetService API by making the `HYDEFRONT_VERSION` and `HYDEFRONT_CDN_URL` constants protected instead of public, as these no longer have any influence outside of the class, after https://github.com/hydephp/develop/pull/1910. This change improves encapsulation and reduces the public API surface, but it is a breaking change for any code directly accessing these constants. The PR also removes related unit tests that are no longer applicable due to the change in visibility.

[2.x] Simplify public asset service API

---

app/config.php
packages/framework/resources/views/layouts/styles.blade.php
packages/framework/src/Facades/Asset.php
packages/framework/src/Facades/HydeFront.php
packages/framework/tests/Unit/Facades/AssetFacadeUnitTest.php
packages/framework/tests/Unit/Facades/HydeFrontFacadeTest.php
packages/framework/tests/Unit/Views/StylesComponentViewTest.php
spec.md

This PR splits the HydeFront-related functionality from the the Asset facade into a new HydeFront facade. This change simplifies the Asset API and separates concerns. This is part of https://github.com/hydephp/develop/pull/1904

[2.x] Decouple HydeFront features from the Asset facade

---

config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Facades/Asset.php
packages/framework/src/Foundation/Kernel/Hyperlinks.php
packages/framework/src/Support/Filesystem/MediaFile.php
packages/framework/tests/Feature/Foundation/HyperlinksTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php

This PR is part of https://github.com/hydephp/develop/pull/1904 and fixes a major discrepancy where `Asset::mediaLink()` adds a cache busting key but `Hyde::mediaLink()` does not. Now, all asset helpers will use cache busting when enabled.

[2.x] Normalize asset cache busting

---

RELEASE_NOTES.md
packages/framework/src/Hyde.php

Let's see if this has gotten better support since last time we tried this. If this works, it means that clicking a usage will actually lead to the implementation, and we can get better support for PHPDoc annotations like usages and deprecations.

Update the Hyde facade to use a mixin annotation instead of method annotations

---

.github/workflows/coverage-tests.yml
.github/workflows/smoke-tests.yml
monorepo/scripts/ping-openanalytics-testrunner.php

We've updated our smoke tests workflow to run tests in parallel, improving efficiency while maintaining compatibility with our existing processes. Here are the key changes:
1. Renamed the workflow to "🔥 Parallel Smoke Tests" to reflect its new parallel nature.
2. Added a step to prepare separate directories for unit and feature tests.
3. Introduced a "Run Parallel Smoke Tests" step that:
- Defines a function `run_tests` to execute tests for each suite.
- Runs unit and feature tests in parallel using background processes.
- Uses `sed` to prefix each line of output with either `[UNIT]` or `[FEATURE]` for clarity, with proper padding for alignment.
- Generates separate JUnit XML reports for each test suite.
4. Added a "Merge JUnit XML Reports" step that combines the unit and feature test …

Internal: Parallel smoke testing

---

packages/framework/src/Support/Filesystem/MediaFile.php
packages/framework/tests/Feature/Support/MediaFileTest.php
packages/framework/tests/Unit/Support/MediaFileUnitTest.php

- Follow up to https://github.com/hydephp/develop/pull/1918 
- This is a part of https://github.com/hydephp/develop/pull/1904
- Makes the public readonly metadata properties protected and only accessible via getter methods
- Lazy loads metadata properties using a boot system, which constructs all metadata properties when one is accessed (and when instance is serialized to array), and then caches them for future access
- No longer validates file existence in the constructor, but instead on boot, making it possible to create memory based file objects which opens up the API for more use cases, at the cost of inconsistent places where the file existence is checked but still having a robust system in place for when trying to get filesystem information for a non-existent file

[2.x] Lazy loaded MediaFile metadata properties

---

.github/workflows/smoke-tests.yml

This makes them open in the UI

Internal: Update smoke testing workflow to fail steps where logs have failures

---

.github/workflows/smoke-tests.yml

Part of https://github.com/hydephp/develop/issues/1950

Internal: Use compact smoke test output

---

ide.json
packages/framework/resources/views/layouts/scripts.blade.php
packages/framework/resources/views/layouts/styles.blade.php
packages/framework/src/Facades/Asset.php
packages/framework/tests/Feature/AssetAPIFeatureTest.php
packages/framework/tests/Unit/Facades/AssetFacadeUnitTest.php

Also considered `has`, but exists is generally better for clarity, as it directly indicates that you're checking for the presence of a file. has can be more ambiguous, as it might imply ownership or possession rather than existence. Therefore, exists is often preferred for methods that check for the presence of an item. It's also what the Laravel Filesystem facade uses.
Part of https://github.com/hydephp/develop/pull/1904

[2.x] Rename method `Asset::hasMediaFile` to `Asset::exists`

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Concerns/ForwardsHyperlinks.php
packages/framework/src/Foundation/Kernel/Hyperlinks.php

See https://github.com/hydephp/develop/pull/1904

[1.x] Deprecate `Hyde::mediaLink` being replaced by `Hyde::asset()` in v2

---

RELEASE_NOTES.md
config/hyde.php
docs/extensions/realtime-compiler.md
packages/framework/config/hyde.php
packages/realtime-compiler/tests/RealtimeCompilerTest.php

This pull request addresses issue [#1994](https://github.com/hydephp/develop/issues/1994) by updating the `serve` command to not save pages by default. This change aims to enhance the developer experience by making the behavior of the `serve` command less unexpected.
- **Unexpected Behavior**: The current implementation of the `serve` command saves pages by default, which can be surprising for developers who do not anticipate this action.
- **Improved Development Workflow**: By not saving pages by default, the development workflow becomes more intuitive, allowing developers to preview changes without automatically persisting them.
- Update the `serve` command to disable automatic saving of pages by default.
- The option for users to enable saving if desired is still available. 
This PR …

[2.x] Update default configuration to no longer save previewed pages

---

RELEASE_NOTES.md
docs/creating-content/documentation-pages.md
docs/digging-deeper/navigation.md
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Navigation/NumericalPageOrderingHelper.php
packages/framework/src/Support/Models/RouteKey.php
packages/framework/tests/Feature/NumericalPageOrderingHelperTest.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php
packages/framework/tests/Unit/NavigationDataFactoryUnitTest.php
packages/framework/tests/Unit/NumericalPageOrderingHelperUnitTest.php
packages/framework/tests/Unit/RouteKeyTest.php

Changes the numerical navigation prefix ordering to only work on documentation pages and removes the config option. Fixes https://github.com/hydephp/develop/issues/1997, which also has the motivations for this.

[2.x] Simplify numerical page ordering

---

RELEASE_NOTES.md
docs/creating-content/managing-assets.md
monorepo/scripts/tests/project-styles.php
vite.config.js

This pull request changes where compiled assets are saved during build. Currently, they go to `_site/media`. This request moves them to `_media` to better match project structure and simplify the build process.
- Targets https://github.com/hydephp/develop/pull/1565 via https://github.com/hydephp/develop/pull/2006
Based on the documentation and project structure, I believe `npm run build` should save assets to `_media` directory. Here's my reasoning:
Our documented conventions establish that:
- `resources/assets` contains source files that need compilation
- `_media` contains compiled/minified files
- `_site/media` is the final output directory for serving to users
This pattern makes sense because:
- It separates source, compiled, and output files clearly
- `_media` acts as a …

No longer copy files to site output from the asset bundler command

---

RELEASE_NOTES.md
packages/realtime-compiler/src/Actions/AssetFileLocator.php
packages/realtime-compiler/tests/RealtimeCompilerTest.php

This PR changes the realtime compiler to only serve assets from the media source directory (`_media`), rather than also checking the site output directory (`_site/media`).
- Targets https://github.com/hydephp/develop/pull/1565 via https://github.com/hydephp/develop/pull/2006
The realtime compiler is designed to emulate how the site will behave when served from a web server. When building the site, files from `_media` are copied to `_site/media`. Having the realtime compiler serve files from both locations could lead to inconsistencies and confusion about which version is being served.
While we could use `filemtime()` to serve the latest version, this would not accurately represent the production environment where only the files in `_site/media` would be available. Additionally, any file …

[2.x] Update the realtime compiler to only serve source media files

---

RELEASE_NOTES.md
docs/getting-started/console-commands.md
packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/tests/Feature/StaticSiteServiceTest.php

- Targets https://github.com/hydephp/develop/pull/1565 via https://github.com/hydephp/develop/pull/2006
This PR replaces the `--run-dev` and `--run-prod` build command flags with a single `--run-vite` flag. This change is needed because we switched from Laravel Mix to Vite in #2010, which has different commands and behaviors:
- `npm run dev` with Vite starts a development server (incompatible with our build process)
- `npm run prod` no longer exists, replaced by `npm run build`
**The new `--run-vite` flag will:**
1. Run `npm run build` to compile assets with Vite
2. Re-run the media asset transfer task since Vite outputs to `_site/media` (see #2011)
- Removed `--run-dev` flag
- Removed `--run-prod` flag
- Added new `--run-vite` flag
- Follows #2010 (Switch to Vite)
- Follows #2011 (Change …

[2.x] Replace `--run-dev` and `--run-prod` build command flags with `--run-vite` flag

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php
packages/realtime-compiler/src/ConsoleOutput.php

```bash
i PHP 8.3.7 Development Server started. Press Ctrl+C to stop.2024-11-12 11:25:28 # Before
i PHP 8.3.7 Development Server started. Use Ctrl+C to stop.  2024-11-12 11:26:26 # After
```

Shorten the realtime compiler server start message to better fit within 80 column terminals

---

RELEASE_NOTES.md
vite.config.js

- Closes https://github.com/hydephp/develop/issues/2027
- Targets https://github.com/hydephp/develop/pull/1565 via https://github.com/hydephp/develop/pull/2006
PS H:\monorepo> npm run build
```bash
> build
> vite build
vite v5.4.10 building for production...
✓ 2 modules transformed.
Generated an empty chunk: "app".
_media/app.css  38.78 kB │ gzip: 7.51 kB
_media/app.js    0.00 kB │ gzip: 0.02 kB
✓ built in 1.09s
```
```bash
PS H:\monorepo> npm run build
> build
> vite build
vite v5.4.10 building for production...
✓ 1 modules transformed.
_media/app.css  37.77 kB │ gzip: 7.27 kB
✓ built in 1.44s
```
```bash
PS H:\monorepo> npm run build
> build
> vite build
vite v5.4.10 building for production...
✓ 2 modules transformed.
_media/app.css  37.77 kB │ gzip: 7.27 kB
_media/app.js    0.02 kB │ …
```

[2.x] Only compile app scripts if it has contents

---

packages/hyde/tailwind.config.js
tailwind.config.js

This change ensures that Tailwind will scan all nested Blade pages in the `_pages` directory.
Cherry picks https://github.com/hydephp/hyde/pull/267 to the monorepo to sync up the packages.

Fix Tailwind content path for nested Blade pages

---

packages/testing/src/Support/HtmlTesting/TestableHtmlDocument.php

Fixes an issue where the old implementation does not work reliably on macOS when running the full suite.
---
**Explanation of Changes:**
1. **Using XPath:**  XPath is a powerful language for querying XML documents (and HTML, which is XML-like). It's much more efficient and reliable for complex queries than manual traversal.
2. **`DOMXPath` Object:** We create a `DOMXPath` object using the existing `$this->document` object, which is already a parsed DOM. This avoids re-parsing the HTML.
3. **Robust Class Matching:** The XPath expression `//*[contains(concat(' ', normalize-space(@class), ' '), ' $class ')]` is a standard and robust way to find elements with a specific class, even if they have multiple classes.  It handles leading/trailing spaces correctly.
4. **Iterating `DOMNodeList`:** …

Internal: More reliable internal testing helper implementation

---

packages/publications/tests/Feature/PublicationPageCompilerTest.php

At long last tracks down this test that keeps removing `resources/views/.gitkeep`

Internal: Fix test removing gitkeep file

---

packages/framework/src/Framework/Actions/GeneratesTableOfContents.php
packages/framework/src/Markdown/Processing/HeadingRenderer.php
packages/framework/tests/Feature/MarkdownHeadingRendererTest.php
packages/framework/tests/Unit/HeadingRendererUnitTest.php

- Follow up to https://github.com/hydephp/develop/pull/2047
- Targets https://github.com/hydephp/develop/pull/2006
This pull request modifies the heading identifier generation to improve how heading slugs/IDs are created. The key changes include:
1. Replacing the simple `Str::slug()` method with a more robust `makeIdentifier()` method in the `HeadingRenderer` class.
2. Adding more comprehensive normalization of heading text:
- Transliterate non-ASCII characters
- Replace certain special characters (e.g., '&' becomes 'and', '<' and '>' are removed)
- Handle emojis by removing them
- Normalize accented characters
- Trim and clean up various edge cases
3. Ensure the identifier works consistently across different types of input, including:
- Special characters
- Emojis
- Accented characters
- …

[2.x] Normalize Markdown heading identifiers

---

docs/creating-content/managing-assets.md
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/src/Facades/Vite.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php
packages/framework/tests/Unit/Facades/ViteFacadeTest.php
packages/framework/tests/Unit/ServeCommandOptionsUnitTest.php
packages/realtime-compiler/src/ConsoleOutput.php

Targets https://github.com/hydephp/develop/pull/2006
- Refactors code
- Adds documentation
- Adds more tests
- Throws if the path is not a supported extension (Laravel assumes non-CSS is JavaScript... I'd rather be explicit)
- Removes the internal `HYDE_SERVER_VITE` environment variable
- The complexity this adds to microoptimize things is not warranted yet
- The Vite server configuration already manages adding and removing the hotfile.
- <s>**We need this to print the start message. Instead, it renames the variable to be more clear it's internal**</s> Edit: Fixed by just touching the hotfile right away

[2.x] Improve the Vite integration

---

.github/workflows/split-monorepo.yml

**Key changes made:**
1.  Added new environment variables for author name and email from the head commit
2.  Updated Git config to use the original author's name and email instead of github-actions
3.  Experimental: Makes it so that it says that the original user authored and GitHub Actions committed
This will now attribute the split repository commits to the original author of the commit being synced.
---
**Background**
This workflow currently makes the split commit as the GitHub Actions user. This was originally so that if there are multiple commits, we may not want to attribute unrelated commits to authors. But I had an idea:
First, I was thinking that if the commit is a merge commit (like from a pull request), we can use the commit author then. Because if an author merges a PR, they …

Internal: Retain commit authors for split monorepo packages

---

packages/hyde/package.json

Reverts hydephp/develop#2115 as Tailwind 4 is breaking and we'll save that for HydePHP v2.0.

Revert "Bump tailwindcss from 3.4.17 to 4.0.12 in /packages/hyde"

---

.github/workflows/continuous-integration.yml
app/storage/framework/runtime/.gitignore
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/src/Facades/Vite.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php
packages/framework/tests/Unit/Facades/ViteFacadeTest.php
packages/hyde/vite.config.mjs
vite.config.mjs

Moves the Vite hot file from the cache directory to a new runtime directory under storage/framework. This aligns better with its actual purpose, as the file is used for runtime signaling, not caching.
- The hot file is now located at storage/framework/runtime/vite.hot.
- The Vite::running() method has been updated to reflect the new path.
- No external user-facing behavior is changed. Framework storage is internal.
- This change prepares the system for potential future runtime or IPC features.
The cache directory is intended for optimizing repeated computations, not for interprocess signaling or ephemeral runtime flags. Using a dedicated runtime directory makes internal filesystem structure clearer and more maintainable over time.

[2.x] Move internal Vite hot file to runtime directory for better semantics

---

.github/workflows/update-browserslist-db.yml

This GitHub Actions workflow will automatically update your Browserslist database every 3 months and create a pull request with the changes. Here's what it does:
1.  **Schedule**: Runs on the first day of January, April, July, and October (quarterly)
2.  **Manual trigger**: Can also be triggered manually via the workflow_dispatch event
3.  **Process**:
-   Checks out your repository
-   Sets up Node.js with npm caching
-   Installs dependencies
-   Runs the update-browserslist-db command
-   Creates a pull request with the changes

Create workflow to update Browserslist database

---

.github/scripts/RemoveStateLabels.js
.github/workflows/label-pull-requests.yml

Previous versions of actions/github-script (v6 and earlier) used CommonJS internally, where require() worked fine. Now it uses ESM, so the action fails.

Internal: Fix GitHub action that switched to ESM

---

RELEASE_NOTES.md
docs/creating-content/blog-posts.md
docs/creating-content/managing-assets.md
packages/framework/resources/views/components/post/image.blade.php
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Markdown/Contracts/FrontMatter/SubSchemas/FeaturedImageSchema.php
packages/framework/tests/Feature/FeaturedImageFactoryTest.php
packages/framework/tests/Feature/FeaturedImageTest.php
packages/framework/tests/Unit/SchemaContractsTest.php
packages/framework/tests/Unit/Views/FeaturedImageViewTest.php

Fixes https://github.com/hydephp/develop/issues/1718 by introducing a new "caption" field to just control the caption without having to remember the full syntax.

[2.x] Simplified front matter image schema

---

RELEASE_NOTES.md
_pages/404.blade.php
packages/framework/resources/views/components/navigation/navigation-brand.blade.php
packages/framework/resources/views/pages/404.blade.php
packages/framework/src/Foundation/Facades/Routes.php
packages/framework/src/Framework/Views/Components/BreadcrumbsComponent.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/tests/Unit/Facades/RouteFacadeTest.php
packages/realtime-compiler/src/Http/DashboardController.php
packages/realtime-compiler/src/Routing/PageRouter.php

This PR improves the Routes facade API by renaming methods to better communicate their behavior:
1. Renames `Routes::get()` (which returns null for missing routes) to `Routes::find()` to better indicate its trying to find, but is null safe
2. Renames `Routes::getOrFail()` to `Routes::get()` to make the exception-throwing behavior the default
**Benefits:**
- More predictable API: `get()` now fails fast with clear exceptions, matching Laravel conventions
- More descriptive naming: `find()` indicates it may return null
- Complete type safety: `find()` returns `?Route`, `get()` returns `Route`
**Breaking changes:**
- Code using `Routes::get('some-route')` needs to be updated to `Routes::find('some-route')` _if_ it needs to handle missing routes nullably
- Code using …

[2.x] Improve Routes facade method naming with find() and get()

---

CHANGELOG.md
RELEASE_NOTES.md
packages/framework/src/Foundation/HydeKernel.php

- Updated the `HydeKernel` array representation to include the Hyde version in https://github.com/hydephp/develop/pull/1786
- Registered the `cache:clear` command to make it easier to clear the cache in https://github.com/hydephp/develop/pull/1881
- Added a new `Hyperlinks::isRemote()` helper method to check if a URL is remote in https://github.com/hydephp/develop/pull/1882
- All page types now support the `description` front matter field (used in page metadata) in https://github.com/hydephp/develop/pull/1884
- Added a new `Filesystem::findFiles()` method to find files in a directory in https://github.com/hydephp/develop/pull/2064
- Added `webp` to the list of default media extensions in https://github.com/hydephp/framework/pull/663
- Added a new slug generation helper to improve …

HydePHP v1.8.0 - 2025-05-17

---

RELEASE_NOTES.md
docs/extensions/realtime-compiler.md
packages/realtime-compiler/bin/server.php
packages/realtime-compiler/resources/stubs/HydeValetDriver.php
packages/realtime-compiler/src/Console/Commands/HerdInstallCommand.php
packages/realtime-compiler/src/RealtimeCompilerServiceProvider.php

Merges https://github.com/hydephp/realtime-compiler/pull/30 and adds documentation

Add experimental support for Laravel Herd

---

packages/framework/src/Foundation/HydeKernel.php
packages/hyde/composer.json
packages/ui-kit/docs/composer.json

At long last, this is the first release candidate for HydePHP v2.0. Please stay tuned for the official release which will contain the finalized changeset and release notes with upgrade guide. However, for those who are curious - feel free to start testing this right now!

HydePHP v2 Release Candidate One

---

packages/framework/src/Console/Commands/RebuildPageCommand.php
packages/framework/tests/Feature/Commands/RebuildPageCommandTest.php

output message about file location fixed
Closes: 288
(cherry picked from commit 08ea48bfb4ba2fea3dd8b28bbe31d3bd190fd52c)

[2.x] Fix rebuild command showing the wrong console output

---

.github/workflows/sync-documentation-mirror.yml

Introduced a GitHub Actions workflow to automatically sync documentation from the monorepo to the hydephp/docs repository for relevant branches.

Add documentation sync workflow

---

package-lock.json
package.json

Updated the hyde-vite-plugin dependency from version 1.0.0-RC.4 to 1.0.0-RC.5 in package.json.

Bump hyde-vite-plugin to 1.0.0-RC.5

---

RELEASE_NOTES.md
docs/getting-started/console-commands.md
packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/tests/Feature/StaticSiteServiceTest.php

Replaces all occurrences of the --run-vite flag with --vite in documentation, command signature, implementation, and tests for consistency and clarity. Updates deprecation messages and related documentation to reflect the new flag name. This is not breaking as HydePHP v2 has not been released yet

[2.x] Rename --run-vite flag to --vite in build command

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Concerns/ImplementsStringHelpers.php
packages/framework/tests/Unit/HydeHelperFacadeMakeSlugTest.php

Updated the makeSlug helper to replace '@' with 'at' and '&' with 'and' before slugging. Adjusted related unit tests to reflect the new normalization behavior.

[2.x] Normalize @ and & in makeSlug helper 

---

RELEASE_NOTES.md
docs/creating-content/documentation-pages.md
packages/framework/src/Framework/Features/Navigation/NavigationMenuGenerator.php
packages/framework/tests/Feature/AutomaticNavigationConfigurationsTest.php

Refactored configuration option 'docs.sidebar_group_labels' to 'docs.sidebar.labels' throughout the codebase, documentation, and tests. Updated relevant documentation and release notes to reflect this breaking change and provided upgrade instructions.

[2.x] Rename docs.sidebar_group_labels to docs.sidebar.labels

---

CHANGELOG.md
packages/framework/src/Framework/Services/MarkdownService.php
packages/framework/tests/Feature/MarkdownServiceTest.php

Updated isDocumentationPage to use is_a for class and subclass detection. Added tests to verify correct attribution handling and isDocumentationPage behavior for DocumentationPage and its subclasses. This is so that this works for child classes.

[2.x] Improve documentation page detection in MarkdownService
