hydephp/develop

CHANGELOG.md
packages/framework/src/Actions/ChecksIfConfigIsUpToDate.php
packages/framework/tests/Feature/Actions/ChecksIfConfigIsUpToDateTest.php
packages/framework/tests/Feature/Commands/HydeUpdateConfigsCommandTest.php

Refactor ChecksIfConfigIsUpToDate to not have to read filesystem each time

---

CHANGELOG.md
docs/documentation-pages.md
packages/framework/resources/views/components/docs/search.blade.php

Adds a fallback which removes the search modal element and redirects to the search.html page when the dialogue element is not supported to fix https://github.com/hydephp/develop/issues/41

Add dialogue element fallback

---

packages/framework/src/Router.php
packages/framework/tests/Feature/RouterTest.php
tests/TestCase.php

Fixes https://github.com/hydephp/develop/issues/206

Convert Router into Singleton

---

app/bootstrap.php

(Hopefully) Fixes https://github.com/hydephp/develop/issues/212

Set Hyde base path using dirname instead of getcwd

---

RELEASE_NOTES.md
_pages/404.blade.php
packages/framework/resources/views/pages/404.blade.php
packages/framework/src/Concerns/Internal/FileHelpers.php
packages/framework/src/Services/RssFeedService.php
packages/framework/tests/Feature/Commands/HydeBuildRssFeedCommandTest.php
packages/framework/tests/Feature/Commands/HydeBuildSitemapCommandTest.php
packages/framework/tests/Feature/Concerns/GeneratesPageMetadataTest.php
packages/framework/tests/Feature/Concerns/HasPageMetadataTest.php
packages/framework/tests/Feature/Services/BuildHookServiceTest.php
packages/framework/tests/Feature/Services/RssFeedServiceTest.php
packages/framework/tests/Feature/Services/SitemapServiceTest.php
packages/framework/tests/Feature/Services/ValidationServiceTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php
packages/framework/tests/Unit/HasPageMetadataRssFeedLinkTest.php
packages/framework/tests/Unit/HydeUriPathHelperTest.php
packages/framework/tests/Unit/MarkdownPostHelpersTest.php

This makes it match both the site.name and the Laravel config, adding consistency.

Change config option site.site_url to site.url

---

RELEASE_NOTES.md
packages/framework/src/Commands/HydePublishHomepageCommand.php
packages/framework/tests/Feature/Commands/HydePublishHomepageCommandTest.php

Fixes https://github.com/hydephp/develop/issues/260

Always output published status for the selected homepage

---

packages/framework/src/Hyde.php

This allows for better IDE support and autocomplete

Add `@method` annotations to the Hyde facade

---

.github/workflows/split-monorepo.yml

Cleans up the test files in the split sub-repository https://github.com/hydephp/hyde.

Clean up Hyde/Hyde package files

---

RELEASE_NOTES.md
packages/framework/src/Contracts/HydeKernelContract.php

Adds base path methods to Kernel interface

Update HydeKernelContract interface

---

.github/workflows/continuous-integration.yml
.github/workflows/test-pull-requests.yml
composer.json
composer.lock
psalm.xml

https://shepherd.dev/github/hydephp/develop

Add psalm static analysis

---

packages/framework/src/Actions/SourceFileParser.php

Adds strong types and normalizes arguments to match conventions

Improve types for helpers added in https://github.com/hydephp/develop/pull/330

---

RELEASE_NOTES.md
packages/framework/src/Actions/PageModelConstructor.php
packages/framework/src/Actions/SourceFileParser.php
packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/tests/Feature/PageModelConstructorTest.php
packages/framework/tests/Feature/SourceFileParserTest.php

Creates a new action to move logic related to dynamic data construction from the page parser action

Create constructor action

---

packages/framework/src/Contracts/AbstractMarkdownPage.php
packages/framework/src/Contracts/MarkdownPageContract.php
packages/framework/src/Models/FrontMatter.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Unit/FrontMatterModelTest.php

Companion to https://github.com/hydephp/develop/pull/339

Add magic __set method to Markdown pages to set data in front matter

---

packages/framework/src/Actions/BladeMatterParser.php
packages/framework/src/Actions/SourceFileParser.php
packages/framework/src/Commands/HydeMakePostCommand.php
packages/framework/src/Commands/HydePackageDiscoverCommand.php
packages/framework/src/Commands/HydePublishViewsCommand.php
packages/framework/src/Commands/HydeRebuildStaticSiteCommand.php
packages/framework/src/Concerns/FrontMatter/Schemas/BlogPostSchema.php
packages/framework/src/Contracts/RouteFacadeContract.php
packages/framework/src/Hyde.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/src/Models/Route.php
packages/framework/src/Models/ValidationResult.php
packages/framework/src/Modules/DataCollections/DataCollection.php
packages/framework/src/Modules/Markdown/CodeblockFilepathProcessor.php
packages/framework/src/Modules/Markdown/Shortcodes/AbstractColoredBlockquote.php
packages/framework/src/PageCollection.php
packages/framework/src/Services/BuildService.php
packages/framework/src/Services/MarkdownService.php
packages/framework/src/Services/ValidationService.php
packages/framework/src/Views/Components/LinkComponent.php

Adds missing strongly typed parameters and return values, and fixes any improper ones, as discovered by Psalm.

Improve types

---

packages/framework/src/Commands/HydeBuildRssFeedCommand.php
packages/framework/src/Concerns/FrontMatter/Schemas/DocumentationPageSchema.php
packages/framework/src/Services/MarkdownService.php

Fixes some more issues discovered by Scrutinizer

Code quality improvements 

---

.github/workflows/continuous-integration.yml
packages/framework/src/Actions/BladeMatterParser.php
packages/framework/src/Actions/Constructors/FindsNavigationDataForPage.php
packages/framework/src/Actions/Constructors/FindsTitleForPage.php
packages/framework/src/Commands/HydePublishHomepageCommand.php
packages/framework/src/Commands/HydePublishViewsCommand.php
packages/framework/src/Commands/HydeUpdateConfigsCommand.php
packages/framework/src/Commands/HydeValidateCommand.php
packages/framework/src/Concerns/ActionCommand.php
packages/framework/src/Concerns/JsonSerializesArrayable.php
packages/framework/src/Contracts/AbstractPage.php
packages/framework/src/Contracts/PageContract.php
packages/framework/src/Exceptions/RouteNotFoundException.php
packages/framework/src/Exceptions/UnsupportedPageTypeException.php
packages/framework/src/Helpers/Features.php
packages/framework/src/HydeKernel.php
packages/framework/src/Models/Author.php
packages/framework/src/Models/FrontMatter.php
packages/framework/src/Models/Image.php
packages/framework/src/Models/NavItem.php
packages/framework/src/Models/NavigationMenu.php
packages/framework/src/Models/Pages/MarkdownPost.php
packages/framework/src/Models/Route.php
packages/framework/src/Models/ValidationResult.php
packages/framework/src/Services/DiscoveryService.php
packages/framework/tests/Unit/JsonSerializesArrayableTest.php

Fixes issues discovered by static analysis, and adds some extra types.

Fix static analysis issues

---

packages/framework/src/Commands/HydeBuildSearchCommand.php
packages/framework/src/HydeServiceProvider.php
packages/framework/src/Models/Author.php
packages/framework/src/Modules/Markdown/ShortcodeProcessor.php
packages/framework/src/Services/BuildHookService.php

Removes a todo that I'm not sure what it's mean to do, and links the rest to GitHub issues

Update todo PHPDocs comments

---

RELEASE_NOTES.md
packages/framework/resources/views/pages/documentation-search.blade.php
packages/framework/src/Actions/StaticPageBuilder.php
packages/framework/src/Concerns/AbstractPage.php
packages/framework/src/Contracts/PageContract.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/tests/Feature/AbstractPageTest.php
packages/framework/tests/Feature/RouteTest.php
packages/framework/tests/Unit/DocumentationPageTest.php
packages/framework/tests/Unit/MarkdownPostHelpersTest.php
projects/shelf/admin/src/AdminPage.php

These areas have overlapping responsibilities, and should be unified into a single API.

Merge getCurrentPagePath method into getRouteKey

---

packages/framework/src/Actions/CreatesNewMarkdownPostFile.php
packages/framework/src/Actions/PostBuildTasks/GenerateBuildManifest.php
packages/framework/src/Concerns/AbstractBuildTask.php
packages/framework/src/Concerns/BaseMarkdownPage.php
packages/framework/src/Concerns/Internal/ConstructsPageSchemas.php
packages/framework/src/Concerns/Internal/SetsUpMarkdownConverter.php
packages/framework/src/Models/Pages/DocumentationPage.php
packages/framework/src/Models/Pages/MarkdownPost.php

Code cleanup

---

packages/framework/src/Models/Support/Site.php
packages/framework/tests/Feature/SiteTest.php
packages/framework/tests/Models/SiteTest.php

Apparently the test needed to be in the feature namespace to be covering.

Fix missing coverage in the Site model

---

packages/framework/src/Models/Support/File.php

Solves issue #562 
Let me know if any changes needs to be made. I used appilication/xml instead of text/xml as the former was recommended. I could learn something new, thanks for the opportunity!

Added XML support to File.php

---

packages/testing/src/TestCase.php

Should fix https://github.com/hydephp/develop/issues/564

Flush the component cache when tearing down the test

---

packages/framework/resources/views/components/docs/documentation-article.blade.php
packages/framework/resources/views/layouts/docs.blade.php
packages/framework/src/Framework/Features/Documentation/SemanticDocumentationArticle.php
packages/framework/src/Pages/DocumentationPage.php
packages/framework/src/Support/Models/SemanticDocumentationArticle.php
packages/framework/tests/Feature/Services/HydeSmartDocsTest.php

Refactors the internal behaviour, not the result.

Refactor semantic documentation article feature

---

config/hyde.php
packages/framework/config/hyde.php
packages/framework/src/Facades/Author.php
packages/framework/src/Framework/Features/Blogging/Models/PostAuthor.php
packages/framework/tests/Feature/AuthorPostsIntegrationTest.php
packages/framework/tests/Feature/PostAuthorTest.php
packages/framework/tests/Unit/Facades/AuthorTest.php

Simplifies the public API by creating an author facade and simplifying the constructors.

Refactor the author model

---

packages/framework/src/Support/Models/File.php
packages/framework/tests/Feature/FileTest.php

Implements the tested behaviour

Implement the file model's array representation

---

.idea/misc.xml
packages/framework/src/Facades/Features.php
packages/framework/src/Foundation/FileCollection.php
packages/framework/src/Framework/Features/Navigation/NavItem.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/ConfigurableFeaturesTest.php

These refactors should not change any behaviour.

Minor code refactors

---

packages/framework/src/Framework/Services/BuildService.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/tests/Feature/DiscoveryServiceTest.php
packages/framework/tests/Feature/StaticSiteServiceTest.php

Adds support for up to three levels of nested directories for media files.

Allow media assets to be in subdirectories

---

packages/framework/src/Framework/Actions/CreatesNewPublicationFile.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldType.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/PublicationFieldTest.php
packages/framework/tests/Feature/PublicationFieldTypeTest.php
packages/framework/tests/Feature/PublicationTypeTest.php

Refactor PublicationFieldType class

---

packages/framework/src/Framework/Actions/Concerns/CreateAction.php
packages/framework/src/Framework/Actions/Contracts/CreateActionContract.php
packages/framework/src/Framework/Actions/CreatesNewPublicationFile.php
packages/framework/src/Framework/Actions/CreatesNewPublicationType.php
packages/framework/src/Framework/Actions/Interfaces/CreateActionContract.php
packages/framework/src/Framework/Actions/Interfaces/CreateActionInterface.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/CreateActionTest.php

This targets https://github.com/hydephp/develop/pull/685 via https://github.com/hydephp/develop/pull/688

Refactor create actions to reduce overlapping code and create a more consistent internal API

---

monorepo/HydeStan/HydeStan.php
monorepo/HydeStan/vendor/php-console/console.php

This change is not breaking as it only covers internal code.

Internal: Refactor static analyser 

---

packages/framework/src/Foundation/Filesystem.php
packages/framework/tests/Feature/Foundation/FilesystemTest.php

Adds a helper to implode path components into a string with directory separators.

Add helper to implode path components into a proper path string

---

packages/framework/src/Facades/Filesystem.php
packages/framework/tests/Feature/FilesystemFacadeTest.php

Makes some quick refactors and improvements for https://github.com/hydephp/develop/pull/695

Update the filesystem facade

---

packages/framework/src/Console/Commands/MakePublicationTypeCommand.php
packages/framework/src/Framework/Features/Publications/Models/PublicationFieldType.php
packages/framework/src/Framework/Features/Publications/Models/PublicationType.php
packages/framework/tests/Feature/Commands/MakePublicationTypeCommandTest.php
packages/framework/tests/Feature/PublicationFieldTypeTest.php
packages/framework/tests/Feature/PublicationTypeTest.php

Attempting to get ahead of merge conflicts, see https://github.com/hydephp/develop/pull/721

Cherry pick changes from rgasch:publications-feature

---

packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php

Adds types to all callback functions and does some minor code style refactors

Increase type coverage of DocumentationSidebar class 

---

docs/digging-deeper/advanced-markdown.md

Fixes https://github.com/hydephp/develop/issues/54
Keeping this open for just a little bit as I'm in the car and cannot test to double check that the changes work as I'm using the GitHub web editor.

Document colored blockquotes and code block filepaths

---

.github/workflows/test-pull-requests.yml

Fixes https://github.com/hydephp/develop/issues/787

Update PR test matrix to also run tests on PHP 8.2

---

packages/framework/src/Framework/Services/BuildService.php
packages/framework/tests/Feature/StaticSiteServiceTest.php

Refactors usage for method being removed in https://github.com/hydephp/develop/pull/823

Refactor build service to not use deprecated method

---

.idea/misc.xml
packages/framework/src/Foundation/Application.php
packages/framework/src/Foundation/Facades/Router.php
packages/framework/src/Foundation/Filesystem.php
packages/framework/src/Framework/Actions/BladeMatterParser.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/src/Markdown/Models/FrontMatter.php

Non-breaking PR to clean up code and fix inspection issues.

Clean up code

---

packages/framework/src/Console/Concerns/AsksToRebuildSite.php
packages/framework/src/Framework/Concerns/InteractsWithDirectories.php
packages/framework/src/Framework/Concerns/InteractsWithFrontMatter.php
packages/framework/src/Framework/Concerns/InvokableAction.php
packages/framework/src/Framework/Concerns/RegistersFileLocations.php
packages/framework/src/Framework/Features/BuildTasks/BuildTask.php
packages/framework/src/Framework/Features/DataCollections/DataCollectionServiceProvider.php
packages/framework/src/Framework/Services/AssetService.php
packages/framework/src/Framework/Services/BuildService.php
packages/framework/src/Framework/Services/BuildTaskService.php
packages/framework/src/Framework/Services/MarkdownService.php
packages/framework/src/Hyde.php
packages/framework/src/Markdown/Processing/BladeDownProcessor.php
packages/framework/src/Support/Filesystem/ProjectFile.php

Fixes some issues discovered by static analysis, mainly pertaining to type coverage.

Fix static analysis issues and improve type coverage

---

packages/framework/src/Console/Commands/BuildSiteCommand.php
packages/framework/src/Console/Commands/RebuildStaticSiteCommand.php
packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Console/Concerns/Command.php
packages/framework/src/Framework/Services/DiscoveryService.php
packages/framework/tests/Feature/CommandTest.php
packages/framework/tests/Feature/DiscoveryServiceTest.php

Hopefully having helpers like the InfoComment (from the publications branch) will help in creating console output that is visually consistent.

Create base command class containing refactored helpers for shared code

---

.github/workflows/continuous-integration.yml

Fixs https://github.com/hydephp/develop/issues/797

Create CI job to build and upload the upcoming documentation

---

packages/framework/src/Console/Commands/RebuildStaticSiteCommand.php
packages/framework/src/Console/Concerns/Command.php
packages/framework/tests/Feature/CommandTest.php
packages/testing/src/TestCase.php

Follow up to https://github.com/hydephp/develop/pull/891, cherry pinging the refactors to the master branch

Cherry pick base command changes from publications feature

---

packages/framework/src/Framework/Services/DocumentationSearchService.php
packages/framework/tests/Feature/Services/DocumentationSearchServiceTest.php

Just some additional code cleanups

Documentation search code cleanups

---

.github/workflows/static-analysis.yml

Apparently the last PR didn't work properly. My bad.

Internal: Fix Psalm action

---

packages/framework/src/Console/Commands/PublishViewsCommand.php
packages/framework/tests/Feature/Commands/PublishViewsCommandTest.php

Just some bug fixes and cleanups

Cleanup publish views command class

---

packages/framework/src/Pages/VirtualPage.php

This allows any custom logic in child classes to be applied

Update VirtualPage compile method to use accessors

---

packages/framework/src/Pages/Contracts/DynamicPage.php
packages/framework/src/Pages/InMemoryPage.php
packages/framework/src/Pages/VirtualPage.php
packages/framework/tests/Feature/DocumentationSearchPageTest.php
packages/framework/tests/Feature/HydeKernelDynamicPageClassesTest.php
packages/framework/tests/Feature/PaginatorTest.php
packages/framework/tests/Unit/Pages/InMemoryPageTest.php
packages/framework/tests/Unit/Pages/InMemoryPageUnitTest.php
packages/framework/tests/Unit/Pages/VirtualPageUnitTest.php
packages/framework/tests/Unit/Views/HeadComponentViewTest.php
psalm-baseline.xml

Renames experimental class VirtualPage to InMemoryPage and updates the documentation for surrounding pages.

Rename class VirtualPage to InMemoryPage

---

packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/src/PublicationService.php
packages/publications/tests/Feature/PublicationServiceTest.php

Fixes https://github.com/hydephp/publications/issues/3

Support the new custom media directory feature for publications media

---

packages/framework/src/Foundation/Providers/ConfigurationServiceProvider.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeServiceProviderTest.php

Creates a service provider responsible for managing configuration services.
Tracked in https://github.com/hydephp/develop/issues/939

Create configuration service provider

---

packages/framework/src/Foundation/Providers/ViewServiceProvider.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeServiceProviderTest.php

Creates a service provider responsible for managing view services.
Tracked in https://github.com/hydephp/develop/issues/939

Create view service provider

---

packages/framework/src/Foundation/Providers/ConfigurationServiceProvider.php

Noticed that we never actually merged our config files. Adding this as it's a good idea to provide fallbacks.

Merge configuration files in configuration service provider

---

app/bootstrap.php
packages/framework/src/Foundation/ConsoleKernel.php
packages/framework/tests/Unit/ConsoleKernelTest.php

Creates a custom console kernel implementation, and updates the bootstrap script to use it.

Create custom console kernel implementation

---

packages/realtime-compiler/src/Actions/RendersSearchPage.php
packages/realtime-compiler/tests/RealtimeCompilerTest.php

This was missed in https://github.com/hydephp/develop/pull/932

Update realtime compiler to support the new documentation search page

---

packages/framework/src/Foundation/Concerns/BaseFoundationCollection.php
packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Foundation/Kernel/PageCollection.php
packages/framework/src/Foundation/Kernel/RouteCollection.php
packages/framework/tests/Unit/BaseFoundationCollectionTest.php

Splits internal method into two

Split out extension callback running from discovery methods

---

packages/framework/src/Foundation/HydeKernel.php
packages/framework/src/Hyde.php
packages/framework/tests/Feature/HydeKernelTest.php

- Add $mediaDirectory to the HydeKernel's array representation
- Add method annotation for getRegisteredExtensions method

Update HydeKernel array representation and method annotations

---

packages/framework/src/Framework/Features/Blogging/Models/LocalFeaturedImage.php

Unwraps internal deprecated method. Fixes https://github.com/hydephp/develop/issues/996

Internal code cleanups

---

packages/framework/src/Facades/Features.php

Extracts a protected helper method

Clean up Features class

---

packages/framework/src/Foundation/Internal/LoadConfiguration.php

Cleans up the code, makes it more readable, and attains 100% type coverage.

Refactor internal LoadConfiguration class

---

packages/framework/src/Console/Commands/DebugCommand.php
packages/framework/src/Console/Commands/MakePostCommand.php
packages/framework/src/Console/Commands/PublishViewsCommand.php
packages/framework/src/Facades/Config.php
packages/framework/src/Foundation/Services/LoadYamlConfiguration.php
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Factories/NavigationDataFactory.php
packages/framework/src/Framework/Features/Blogging/Models/PostAuthor.php
packages/framework/src/Framework/Features/Blogging/Models/RemoteFeaturedImage.php
packages/framework/src/Framework/Features/Metadata/MetadataBag.php
packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php
packages/framework/src/Framework/Services/ChecksumService.php
packages/framework/src/Pages/BladePage.php
packages/framework/src/Support/Models/Redirect.php
packages/framework/src/Support/ReadingTime.php
packages/framework/tests/Feature/Services/ChecksumServiceTest.php

Non-breaking code cleanups to improve type coverage and overall code quality. Coverage is increased by about 1%.
See https://github.com/hydephp/develop/issues/1021

Improve type coverage and overall code quality

---

packages/framework/resources/views/components/docs/sidebar.blade.php

Fixes https://github.com/hydephp/develop/issues/1030

Refactor documentation sidebar height to be dynamic

---

packages/framework/resources/views/components/docs/collapsible-grouped-sidebar-navigation.blade.php
packages/framework/src/Framework/Features/Navigation/DocumentationSidebar.php
packages/framework/tests/Feature/Services/DocumentationSidebarTest.php

Moves logic from view to class and adds some generic types.

Clean up DocumentationSidebar class and view

---

packages/framework/src/Foundation/Internal/LoadConfiguration.php

Add experimental framework support for compiling HydeCLI to standalone application

Update LoadConfiguration to support static Phar config

---

packages/framework/src/Foundation/Concerns/BootsHydeKernel.php
packages/framework/src/Framework/HydeServiceProvider.php
packages/framework/tests/Feature/HydeKernelTest.php

Removes the internal readyToBoot handler as I don't think it should be needed

Remove internal readyToBoot handler

---

packages/framework/src/Console/Commands/RouteListCommand.php
packages/framework/src/Support/Models/RouteList.php
packages/framework/src/Support/Models/RouteListItem.php
packages/framework/tests/Feature/Commands/RouteListCommandTest.php
packages/framework/tests/Feature/RouteListTest.php

Extracts a model class to contain the the route list data and to provide formatting helpers. Fixes all relevant issues in https://github.com/hydephp/develop/issues/1102

Route list improvements

---

packages/publications/src/Models/PublicationPage.php
packages/publications/src/PublicationService.php
packages/publications/src/PublicationsExtension.php
packages/publications/tests/Feature/MakePublicationCommandTest.php
packages/publications/tests/Feature/PublicationFieldValidatorTest.php
packages/publications/tests/Feature/PublicationServiceTest.php
packages/publications/tests/Feature/PublicationsExtensionTest.php
packages/publications/tests/Feature/SeedPublicationCommandTest.php
packages/publications/tests/Feature/ValidatePublicationsCommandTest.php
packages/testing/src/TestCase.php

Fixes https://github.com/hydephp/publications/issues/9

Refactor publications into the kernel container

---

packages/publications/src/PublicationService.php
packages/publications/src/PublicationsExtension.php
packages/publications/tests/Feature/PublicationsExtensionTest.php
packages/testing/src/TestCase.php

Refactors changes made in https://github.com/hydephp/develop/pull/1138 to utilize features from https://github.com/hydephp/develop/pull/1144

Refactor the publications extension class internals

---

packages/publications/src/Models/PublicationPage.php
packages/publications/tests/Feature/PublicationPageUnitTest.php

Cherry picked from https://github.com/hydephp/develop/pull/1140, see https://github.com/hydephp/develop/pull/1140/files#r1119889529

Add PublicationPage::getType helper

---

packages/framework/src/Foundation/Concerns/ManagesExtensions.php
packages/framework/tests/Feature/HydeExtensionFeatureTest.php
packages/framework/tests/Unit/ExtensionsUnitTest.php

Updates the exception message to match the other exceptions in the method.

Update invalid extension registration exception message

---

packages/framework/resources/views/components/docs/search-scripts.blade.php

Fixes https://github.com/hydephp/develop/issues/1167

Update search scripts component to relatively resolve the documentation search index link

---

config/hyde.php
config/markdown.php
packages/framework/config/hyde.php
packages/framework/config/markdown.php

Reorders some settings and updates the embedded documentation. No change here is breaking.

Update and clean up the configuration stubs

---

packages/framework/src/Framework/Actions/MarkdownFileParser.php

Update MarkdownFileParser to use the Filesystem facade

---

packages/framework/src/Foundation/Facades/Files.php
packages/framework/src/Foundation/Facades/Pages.php
packages/framework/src/Foundation/Facades/Routes.php
packages/framework/src/Foundation/Kernel/FileCollection.php
packages/framework/src/Foundation/Kernel/PageCollection.php
packages/framework/src/Foundation/Kernel/RouteCollection.php
packages/framework/src/Pages/Concerns/HydePage.php
packages/framework/tests/Feature/FileCollectionTest.php

Final polishing to reduce complexity layovers from https://github.com/hydephp/develop/pull/1205

Finalize foundation collection facades

---

docs/creating-content/blog-posts.md
packages/framework/src/Facades/Features.php
packages/framework/src/Framework/Factories/BlogPostDataFactory.php
packages/framework/src/Framework/Factories/FeaturedImageFactory.php
packages/framework/src/Framework/Features/Blogging/Models/FeaturedImage.php
packages/framework/src/Markdown/Contracts/FrontMatter/BlogPostSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/FrontMatterSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/FrontMatterSchemas.php
packages/framework/src/Markdown/Contracts/FrontMatter/PageSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/SubSchemas/AuthorSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/SubSchemas/FeaturedImageSchema.php
packages/framework/src/Markdown/Contracts/FrontMatter/SubSchemas/NavigationSchema.php
packages/framework/src/Pages/InMemoryPage.php
packages/framework/src/Support/Filesystem/SourceFile.php
packages/framework/tests/Feature/FeaturedImageFactoryTest.php
packages/framework/tests/Feature/FeaturedImageTest.php
packages/framework/tests/Feature/HydePageTest.php
packages/framework/tests/Feature/MarkdownPostTest.php
packages/framework/tests/Unit/FeaturedImageUnitTest.php
packages/framework/tests/Unit/SchemaContractsTest.php
packages/framework/tests/Unit/Views/FeaturedImageViewTest.php
psalm-baseline.xml
tests/fixtures/_posts/typography-front-matter.md

This will, among others, fix https://github.com/hydephp/develop/issues/1223

Final round of code polishing

---

packages/realtime-compiler/README.md
packages/realtime-compiler/SECURITY.md

See https://github.com/hydephp/develop/issues/1229

RealtimeCompiler v3.0

---

packages/framework/src/Framework/Features/Blogging/Models/PostAuthor.php

Otherwise `static::all()->firstWhere('username', $username)` doesn't work.

Update PostAuthor::all() to map entries into array keyed by username

---

SECURITY.md

Fixes https://github.com/hydephp/develop/issues/1249

Update supported versions policy

---

README.md

Updates the packagist badges to lead to packagist and license to lead to the license page

Update readme badges to lead to something

---

RELEASE_NOTES.md
packages/framework/src/Framework/Services/AssetService.php
packages/framework/tests/Unit/AssetServiceUnitTest.php

Fixes https://github.com/hydephp/develop/issues/1322

Fix wrong HydeFront version constant

---

RELEASE_NOTES.md
packages/framework/resources/views/components/navigation/dropdown.blade.php

Fixes https://github.com/hydephp/develop/issues/1330

Close dropdown when clicking outside it or when pressing escape

---

packages/framework/tests/Unit/HydePageSerializableUnitTest.php

Just because I love unit tests and Jsonencoded HydePHP data.

Add unit tests for all serialized page types

---

monorepo/scripts/docs/MarkdownFormatter.php

Refactors for somewhat better OOP

Refactor internal Markdown formatter script

---

packages/publications/resources/views/tags_list.blade.php
packages/publications/src/Actions/GeneratesPublicationTagPages.php
packages/publications/src/Actions/SeedsPublicationFiles.php
packages/publications/src/Commands/MakePublicationCommand.php
packages/publications/src/Publications.php
packages/publications/src/PublicationsExtension.php
packages/publications/tests/Feature/GeneratesPublicationTagPagesTest.php
packages/publications/tests/Feature/MakePublicationCommandTest.php
packages/publications/tests/Feature/PublicationsExtensionTest.php
packages/publications/tests/Feature/SeedsPublicationFilesTest.php

Aggressively simplifies the publication tags class and merges the one remaining method into the publication service facade.

Finalize publication tags API

---

monorepo/scripts/ping-ci-server-with-type-coverage.php
monorepo/scripts/ping-openanalytics-testrunner.php

See https://hydephp.com/posts/sunsetting-hydephp-dot-se

Internal: Update monorepo scripts to use the HydePHP.com CI server

---

.github/workflows/end-to-end-testing.yml

Patch https://github.com/titusfortner/webdrivers/issues/247 via https://stackoverflow.com/a/76980976

Downgrade Chrome driver to v114

---

packages/framework/src/Foundation/HydeKernel.php

Updates readme and syncs up versioning

Framework version v1.3.2

---

packages/framework/src/Foundation/HydeKernel.php

Framework version v1.3.3

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy-documentation-preview.yml
.github/workflows/smoke-tests.yml
.github/workflows/test-pull-requests.yml
packages/testing/stubs/hyde-testing-workflow.stub

Fixes macOS tests failing, see https://github.com/shivammathur/setup-php/issues/780.

Bump PHP setup action for test runners

---

packages/framework/.github/workflows/run-tests.yml

Syncs back downstream patches to the monorepo.

Sync back with downstream repositories

---

RELEASE_NOTES.md
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php
packages/realtime-compiler/bin/server.php
packages/realtime-compiler/src/Console.php
packages/realtime-compiler/src/ConsoleOutput.php

Fancy serve command

---

packages/framework/src/Foundation/HydeKernel.php

Syncs back with https://github.com/hydephp/framework/pull/584

Merge downstream Framework patch version

---

RELEASE_NOTES.md
packages/framework/src/Foundation/Internal/LoadYamlConfiguration.php
packages/framework/tests/Feature/LoadYamlConfigurationTest.php

Fixes https://github.com/hydephp/develop/issues/1471

Expand dot notation when merging Yaml configuration

---

docs/digging-deeper/customization.md

Fixes https://github.com/hydephp/develop/issues/1470

Document automatic subdirectory navigation dropdown configuration

---

RELEASE_NOTES.md
packages/realtime-compiler/resources/dashboard.blade.php

This reverts a faulty change accidentally made in 679164bd2b57557a23c9b76fe469cee9dfe3195e

Fix wrong section title in dashboard

---

packages/framework/src/Foundation/HydeKernel.php

Framework version v1.4.1

---

packages/framework/src/Foundation/HydeKernel.php

Framework version v1.4.3

---

docs/advanced-features/build-tasks.md
docs/advanced-features/hyde-pages.md
docs/advanced-features/in-memory-pages.md
docs/architecture-concepts/autodiscovery.md
docs/architecture-concepts/automatic-routing.md
docs/architecture-concepts/dynamic-data-discovery.md
docs/architecture-concepts/extensions-api.md
docs/architecture-concepts/the-hydekernel.md
docs/creating-content/blog-posts.md
docs/creating-content/compile-and-deploy.md
docs/creating-content/documentation-pages.md
docs/creating-content/managing-assets.md
docs/creating-content/static-pages.md
docs/digging-deeper/advanced-customization.md
docs/extensions/ui-kit.md
packages/ui-kit/docs/documentation.md

Cleans up the documentation formatting and wording. Also fixes some embarrassing spelling mistakes that we should probably gloss over...

Clean up documentation

---

docs/creating-content/documentation-pages.md
docs/digging-deeper/advanced-markdown.md
docs/digging-deeper/customization.md
docs/digging-deeper/navigation.md

This feature is quite complex and deserves its own page.

Add dedicated navigation documentation page

---

docs/digging-deeper/helpers.md

Document stock includes

---

packages/framework/tests/Unit/Pages/BladePageUnitTest.php
packages/framework/tests/Unit/Pages/DocumentationPageUnitTest.php
packages/framework/tests/Unit/Pages/HtmlPageUnitTest.php
packages/framework/tests/Unit/Pages/InMemoryPageUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPageUnitTest.php
packages/framework/tests/Unit/Pages/MarkdownPostUnitTest.php
packages/framework/tests/helpers/BaseHydePageUnitTest.php
packages/framework/tests/helpers/BaseMarkdownPageUnitTest.php
packages/framework/tests/helpers/README.md

Makes some cleanup to internal testing code

Internal: Move testing helper classes to new helpers directory

---

packages/framework/tests/Feature/ExampleTest.php
packages/framework/tests/Unit/ExampleUnitTest.php

Adds some example tests that can just be copied as a base to create new tests.

Internal: Add example tests

---

.github/workflows/label-pull-requests.yml

Would be very nice if GitHub could warn about this before merging

Internal: Fix workflow formatting

---

packages/framework/tests/Unit/BuildTaskUnitTest.php

Add unit test to bring the base build task class up to 100% coverage

Internal: Add build task unit test

---

.github/workflows/smoke-tests.yml

Internal: Try to fix Codecov

---

RELEASE_NOTES.md
packages/framework/src/Framework/Factories/BlogPostDataFactory.php
packages/framework/tests/Unit/Pages/MarkdownPostHelpersTest.php

Fixes https://github.com/hydephp/develop/issues/1634

Strip Markdown from automatic blog post descriptions

---

packages/framework/src/Console/Commands/BuildSitemapCommand.php

Fixes https://github.com/hydephp/develop/issues/1666

Fix command description wording

---

.github/workflows/continuous-integration.yml

Should fix fast forward issues

Internal: Update Tailwind compiler to force push build

---

.github/workflows/continuous-integration.yml

Fixes the syntax made in https://github.com/hydephp/develop/pull/1688

Internal: Update Tailwind compiler to force push builds to the target branch

---

packages/hyde/.gitattributes

Syncs https://github.com/hydephp/hyde/pull/254 back into the monorepo

Merge changes from downstream repository

---

CHANGELOG.md
RELEASE_NOTES.md
docs/advanced-features/build-tasks.md
docs/digging-deeper/helpers.md
packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/src/Support/DataCollections.php
resources/assets/app.css
resources/assets/app.js

Imports used functions and formats files to normalize whitespace

Minor code cleanup

---

packages/framework/src/Foundation/HydeKernel.php

Framework version v1.7.1

---

packages/framework/src/Framework/Features/XmlGenerators/RssFeedGenerator.php

Updates an internal reference missed in https://github.com/hydephp/develop/pull/1794

Internal: Replace deprecated method usage

---

monorepo/HydeStan/HydeStan.php
packages/framework/tests/Feature/BladeMatterParserTest.php
packages/framework/tests/Feature/NavigationDataTest.php
packages/framework/tests/Feature/TypedConfigFacadeTest.php
packages/framework/tests/Feature/YamlConfigurationFeatureTest.php
packages/framework/tests/Unit/ServeCommandOptionsUnitTest.php
packages/framework/tests/Unit/TestingSupportHelpersMetaTest.php
packages/testing/src/FluentTestingHelpers.php

Adds a testing helper, and updates the static analyser to report test code style issues, and fixes those issues.

Internal: Improve testing helpers

---

monorepo/HydeStan/HydeStan.php
packages/framework/src/Foundation/Concerns/HandlesFoundationCollections.php
packages/framework/src/Foundation/Facades/Files.php

Fixes https://github.com/hydephp/develop/issues/1821

Add new HydeStan rules and resolve code style issues

---

monorepo/scripts/docs/MarkdownFormatter.php

Confirmed to have no effect on the results.

Internal: Refactor the Markdown formatter script with Claude

---

composer.json
composer.lock

Sometimes Composer gets stuck in an infinite loop, this seems to fix that. See https://github.com/composer/composer/issues/8710

Internal: Disable Composer API calls for VCS repository

---

RELEASE_NOTES.md
packages/hyde/composer.json
packages/realtime-compiler/.gitattributes
packages/realtime-compiler/.github/workflows/test.yml
packages/realtime-compiler/.gitignore
packages/realtime-compiler/bin/server.php
packages/realtime-compiler/composer.json
packages/realtime-compiler/phpunit.xml
packages/realtime-compiler/src/Http/ExceptionHandler.php
packages/realtime-compiler/tests/Integration/IntegrationTest.php
packages/realtime-compiler/tests/Integration/IntegrationTestCase.php
packages/realtime-compiler/tests/Integration/TestResponse.php
phpunit.xml.dist

Merges realtime compiler changes from the downstream master branch and https://github.com/hydephp/realtime-compiler/pull/27

Realtime compiler v3.6.0

---

.github/workflows/continuous-integration.yml
.github/workflows/smoke-tests.yml
composer.json
composer.lock

Replaces https://github.com/hydephp/develop/pull/1860

Improved junctioned Composer package version requirements

---

RELEASE_NOTES.md
packages/realtime-compiler/src/Actions/AssetFileLocator.php

Fixes https://github.com/hydephp/realtime-compiler/issues/26

Fix realtime compiler not being able to serve media assets in subdirectories 

---

RELEASE_NOTES.md
_pages/404.blade.php
packages/framework/resources/views/pages/404.blade.php

Fixes https://github.com/hydephp/develop/issues/1781

Update 404 page home link fallback to lead to the domain root

---

RELEASE_NOTES.md
packages/framework/config/commands.php
packages/framework/tests/Feature/Commands/CacheClearCommandTest.php

Fixes https://github.com/hydephp/develop/issues/1873

Register the cache clear command

---

RELEASE_NOTES.md
packages/framework/resources/views/components/article-excerpt.blade.php
packages/framework/resources/views/components/blog-post-feed.blade.php
packages/framework/tests/Unit/Views/ArticleExcerptViewTest.php

Adds more rich data to the blog post feed and blog post components

[2.x] Add more rich markup data to blog post components

---

packages/framework/src/Markdown/MarkdownConverter.php

Cannot remember what this was about, it's not relevant anymore.

Remove legacy class comment

---

packages/framework/src/Foundation/HydeKernel.php

Framework version v1.7.4

---

packages/framework/src/Console/Commands/ServeCommand.php
packages/framework/tests/Feature/Commands/ServeCommandTest.php

Fixes https://github.com/hydephp/hyde/issues/276

Fix serve command not handling project path with spaces

---

package-lock.json
package.json

Revert "Bump tailwindcss from 3.4.17 to 4.0.16"

---

RELEASE_NOTES.md
docs/getting-started/console-commands.md
packages/framework/src/Console/Commands/PublishViewsCommand.php
packages/framework/tests/Feature/Commands/PublishViewsCommandTest.php

Fixes https://github.com/hydephp/develop/issues/2142

Change "category" to "group" in PublishViewsCommand

---

RELEASE_NOTES.md
input.csv
output.md
parse.php

Adding the full code here if I need to run it later, will then squash merge to remove the temporary files when I pull it into the target branch.

[2.x] Parse and process release notes

---

packages/hyde/package.json

This got lost... Needs a test!

Use HydePHP v2 packages in the split Hyde package

---

packages/framework/src/Console/Commands/RebuildPageCommand.php
packages/framework/tests/Feature/Commands/RebuildPageCommandTest.php

output message about file location fixed
Fixes https://github.com/hydephp/hyde/issues/288

Fix rebuild command showing the wrong console output

---

package-lock.json
package.json
packages/hyde/package-lock.json
packages/hyde/package.json

Merges Tailwind Dependabot changes in one go
- Merges https://github.com/hydephp/develop/pull/2282
- Merges https://github.com/hydephp/develop/pull/2285
- Merges https://github.com/hydephp/develop/pull/2284
- Merges https://github.com/hydephp/develop/pull/2283

Merge Tailwind Dependabot changes
